// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2025.1/1166825 Production Release
//       HLS date: Sun Feb 16 14:04:49 PST 2025
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: gtombesi@corsica
// Generated date: Thu May 08 19:13:50 EDT 2025
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model LeakyreluController
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Constructor: sysc_sim_wrapper

CCS_RTL::sysc_sim_wrapper::sysc_sim_wrapper(
   const sc_module_name& nm
)
   : ccs_rtl(
      "ccs_rtl",
      "ccs_wrapper"
   )
   , clk("clk")
   , rst("rst")
   , acc_done("acc_done")
   , dma_read_chnl("dma_read_chnl")
   , dma_write_chnl("dma_write_chnl")
   , dma_read_ctrl("dma_read_ctrl")
   , dma_write_ctrl("dma_write_ctrl")
   , conf_info_ctrl_dma2acc("conf_info_ctrl_dma2acc")
   , conf_info_ctrl_plm2vec("conf_info_ctrl_plm2vec")
   , conf_info_ctrl_acc2dma("conf_info_ctrl_acc2dma")
   , vec_in_a("vec_in_a")
   , vec_in_b("vec_in_b")
   , vec_out("vec_out")
   , ccs_rtl_SIG_clk("ccs_rtl_SIG_clk")
   , ccs_rtl_SIG_rst("ccs_rtl_SIG_rst")
   , ccs_rtl_SIG_acc_done("ccs_rtl_SIG_acc_done")
   , ccs_rtl_SIG_dma_read_chnl_val("ccs_rtl_SIG_dma_read_chnl_val")
   , ccs_rtl_SIG_dma_read_chnl_rdy("ccs_rtl_SIG_dma_read_chnl_rdy")
   , ccs_rtl_SIG_dma_read_chnl_msg("ccs_rtl_SIG_dma_read_chnl_msg")
   , ccs_rtl_SIG_dma_write_chnl_val("ccs_rtl_SIG_dma_write_chnl_val")
   , ccs_rtl_SIG_dma_write_chnl_rdy("ccs_rtl_SIG_dma_write_chnl_rdy")
   , ccs_rtl_SIG_dma_write_chnl_msg("ccs_rtl_SIG_dma_write_chnl_msg")
   , ccs_rtl_SIG_dma_read_ctrl_val("ccs_rtl_SIG_dma_read_ctrl_val")
   , ccs_rtl_SIG_dma_read_ctrl_rdy("ccs_rtl_SIG_dma_read_ctrl_rdy")
   , ccs_rtl_SIG_dma_read_ctrl_msg("ccs_rtl_SIG_dma_read_ctrl_msg")
   , ccs_rtl_SIG_dma_write_ctrl_val("ccs_rtl_SIG_dma_write_ctrl_val")
   , ccs_rtl_SIG_dma_write_ctrl_rdy("ccs_rtl_SIG_dma_write_ctrl_rdy")
   , ccs_rtl_SIG_dma_write_ctrl_msg("ccs_rtl_SIG_dma_write_ctrl_msg")
   , ccs_rtl_SIG_conf_info_ctrl_dma2acc_val("ccs_rtl_SIG_conf_info_ctrl_dma2acc_val")
   , ccs_rtl_SIG_conf_info_ctrl_dma2acc_rdy("ccs_rtl_SIG_conf_info_ctrl_dma2acc_rdy")
   , ccs_rtl_SIG_conf_info_ctrl_dma2acc_msg("ccs_rtl_SIG_conf_info_ctrl_dma2acc_msg")
   , ccs_rtl_SIG_conf_info_ctrl_plm2vec_val("ccs_rtl_SIG_conf_info_ctrl_plm2vec_val")
   , ccs_rtl_SIG_conf_info_ctrl_plm2vec_rdy("ccs_rtl_SIG_conf_info_ctrl_plm2vec_rdy")
   , ccs_rtl_SIG_conf_info_ctrl_plm2vec_msg("ccs_rtl_SIG_conf_info_ctrl_plm2vec_msg")
   , ccs_rtl_SIG_conf_info_ctrl_acc2dma_val("ccs_rtl_SIG_conf_info_ctrl_acc2dma_val")
   , ccs_rtl_SIG_conf_info_ctrl_acc2dma_rdy("ccs_rtl_SIG_conf_info_ctrl_acc2dma_rdy")
   , ccs_rtl_SIG_conf_info_ctrl_acc2dma_msg("ccs_rtl_SIG_conf_info_ctrl_acc2dma_msg")
   , ccs_rtl_SIG_vec_in_a_val("ccs_rtl_SIG_vec_in_a_val")
   , ccs_rtl_SIG_vec_in_a_rdy("ccs_rtl_SIG_vec_in_a_rdy")
   , ccs_rtl_SIG_vec_in_a_msg("ccs_rtl_SIG_vec_in_a_msg")
   , ccs_rtl_SIG_vec_in_b_val("ccs_rtl_SIG_vec_in_b_val")
   , ccs_rtl_SIG_vec_in_b_rdy("ccs_rtl_SIG_vec_in_b_rdy")
   , ccs_rtl_SIG_vec_in_b_msg("ccs_rtl_SIG_vec_in_b_msg")
   , ccs_rtl_SIG_vec_out_val("ccs_rtl_SIG_vec_out_val")
   , ccs_rtl_SIG_vec_out_rdy("ccs_rtl_SIG_vec_out_rdy")
   , ccs_rtl_SIG_vec_out_msg("ccs_rtl_SIG_vec_out_msg")
   , SIG_SC_LOGIC_0("SIG_SC_LOGIC_0")
   , SIG_SC_LOGIC_1("SIG_SC_LOGIC_1")
{
   // Instantiate other modules
   ccs_rtl.clk(ccs_rtl_SIG_clk);
   ccs_rtl.rst(ccs_rtl_SIG_rst);
   ccs_rtl.acc_done(ccs_rtl_SIG_acc_done);
   ccs_rtl.dma_read_chnl_val(ccs_rtl_SIG_dma_read_chnl_val);
   ccs_rtl.dma_read_chnl_rdy(ccs_rtl_SIG_dma_read_chnl_rdy);
   ccs_rtl.dma_read_chnl_msg(ccs_rtl_SIG_dma_read_chnl_msg);
   ccs_rtl.dma_write_chnl_val(ccs_rtl_SIG_dma_write_chnl_val);
   ccs_rtl.dma_write_chnl_rdy(ccs_rtl_SIG_dma_write_chnl_rdy);
   ccs_rtl.dma_write_chnl_msg(ccs_rtl_SIG_dma_write_chnl_msg);
   ccs_rtl.dma_read_ctrl_val(ccs_rtl_SIG_dma_read_ctrl_val);
   ccs_rtl.dma_read_ctrl_rdy(ccs_rtl_SIG_dma_read_ctrl_rdy);
   ccs_rtl.dma_read_ctrl_msg(ccs_rtl_SIG_dma_read_ctrl_msg);
   ccs_rtl.dma_write_ctrl_val(ccs_rtl_SIG_dma_write_ctrl_val);
   ccs_rtl.dma_write_ctrl_rdy(ccs_rtl_SIG_dma_write_ctrl_rdy);
   ccs_rtl.dma_write_ctrl_msg(ccs_rtl_SIG_dma_write_ctrl_msg);
   ccs_rtl.conf_info_ctrl_dma2acc_val(ccs_rtl_SIG_conf_info_ctrl_dma2acc_val);
   ccs_rtl.conf_info_ctrl_dma2acc_rdy(ccs_rtl_SIG_conf_info_ctrl_dma2acc_rdy);
   ccs_rtl.conf_info_ctrl_dma2acc_msg(ccs_rtl_SIG_conf_info_ctrl_dma2acc_msg);
   ccs_rtl.conf_info_ctrl_plm2vec_val(ccs_rtl_SIG_conf_info_ctrl_plm2vec_val);
   ccs_rtl.conf_info_ctrl_plm2vec_rdy(ccs_rtl_SIG_conf_info_ctrl_plm2vec_rdy);
   ccs_rtl.conf_info_ctrl_plm2vec_msg(ccs_rtl_SIG_conf_info_ctrl_plm2vec_msg);
   ccs_rtl.conf_info_ctrl_acc2dma_val(ccs_rtl_SIG_conf_info_ctrl_acc2dma_val);
   ccs_rtl.conf_info_ctrl_acc2dma_rdy(ccs_rtl_SIG_conf_info_ctrl_acc2dma_rdy);
   ccs_rtl.conf_info_ctrl_acc2dma_msg(ccs_rtl_SIG_conf_info_ctrl_acc2dma_msg);
   ccs_rtl.vec_in_a_val(ccs_rtl_SIG_vec_in_a_val);
   ccs_rtl.vec_in_a_rdy(ccs_rtl_SIG_vec_in_a_rdy);
   ccs_rtl.vec_in_a_msg(ccs_rtl_SIG_vec_in_a_msg);
   ccs_rtl.vec_in_b_val(ccs_rtl_SIG_vec_in_b_val);
   ccs_rtl.vec_in_b_rdy(ccs_rtl_SIG_vec_in_b_rdy);
   ccs_rtl.vec_in_b_msg(ccs_rtl_SIG_vec_in_b_msg);
   ccs_rtl.vec_out_val(ccs_rtl_SIG_vec_out_val);
   ccs_rtl.vec_out_rdy(ccs_rtl_SIG_vec_out_rdy);
   ccs_rtl.vec_out_msg(ccs_rtl_SIG_vec_out_msg);
   
   // Register processes
   SC_METHOD(update_proc);
   sensitive  << clk << rst << ccs_rtl_SIG_acc_done << dma_read_chnl.Connections::InBlocking_Ports_abs<ac_int<64, true > >::val << ccs_rtl_SIG_dma_read_chnl_rdy << dma_read_chnl.Connections::InBlocking<ac_int<64, true >, Connections::SYN_PORT >::msg << ccs_rtl_SIG_dma_write_chnl_val << dma_write_chnl.Connections::OutBlocking_Ports_abs<ac_int<64, true > >::rdy << ccs_rtl_SIG_dma_write_chnl_msg << ccs_rtl_SIG_dma_read_ctrl_val << dma_read_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::rdy << ccs_rtl_SIG_dma_read_ctrl_msg << ccs_rtl_SIG_dma_write_ctrl_val << dma_write_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::rdy << ccs_rtl_SIG_dma_write_ctrl_msg << conf_info_ctrl_dma2acc.Connections::InBlocking_Ports_abs<conf_info_t >::val << ccs_rtl_SIG_conf_info_ctrl_dma2acc_rdy << conf_info_ctrl_dma2acc.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg << conf_info_ctrl_plm2vec.Connections::InBlocking_Ports_abs<conf_info_t >::val << ccs_rtl_SIG_conf_info_ctrl_plm2vec_rdy << conf_info_ctrl_plm2vec.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg << conf_info_ctrl_acc2dma.Connections::InBlocking_Ports_abs<conf_info_t >::val << ccs_rtl_SIG_conf_info_ctrl_acc2dma_rdy << conf_info_ctrl_acc2dma.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg << ccs_rtl_SIG_vec_in_a_val << vec_in_a.Connections::OutBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::rdy << ccs_rtl_SIG_vec_in_a_msg << ccs_rtl_SIG_vec_in_b_val << vec_in_b.Connections::OutBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::rdy << ccs_rtl_SIG_vec_in_b_msg << vec_out.Connections::InBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::val << ccs_rtl_SIG_vec_out_rdy << vec_out.Connections::InBlocking<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT >::msg;
   // Other constructor statements
   SIG_SC_LOGIC_0.write(SC_LOGIC_0);
   SIG_SC_LOGIC_1.write(SC_LOGIC_1);
}

// ---------------------------------------------------------------
// Process: SC_METHOD update_proc

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   
   // none.sc_in field_key=clk:2ef165e7-0029-46a0-81b6-62b8649d0b14-1557:clk:2ef165e7-0029-46a0-81b6-62b8649d0b14-1557
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1557; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:2ef165e7-0029-46a0-81b6-62b8649d0b14-1558:rst:2ef165e7-0029-46a0-81b6-62b8649d0b14-1558
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1558; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1558); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1558); // then write to RTL port
   
   // none.sc_out field_key=acc_done:2ef165e7-0029-46a0-81b6-62b8649d0b14-1559:acc_done:2ef165e7-0029-46a0-81b6-62b8649d0b14-1559
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1559;
   bool d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1559;
   t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1559 = ccs_rtl_SIG_acc_done.read();
   vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1559, 1, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1559);
   acc_done.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1559);
   
   // none.sc_in field_key=dma_read_chnl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1560:val:2ef165e7-0029-46a0-81b6-62b8649d0b14-1571
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1571; // NPS - LV to hold field
   type_to_vector(dma_read_chnl.Connections::InBlocking_Ports_abs<ac_int<64, true > >::val.read(),1,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1571); // read orig port and type convert
   ccs_rtl_SIG_dma_read_chnl_val.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1571); // then write to RTL port
   
   // none.sc_out field_key=dma_read_chnl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1560:rdy:2ef165e7-0029-46a0-81b6-62b8649d0b14-1572
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1572;
   bool d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1572;
   t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1572 = ccs_rtl_SIG_dma_read_chnl_rdy.read();
   vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1572, 1, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1572);
   dma_read_chnl.Connections::InBlocking_Ports_abs<ac_int<64, true > >::rdy.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1572);
   
   // none.sc_in field_key=dma_read_chnl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1560:msg:2ef165e7-0029-46a0-81b6-62b8649d0b14-1573
   sc_lv< 64 > t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1573; // NPS - LV to hold field
   type_to_vector(dma_read_chnl.Connections::InBlocking<ac_int<64, true >, Connections::SYN_PORT >::msg.read(),64,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1573); // read orig port and type convert
   ccs_rtl_SIG_dma_read_chnl_msg.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1573); // then write to RTL port
   
   // none.sc_out field_key=dma_write_chnl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1574:val:2ef165e7-0029-46a0-81b6-62b8649d0b14-1583
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1583;
   bool d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1583;
   t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1583 = ccs_rtl_SIG_dma_write_chnl_val.read();
   vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1583, 1, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1583);
   dma_write_chnl.Connections::OutBlocking_Ports_abs<ac_int<64, true > >::val.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1583);
   
   // none.sc_in field_key=dma_write_chnl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1574:rdy:2ef165e7-0029-46a0-81b6-62b8649d0b14-1584
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1584; // NPS - LV to hold field
   type_to_vector(dma_write_chnl.Connections::OutBlocking_Ports_abs<ac_int<64, true > >::rdy.read(),1,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1584); // read orig port and type convert
   ccs_rtl_SIG_dma_write_chnl_rdy.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1584); // then write to RTL port
   
   // none.sc_out field_key=dma_write_chnl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1574:msg:2ef165e7-0029-46a0-81b6-62b8649d0b14-1585
   sc_lv< 64 > t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1585;
   sc_dt::sc_lv<64 > d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1585;
   if ( ccs_rtl_SIG_dma_write_chnl_val.read() == SC_LOGIC_1 ) {
      t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1585 = ccs_rtl_SIG_dma_write_chnl_msg.read();
      vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1585, 64, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1585);
      dma_write_chnl.Connections::OutBlocking<ac_int<64, true >, Connections::SYN_PORT >::msg.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1585);
   }
   
   // none.sc_out field_key=dma_read_ctrl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1586:val:2ef165e7-0029-46a0-81b6-62b8649d0b14-1595
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1595;
   bool d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1595;
   t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1595 = ccs_rtl_SIG_dma_read_ctrl_val.read();
   vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1595, 1, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1595);
   dma_read_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::val.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1595);
   
   // none.sc_in field_key=dma_read_ctrl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1586:rdy:2ef165e7-0029-46a0-81b6-62b8649d0b14-1596
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1596; // NPS - LV to hold field
   type_to_vector(dma_read_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::rdy.read(),1,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1596); // read orig port and type convert
   ccs_rtl_SIG_dma_read_ctrl_rdy.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1596); // then write to RTL port
   
   // none.sc_out field_key=dma_read_ctrl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1586:msg:2ef165e7-0029-46a0-81b6-62b8649d0b14-1597
   sc_lv< 73 > t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1597;
   sc_dt::sc_lv<73 > d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1597;
   if ( ccs_rtl_SIG_dma_read_ctrl_val.read() == SC_LOGIC_1 ) {
      t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1597 = ccs_rtl_SIG_dma_read_ctrl_msg.read();
      vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1597, 73, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1597);
      dma_read_ctrl.Connections::OutBlocking<dma_info_t, Connections::SYN_PORT >::msg.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1597);
   }
   
   // none.sc_out field_key=dma_write_ctrl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1598:val:2ef165e7-0029-46a0-81b6-62b8649d0b14-1603
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1603;
   bool d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1603;
   t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1603 = ccs_rtl_SIG_dma_write_ctrl_val.read();
   vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1603, 1, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1603);
   dma_write_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::val.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1603);
   
   // none.sc_in field_key=dma_write_ctrl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1598:rdy:2ef165e7-0029-46a0-81b6-62b8649d0b14-1604
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1604; // NPS - LV to hold field
   type_to_vector(dma_write_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::rdy.read(),1,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1604); // read orig port and type convert
   ccs_rtl_SIG_dma_write_ctrl_rdy.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1604); // then write to RTL port
   
   // none.sc_out field_key=dma_write_ctrl:2ef165e7-0029-46a0-81b6-62b8649d0b14-1598:msg:2ef165e7-0029-46a0-81b6-62b8649d0b14-1605
   sc_lv< 73 > t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1605;
   sc_dt::sc_lv<73 > d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1605;
   if ( ccs_rtl_SIG_dma_write_ctrl_val.read() == SC_LOGIC_1 ) {
      t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1605 = ccs_rtl_SIG_dma_write_ctrl_msg.read();
      vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1605, 73, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1605);
      dma_write_ctrl.Connections::OutBlocking<dma_info_t, Connections::SYN_PORT >::msg.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1605);
   }
   
   // none.sc_in field_key=conf_info_ctrl_dma2acc:2ef165e7-0029-46a0-81b6-62b8649d0b14-1606:val:2ef165e7-0029-46a0-81b6-62b8649d0b14-1615
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1615; // NPS - LV to hold field
   type_to_vector(conf_info_ctrl_dma2acc.Connections::InBlocking_Ports_abs<conf_info_t >::val.read(),1,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1615); // read orig port and type convert
   ccs_rtl_SIG_conf_info_ctrl_dma2acc_val.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1615); // then write to RTL port
   
   // none.sc_out field_key=conf_info_ctrl_dma2acc:2ef165e7-0029-46a0-81b6-62b8649d0b14-1606:rdy:2ef165e7-0029-46a0-81b6-62b8649d0b14-1616
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1616;
   bool d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1616;
   t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1616 = ccs_rtl_SIG_conf_info_ctrl_dma2acc_rdy.read();
   vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1616, 1, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1616);
   conf_info_ctrl_dma2acc.Connections::InBlocking_Ports_abs<conf_info_t >::rdy.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1616);
   
   // none.sc_in field_key=conf_info_ctrl_dma2acc:2ef165e7-0029-46a0-81b6-62b8649d0b14-1606:msg:2ef165e7-0029-46a0-81b6-62b8649d0b14-1617
   sc_lv< 160 > t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1617; // NPS - LV to hold field
   type_to_vector(conf_info_ctrl_dma2acc.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg.read(),160,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1617); // read orig port and type convert
   ccs_rtl_SIG_conf_info_ctrl_dma2acc_msg.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1617); // then write to RTL port
   
   // none.sc_in field_key=conf_info_ctrl_plm2vec:2ef165e7-0029-46a0-81b6-62b8649d0b14-1618:val:2ef165e7-0029-46a0-81b6-62b8649d0b14-1623
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1623; // NPS - LV to hold field
   type_to_vector(conf_info_ctrl_plm2vec.Connections::InBlocking_Ports_abs<conf_info_t >::val.read(),1,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1623); // read orig port and type convert
   ccs_rtl_SIG_conf_info_ctrl_plm2vec_val.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1623); // then write to RTL port
   
   // none.sc_out field_key=conf_info_ctrl_plm2vec:2ef165e7-0029-46a0-81b6-62b8649d0b14-1618:rdy:2ef165e7-0029-46a0-81b6-62b8649d0b14-1624
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1624;
   bool d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1624;
   t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1624 = ccs_rtl_SIG_conf_info_ctrl_plm2vec_rdy.read();
   vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1624, 1, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1624);
   conf_info_ctrl_plm2vec.Connections::InBlocking_Ports_abs<conf_info_t >::rdy.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1624);
   
   // none.sc_in field_key=conf_info_ctrl_plm2vec:2ef165e7-0029-46a0-81b6-62b8649d0b14-1618:msg:2ef165e7-0029-46a0-81b6-62b8649d0b14-1625
   sc_lv< 160 > t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1625; // NPS - LV to hold field
   type_to_vector(conf_info_ctrl_plm2vec.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg.read(),160,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1625); // read orig port and type convert
   ccs_rtl_SIG_conf_info_ctrl_plm2vec_msg.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1625); // then write to RTL port
   
   // none.sc_in field_key=conf_info_ctrl_acc2dma:2ef165e7-0029-46a0-81b6-62b8649d0b14-1626:val:2ef165e7-0029-46a0-81b6-62b8649d0b14-1631
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1631; // NPS - LV to hold field
   type_to_vector(conf_info_ctrl_acc2dma.Connections::InBlocking_Ports_abs<conf_info_t >::val.read(),1,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1631); // read orig port and type convert
   ccs_rtl_SIG_conf_info_ctrl_acc2dma_val.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1631); // then write to RTL port
   
   // none.sc_out field_key=conf_info_ctrl_acc2dma:2ef165e7-0029-46a0-81b6-62b8649d0b14-1626:rdy:2ef165e7-0029-46a0-81b6-62b8649d0b14-1632
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1632;
   bool d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1632;
   t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1632 = ccs_rtl_SIG_conf_info_ctrl_acc2dma_rdy.read();
   vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1632, 1, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1632);
   conf_info_ctrl_acc2dma.Connections::InBlocking_Ports_abs<conf_info_t >::rdy.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1632);
   
   // none.sc_in field_key=conf_info_ctrl_acc2dma:2ef165e7-0029-46a0-81b6-62b8649d0b14-1626:msg:2ef165e7-0029-46a0-81b6-62b8649d0b14-1633
   sc_lv< 160 > t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1633; // NPS - LV to hold field
   type_to_vector(conf_info_ctrl_acc2dma.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg.read(),160,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1633); // read orig port and type convert
   ccs_rtl_SIG_conf_info_ctrl_acc2dma_msg.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1633); // then write to RTL port
   
   // none.sc_out field_key=vec_in_a:2ef165e7-0029-46a0-81b6-62b8649d0b14-1634:val:2ef165e7-0029-46a0-81b6-62b8649d0b14-1643
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1643;
   bool d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1643;
   t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1643 = ccs_rtl_SIG_vec_in_a_val.read();
   vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1643, 1, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1643);
   vec_in_a.Connections::OutBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::val.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1643);
   
   // none.sc_in field_key=vec_in_a:2ef165e7-0029-46a0-81b6-62b8649d0b14-1634:rdy:2ef165e7-0029-46a0-81b6-62b8649d0b14-1644
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1644; // NPS - LV to hold field
   type_to_vector(vec_in_a.Connections::OutBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::rdy.read(),1,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1644); // read orig port and type convert
   ccs_rtl_SIG_vec_in_a_rdy.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1644); // then write to RTL port
   
   // none.sc_out field_key=vec_in_a:2ef165e7-0029-46a0-81b6-62b8649d0b14-1634:msg:2ef165e7-0029-46a0-81b6-62b8649d0b14-1645
   sc_lv< 512 > t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1645;
   sc_dt::sc_lv<512 > d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1645;
   if ( ccs_rtl_SIG_vec_in_a_val.read() == SC_LOGIC_1 ) {
      t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1645 = ccs_rtl_SIG_vec_in_a_msg.read();
      vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1645, 512, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1645);
      vec_in_a.Connections::OutBlocking<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT >::msg.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1645);
   }
   
   // none.sc_out field_key=vec_in_b:2ef165e7-0029-46a0-81b6-62b8649d0b14-1646:val:2ef165e7-0029-46a0-81b6-62b8649d0b14-1651
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1651;
   bool d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1651;
   t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1651 = ccs_rtl_SIG_vec_in_b_val.read();
   vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1651, 1, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1651);
   vec_in_b.Connections::OutBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::val.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1651);
   
   // none.sc_in field_key=vec_in_b:2ef165e7-0029-46a0-81b6-62b8649d0b14-1646:rdy:2ef165e7-0029-46a0-81b6-62b8649d0b14-1652
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1652; // NPS - LV to hold field
   type_to_vector(vec_in_b.Connections::OutBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::rdy.read(),1,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1652); // read orig port and type convert
   ccs_rtl_SIG_vec_in_b_rdy.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1652); // then write to RTL port
   
   // none.sc_out field_key=vec_in_b:2ef165e7-0029-46a0-81b6-62b8649d0b14-1646:msg:2ef165e7-0029-46a0-81b6-62b8649d0b14-1653
   sc_lv< 512 > t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1653;
   sc_dt::sc_lv<512 > d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1653;
   if ( ccs_rtl_SIG_vec_in_b_val.read() == SC_LOGIC_1 ) {
      t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1653 = ccs_rtl_SIG_vec_in_b_msg.read();
      vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1653, 512, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1653);
      vec_in_b.Connections::OutBlocking<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT >::msg.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1653);
   }
   
   // none.sc_in field_key=vec_out:2ef165e7-0029-46a0-81b6-62b8649d0b14-1654:val:2ef165e7-0029-46a0-81b6-62b8649d0b14-1663
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1663; // NPS - LV to hold field
   type_to_vector(vec_out.Connections::InBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::val.read(),1,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1663); // read orig port and type convert
   ccs_rtl_SIG_vec_out_val.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1663); // then write to RTL port
   
   // none.sc_out field_key=vec_out:2ef165e7-0029-46a0-81b6-62b8649d0b14-1654:rdy:2ef165e7-0029-46a0-81b6-62b8649d0b14-1664
   sc_logic t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1664;
   bool d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1664;
   t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1664 = ccs_rtl_SIG_vec_out_rdy.read();
   vector_to_type(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1664, 1, &d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1664);
   vec_out.Connections::InBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::rdy.write(d_2ef165e7_0029_46a0_81b6_62b8649d0b14_1664);
   
   // none.sc_in field_key=vec_out:2ef165e7-0029-46a0-81b6-62b8649d0b14-1654:msg:2ef165e7-0029-46a0-81b6-62b8649d0b14-1665
   sc_lv< 512 > t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1665; // NPS - LV to hold field
   type_to_vector(vec_out.Connections::InBlocking<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT >::msg.read(),512,t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1665); // read orig port and type convert
   ccs_rtl_SIG_vec_out_msg.write(t_2ef165e7_0029_46a0_81b6_62b8649d0b14_1665); // then write to RTL port
}
