#ifndef __INCLUDED_DUAL_PORT_RBW_H__
#define __INCLUDED_DUAL_PORT_RBW_H__

// SystemC memory model of DUAL_PORT_RBW
// Generated by Catapult memory generator
// Generated by:   gtombesi
// Generated date: Mon May  5 16:30:43 2025

// The following classes have been defined:
//     class DUAL_PORT_RBW a 0 delay "structural" model of the RAM

//     class DUAL_PORT_RBW_model<TLM/SYN>::mem<T,size,TLM/SYN>
//         A memory model that can be instanced and used for simulation and synthesis

//     class DUAL_PORT_RBW_model<TLM/SYN>::port_0_port<T,size,TLM/SYN>
//         a model of an external port with read capability

//     class DUAL_PORT_RBW_model<TLM/SYN>::port_1_port<T,size,TLM/SYN>
//         a model of an external port with write capability

#include <ccs_types.h>
#ifndef NO_ASSERTS
#include <assert.h>
#endif

#pragma map_to_module DUAL_PORT_RBW
template <
  int ram_id,
  int AddressSz,
  int data_width,
  int Sz>
class DUAL_PORT_RBW : public sc_module
{
public:
  sc_in< bool >   clk;
  sc_in< bool >   clk_en;
  sc_in< sc_lv<data_width> >   din;
  sc_out< sc_lv<data_width> >   qout;
  sc_in< sc_lv<AddressSz> >   r_adr;
  sc_in< sc_lv<AddressSz> >   w_adr;
  sc_in< bool >   w_en;

#if !defined(__SYNTHESIS__)
  sc_signal<sc_lv<data_width> > *mem = new sc_signal<sc_lv<data_width> > [Sz];

~DUAL_PORT_RBW() {
  delete[] mem;
}
#endif

  SC_CTOR(DUAL_PORT_RBW) :
    clk("clk")
    ,clk_en("clk_en")
    ,din("din")
    ,qout("qout")
    ,r_adr("r_adr")
    ,w_adr("w_adr")
    ,w_en("w_en")
  {
    SC_METHOD(seq_proc_1);
    dont_initialize();
    sensitive << clk.pos();
  }

  void seq_proc_1() {
#if !defined(__SYNTHESIS__)
    if ( clk_en.read() ) {
      int address;
      // read
      sc_lv<data_width> mem_dat1; // not initialized
      vector_to_type( r_adr.read(), false, &address );
#if !defined(NO_ASSERTS)
      assert( address>=0 && address<Sz );
#endif
      if( address<0 || address>=Sz ) { 
        std::ostringstream msg;
        msg << "DUAL_PORT_RBW out-of-bounds read detected from address "<< address << " mapped to address=0";
        SC_REPORT_WARNING(this->name(), msg.str().c_str());
        address = 0;
      }
      mem_dat1 = mem[address];
      qout.write( mem_dat1 );

      // write
      if ((clk_en==1) && (w_en==1)) {
        vector_to_type( w_adr.read(), false, &address );
#if !defined(NO_ASSERTS)
        assert( address>=0 && address<Sz );
#endif
        if( address<0 || address>=Sz ) { 
          std::ostringstream msg;
          msg << "DUAL_PORT_RBW out-of-bounds write detected to address " << address << " mapped to address=0";
          SC_REPORT_WARNING(this->name(), msg.str().c_str());
          address = 0;
        }
        mem[address] = din.read();
      }

    }
#endif
  }

#if !defined(__SYNTHESIS__)
  // NOTE: this method is intended for use by testbenches only. It is not synthesizable!
  sc_lv< data_width> tb_read( int address ) const {
#ifndef NO_ASSERTS
    assert( address>=0 && address < Sz);
#endif
    return mem[address];
  }

  // NOTE: this method is intended for use by testbenches only. It is not synthesizable!
  void tb_write( int address, sc_lv<data_width> data ) {
#ifndef NO_ASSERTS
    assert( address>=0 && address < Sz);
#endif
    mem[address] = data;
  }

#endif
};

template <abstraction_t source_abstraction = AUTO>
class DUAL_PORT_RBW_model {
public:
#if defined(__SYNTHESIS__)
  template <class T, unsigned int size, abstraction_t impl_abstraction = SYN> class mem{};
private:
  template <class T, unsigned int size, abstraction_t impl_abstraction = SYN> class port_0_local;
  template <class T, unsigned int size, abstraction_t impl_abstraction = SYN> class port_1_local;
public:
  template <class T, unsigned int size, abstraction_t impl_abstraction = SYN> class port_0_port;
  template <class T, unsigned int size, abstraction_t impl_abstraction = SYN> class port_1_port;

#elif defined (CCS_DUT_CYCLE) || defined (CCS_DUT_RTL)
  template <class T, unsigned int size, abstraction_t impl_abstraction = (source_abstraction==AUTO) ? SYN : source_abstraction>
      class mem{};
private:
  template <class T, unsigned int size, abstraction_t impl_abstraction = (source_abstraction==AUTO) ? SYN : source_abstraction>
      class port_0_local;
  template <class T, unsigned int size, abstraction_t impl_abstraction = (source_abstraction==AUTO) ? SYN : source_abstraction>
      class port_1_local;
public:
  template <class T, unsigned int size, abstraction_t impl_abstraction = (source_abstraction==AUTO) ? SYN : source_abstraction>
      class port_0_port;
  template <class T, unsigned int size, abstraction_t impl_abstraction = (source_abstraction==AUTO) ? SYN : source_abstraction>
      class port_1_port;

#else
  template <class T, unsigned int size, abstraction_t impl_abstraction = (source_abstraction==AUTO) ? P2P_DEFAULT_VIEW
      : source_abstraction> class mem{};
private:
  template <class T, unsigned int size, abstraction_t impl_abstraction = (source_abstraction==AUTO) ? P2P_DEFAULT_VIEW
      : source_abstraction> class port_0_local;
  template <class T, unsigned int size, abstraction_t impl_abstraction = (source_abstraction==AUTO) ? P2P_DEFAULT_VIEW
      : source_abstraction> class port_1_local;
public:
  template <class T, unsigned int size, abstraction_t impl_abstraction = (source_abstraction==AUTO) ? P2P_DEFAULT_VIEW
      : source_abstraction> class port_0_port;
  template <class T, unsigned int size, abstraction_t impl_abstraction = (source_abstraction==AUTO) ? P2P_DEFAULT_VIEW
      : source_abstraction> class port_1_port;

#endif

  // ***********************************************
  // TLM TLM TLM TLM TLM TLM TLM TLM TLM TLM TLM TLM
  //    This code is only for TLM simulation only
  // ***********************************************

  template <class T, unsigned int size>
  class mem<T,size,TLM>
  {
    enum {
      addr_width = nbits<size-1>::val,
      signedtype = mc_typedef_T_traits<T>::issigned,
      data_width = mc_typedef_T_traits<T>::bitwidth
    };
  public:
    void write (ac_int<addr_width,false> addr, T data=0) {
      port_1_port_instance.reset_chk.test();
#ifndef NO_ASSERTS
      assert( addr>=0 && addr<size );
#endif
      array[addr] = data;
    };

    T read ( ac_int<addr_width,false> addr ) {
#ifndef NO_ASSERTS
      assert( addr>=0 && addr<size );
#endif
      port_0_port_instance.reset_chk.test();
      return array[addr];
    }

    T &operator [] (int index) {
#ifndef NO_ASSERTS
      assert( index>=0 && index<size );
#endif
      return array[index];
    }

    const T &operator [] (int index) const {
#ifndef NO_ASSERTS
      assert( index>=0 && index<size );
#endif
      return array[index];
    }

  public:
    // NOTE: this method is intended for use by testbenches only. It is not synthesizable!
    T tb_read( int address ) const {
#ifndef NO_ASSERTS
      assert( address>=0 && address <size );
#endif
      return array[address];
    }

    // NOTE: this method is intended for use by testbenches only. It is not synthesizable!
    void tb_write( int address, T data ) {
#ifndef NO_ASSERTS
      assert( address>=0 && address <size );
#endif
      array[address] = data;
    }

  public:
    mem(const char* name = "unnamed_")
      : port_0_port_instance(*this, ccs_concat(name,"port_0"))
      , port_1_port_instance(*this, ccs_concat(name,"port_1"))
      {}

    ~mem() {
    delete[] array;
    }

    void reset_read() {
      port_0_port_instance.reset();
    }

    void reset_write() {
      port_1_port_instance.reset();
    }

    void clk(sc_in<bool> &clk_arg) {
      port_0_port_instance.clock_ok();
      port_1_port_instance.clock_ok();
    }
    #ifdef VCS_SYSTEMC
    // Bind may fail due to custom sc_writer_policy::SNPS_SC_WRITER_POLICY
    //  Force the one writer policy used with sc_clock
    void clk(sc_signal<bool,sc_core::SC_ONE_WRITER> &clk_arg)
    #else
    void clk(sc_signal<bool> &clk_arg)
    #endif
    {
      port_0_port_instance.clock_ok();
      port_1_port_instance.clock_ok();
    }

    void clk_en(sc_in<bool> &clk_en_arg) {}
    void clk_en(sc_signal<bool> &clk_en_arg) {}

    port_0_local<T,size,TLM>port_0_port_instance;
    port_1_local<T,size,TLM>port_1_port_instance;
  private:
    T *array = new T [size];
    friend class port_0_local<T,size,TLM>;
    friend class port_1_local<T,size,TLM>;
  };

private:
  template <class T, unsigned int size>
  class port_0_local<T,size,TLM>
  {
    enum {
      addr_width = nbits<size-1>::val,
      signedtype = mc_typedef_T_traits<T>::issigned,
      data_width = mc_typedef_T_traits<T>::bitwidth
    };
    p2p_checker reset_chk;
    p2p_checker clock_chk;
  public:
    void clock_ok() {clock_chk.ok();}

    port_0_local (mem<T,size,TLM> &my_parent, const char *name)
      : reset_chk( name, "call reset()", "access this memory")
      , clock_chk( name, "bind the clock port", "access this memory")
      , parent(my_parent)
      {}

    void reset() {reset_chk.ok();}

    const T &operator [] (int index) const {
      reset_chk.test();
      clock_chk.test();
#ifndef NO_ASSERTS
      assert( index>=0 && index<size );
#endif
      return parent.array[index];
    }

    T read ( ac_int<addr_width,false> addr ) {
      reset_chk.test();
      clock_chk.test();
#ifndef NO_ASSERTS
      assert( addr>=0 && addr<size );
#endif
      return parent.read(addr);
    }

  private:
    mem<T,size,TLM> &parent;
    friend class mem<T,size,TLM>;
  };

  template <class T, unsigned int size>
  class port_1_local<T,size,TLM>
  {
    enum {
      addr_width = nbits<size-1>::val,
      signedtype = mc_typedef_T_traits<T>::issigned,
      data_width = mc_typedef_T_traits<T>::bitwidth
    };
    p2p_checker reset_chk;
    p2p_checker clock_chk;
  public:
    void clock_ok() {clock_chk.ok();}

    port_1_local (mem<T,size,TLM> &my_parent, const char *name)
      : reset_chk( name, "call reset()", "access this memory")
      , clock_chk( name, "bind the clock port", "access this memory")
      , parent(my_parent)
      {}

    void reset() {reset_chk.ok();}

    T &operator [] (int index) {
      reset_chk.test();
      clock_chk.test();
      return parent.array[index];
    }

    const T &operator [] (int index) const {
      reset_chk.test();
      clock_chk.test();
#ifndef NO_ASSERTS
      assert( index>=0 && index<size );
#endif
      return parent.array[index];
    }

    void write (ac_int<addr_width,false> addr, T data=0) {
      reset_chk.test();
      clock_chk.test();
#ifndef NO_ASSERTS
      assert( addr>=0 && addr<size );
#endif
      parent.array[addr] = data;
    };

  private:
    mem<T,size,TLM> &parent;
    friend class mem<T,size,TLM>;
  };

public:
  template <class T, unsigned int size>
  class port_0_port<T,size,TLM>
  {
    enum {
      addr_width = nbits<size-1>::val,
      signedtype = mc_typedef_T_traits<T>::issigned,
      data_width = mc_typedef_T_traits<T>::bitwidth
    };
    p2p_checker reset_chk;

  public:
    port_0_port(const char *name = "unnamed_")
      : reset_chk(name, "call reset()", "access this port")
      , chan_ptr(0)
      , port_ptr(0)
      {}

    T read(unsigned int addr) {
      reset_chk.test();
      if ( bound_to_port )
        return port_ptr->read(addr);
      else
        return chan_ptr->read(addr);
    }

    const T &operator [] (int index) {
      reset_chk.test();
      return (bound_to_port? (*port_ptr)[index] : (*chan_ptr)[index]);
    }

    void reset() {reset_chk.ok();}

    void operator() (port_0_local<T,size,TLM> &c) {
      chan_ptr = &c;
      c.reset(); // Supress reset error on bound memory
      bound_to_port = false;
    }

    void operator() (port_0_port<T,size,TLM> &c) {
      port_ptr = &c;
      c.reset(); // Supress reset error on bound port
      bound_to_port = true;
    }

    void operator() (mem<T,size,TLM> &m) {
      chan_ptr = &m.port_0_port_instance;
      chan_ptr->reset(); // Supress reset error on bound memory
      bound_to_port = false;
    }

  private:
    bool bound_to_port;
    port_0_local<T,size,TLM> *chan_ptr;
    port_0_port<T,size,TLM> *port_ptr;
  };

  template <class T, unsigned int size>
  class port_1_port<T,size,TLM>
  {
    enum {
      addr_width = nbits<size-1>::val,
      signedtype = mc_typedef_T_traits<T>::issigned,
      data_width = mc_typedef_T_traits<T>::bitwidth
    };
    p2p_checker reset_chk;

  public:
    port_1_port(const char *name = "unnamed_")
      : reset_chk(name, "call reset()", "access this port")
      , chan_ptr(0)
      , port_ptr(0)
      {}

    void write(unsigned int addr, T data ) {
      reset_chk.test();
      if ( bound_to_port )
        port_ptr->write(addr,data);
      else
        chan_ptr->write(addr,data);
    }

    T &operator [] (int index) {
      reset_chk.test();
      return (bound_to_port? (*port_ptr)[index] : (*chan_ptr)[index]);
    }

    void reset() {reset_chk.ok();}

    void operator() (port_1_local<T,size,TLM> &c) {
      chan_ptr = &c;
      c.reset(); // Supress reset error on bound memory
      bound_to_port = false;
    }

    void operator() (port_1_port<T,size,TLM> &c) {
      port_ptr = &c;
      c.reset(); // Supress reset error on bound port
      bound_to_port = true;
    }

    void operator() (mem<T,size,TLM> &m) {
      chan_ptr = &m.port_1_port_instance;
      chan_ptr->reset(); // Supress reset error on bound memory
      bound_to_port = false;
    }

  private:
    bool bound_to_port;
    port_1_local<T,size,TLM> *chan_ptr;
    port_1_port<T,size,TLM> *port_ptr;
  };

  // ***********************************************
  // SYN SYN SYN SYN SYN SYN SYN SYN SYN SYN SYN SYN
  // Synthesis code
  // ***********************************************

private:
  template <class T, unsigned int size>
  class port_0_local<T,size,SYN>
  {
    enum {
      addr_width = nbits<size-1>::val,
      signedtype = mc_typedef_T_traits<T>::issigned,
      data_width = mc_typedef_T_traits<T>::bitwidth
    };
    p2p_checker reset_chk;
    p2p_checker clock_chk;
    class mem_ref
    {
    public:
      mem_ref( port_0_local<T,size,SYN> &my_parent, ac_int<addr_width,false> addr)
      : address(addr), parent(my_parent) {}

      operator T() const { return parent.read(address); }

      inline mem_ref operator = ( const mem_ref &val ) { return operator = ((T)val); }

    private:
      ac_int<addr_width,false> address;
      port_0_local<T,size,SYN> &parent;
    };

  public:
    void clock_ok() {clock_chk.ok();}

    port_0_local( const char *name = "unnamed_")
      : reset_chk( name, "call reset()", "access this memory")
      , clock_chk( name, "bind the clock port", "access this memory")
      , qout(ccs_concat(name,"qout"))
      , r_adr(ccs_concat(name,"r_adr"))
      {}

    #pragma mio_delay 0.1
    #pragma remove_out_reg
    #pragma design modulario
    T read (ac_int<addr_width,false> addr) {
      reset_chk.test();
      clock_chk.test();
      sc_lv<addr_width> temp_addr;
      type_to_vector(addr, (signedtype?true:false), temp_addr);
      r_adr.write( temp_addr );
      #pragma unroll
      for (int lcnt=0; lcnt<1; lcnt++) wait();
#if defined(CALYPTO_SC)
      wait(); // Account for unreg outputs for SLEC
#elif !defined(__SYNTHESIS__)
      wait(0.3, SC_NS);  // Account for unreg outputs in simulation
#endif
#if !defined(CALYPTO_SC)
      // Return outputs to don't care to save area
      sc_lv<data_width> dc;
      r_adr.write( dc );
#endif
      T return_data;
      vector_to_type(qout.read(), (signedtype?true:false), &return_data);
      return return_data;
    }

    mem_ref operator [] (int index) {
      mem_ref write_ref(*this, index);
      return write_ref;
    }

    void reset() {
      r_adr.write(sc_dt::Log_0);
      reset_chk.ok();
    }

    sc_signal< sc_lv<data_width> > qout;
    sc_signal< sc_lv<addr_width> > r_adr;
  private:
    friend class mem<T,size,SYN>;
  };

  template <class T, unsigned int size>
  class port_1_local<T,size,SYN>
  {
    enum {
      addr_width = nbits<size-1>::val,
      signedtype = mc_typedef_T_traits<T>::issigned,
      data_width = mc_typedef_T_traits<T>::bitwidth
    };
    p2p_checker reset_chk;
    p2p_checker clock_chk;
    class mem_ref
    {
    public:
      mem_ref( port_1_local<T,size,SYN> &my_parent, ac_int<addr_width,false> addr)
      : address(addr), parent(my_parent) {}

      inline mem_ref operator = ( T val ) {
        parent.write(address,val);
        return *this;
      }

      inline mem_ref operator = ( const mem_ref &val ) { return operator = ((T)val); }

    private:
      ac_int<addr_width,false> address;
      port_1_local<T,size,SYN> &parent;
    };

  public:
    void clock_ok() {clock_chk.ok();}

    port_1_local( const char *name = "unnamed_")
      : reset_chk( name, "call reset()", "access this memory")
      , clock_chk( name, "bind the clock port", "access this memory")
      , din(ccs_concat(name,"din"))
      , w_adr(ccs_concat(name,"w_adr"))
      , w_en(ccs_concat(name,"w_en"))
      {}

    #pragma remove_out_reg
    #pragma design modulario
    void write (ac_int<addr_width,false> addr, T data=0) {
      reset_chk.test();
      clock_chk.test();
      sc_lv<data_width> temp_data;
      type_to_vector(data, (signedtype?true:false), temp_data);
      sc_lv<addr_width> temp_addr;
      type_to_vector(addr, (signedtype?true:false), temp_addr);
      w_en.write(1);
      w_adr.write( temp_addr );
      din.write( temp_data );
      #pragma unroll
      for (int lcnt=0; lcnt<1; lcnt++) wait();
#if defined(CALYPTO_SC)
      wait(); // Account for unreg outputs for SLEC
#elif !defined(__SYNTHESIS__)
      wait(0.3, SC_NS);  // Account for unreg outputs in simulation
#endif
      w_en.write(0);
#if !defined(CALYPTO_SC)
      // Return outputs to don't care to save area
      sc_lv<data_width> dc;
      din.write( dc );
      w_adr.write( dc );
#endif
    }

    mem_ref operator [] (int index) {
      mem_ref write_ref(*this, index);
      return write_ref;
    }

    void reset() {
      w_en.write(0);
      w_adr.write(sc_dt::Log_0);
      din.write(sc_dt::Log_0);
      reset_chk.ok();
    }

    sc_signal< sc_lv<data_width> > din;
    sc_signal< sc_lv<addr_width> > w_adr;
    sc_signal< bool > w_en;
  private:
    friend class mem<T,size,SYN>;
  };

public:
  template <class T, unsigned int size>
  class mem <T,size,SYN>
  {
    enum {
      addr_width = nbits<size-1>::val,
      signedtype = mc_typedef_T_traits<T>::issigned,
      data_width = mc_typedef_T_traits<T>::bitwidth
    };
    class mem_ref
    {
    public:
      mem_ref( mem<T,size,SYN> &my_parent, ac_int<addr_width,false> addr)
      : address(addr), parent(my_parent) {}

      operator T() const { return parent.read(address); }

      inline mem_ref operator = ( T val ) {
        parent.write(address,val);
        return *this;
      }

      inline mem_ref operator = ( const mem_ref &val ) { return operator = ((T)val); }

    private:
      ac_int<addr_width,false> address;
      mem<T,size,SYN> &parent;
    };

  public:
    mem ( const char *name = "unnamed_") :
      port_0_port_instance(ccs_concat(name,"port_0")),
      port_1_port_instance(ccs_concat(name,"port_1")),
      RAM(ccs_concat(name, "RAM"))
    {
      RAM.qout(port_0_port_instance.qout);
      RAM.r_adr(port_0_port_instance.r_adr);
      RAM.din(port_1_port_instance.din);
      RAM.w_adr(port_1_port_instance.w_adr);
      RAM.w_en(port_1_port_instance.w_en);
    }

    port_0_local<T,size,SYN> port_0_port_instance;
    port_1_local<T,size,SYN> port_1_port_instance;

    void clk(sc_in<bool> &clk_arg) {
      RAM.clk(clk_arg);
      port_0_port_instance.clock_ok();
      port_1_port_instance.clock_ok();
    }
    #ifdef VCS_SYSTEMC
    // Bind may fail due to custom sc_writer_policy::SNPS_SC_WRITER_POLICY
    //  Force the one writer policy used with sc_clock
    void clk(sc_signal<bool,sc_core::SC_ONE_WRITER> &clk_arg)
    #else
    void clk(sc_signal<bool> &clk_arg)
    #endif
    {
      RAM.clk(clk_arg);
      port_0_port_instance.clock_ok();
      port_1_port_instance.clock_ok();
    }

    void clk_en(sc_in<bool> &clk_en_arg) {
      RAM.clk_en(clk_en_arg);
    }
    #ifdef VCS_SYSTEMC
    // Bind may fail due to custom sc_writer_policy::SNPS_SC_WRITER_POLICY
    //  Force the one writer policy used with sc_clock
    void clk_en(sc_signal<bool,sc_core::SC_ONE_WRITER> &clk_en_arg)
    #else
    void clk_en(sc_signal<bool> &clk_en_arg)
    #endif
    {
      RAM.clk_en(clk_en_arg);
    }


    T read ( ac_int<addr_width,false> addr ) {
      return port_0_port_instance.read( addr );
    }

    void write (ac_int<addr_width,false> addr, T data=0) {
      port_1_port_instance.write( addr, data );
    }

    mem_ref operator [] (int index) {
      mem_ref write_ref(*this, index);
      return write_ref;
    }

    void reset_read() {
      port_0_port_instance.reset();
    }

    void reset_write() {
      port_1_port_instance.reset();
    }

    // NOTE: this method is intended for use by testbenches only. It is not synthesizable!
    T tb_read(int address) const {
#ifndef NO_ASSERTS
      assert( address>=0 && address<size );
#endif
      T return_data;
      vector_to_type( RAM.tb_read(address) , (signedtype?true:false), &return_data);
      return return_data;
    }

    // NOTE: this method is intended for use by testbenches only. It is not synthesizable!
    void tb_write( int address, T val) {
#ifndef NO_ASSERTS
      assert( address>=0 && address<size );
#endif
      sc_lv<data_width> temp_data;
      type_to_vector(val, (signedtype?true:false), temp_data);
      RAM.tb_write(address, temp_data);
    }

  private:
    DUAL_PORT_RBW<0, addr_width, data_width, size> RAM;
  };

  template <class T, unsigned int size>
  class port_0_port<T,size,SYN>
  {
    enum {
      addr_width = nbits<size-1>::val,
      signedtype = mc_typedef_T_traits<T>::issigned,
      data_width = mc_typedef_T_traits<T>::bitwidth
    };
    p2p_checker reset_chk;

    class mem_ref
    {
    public:
      mem_ref( port_0_port<T,size,SYN> &my_parent, ac_int<addr_width,false> addr)
      : address(addr), parent(my_parent) {}

      operator T() const { return parent.read(address); }

      inline mem_ref operator = ( const mem_ref &val ) { return operator = ((T)val); }

    private:
      ac_int<addr_width,false> address;
      port_0_port<T,size,SYN> &parent;
    };

  public:
    port_0_port( const char *name = "unnamed_")
      : reset_chk( name, "call reset()", "access this memory")
      , qout(ccs_concat(name,"qout"))
      , r_adr(ccs_concat(name,"r_adr"))
      {}

    #pragma mio_delay 0.1
    #pragma remove_out_reg
    #pragma design modulario
    T read (ac_int<addr_width,false> addr) {
      reset_chk.test();
      sc_lv<addr_width> temp_addr;
      type_to_vector(addr, (signedtype?true:false), temp_addr);
      r_adr.write( temp_addr );
      #pragma unroll
      for (int lcnt=0; lcnt<1; lcnt++) wait();
#if defined(CALYPTO_SC)
      wait(); // Account for unreg outputs for SLEC
#elif !defined(__SYNTHESIS__)
      wait(0.3, SC_NS);  // Account for unreg outputs in simulation
#endif
#if !defined(CALYPTO_SC)
      // Return outputs to don't care to save area
      sc_lv<data_width> dc;
      r_adr.write( dc );
#endif
      T return_data;
      vector_to_type(qout.read(), (signedtype?true:false), &return_data);
      return return_data;
    }

    void reset() {
      r_adr.write(sc_dt::Log_0);
      reset_chk.ok();
    }

    sc_in< sc_lv<data_width> > qout;
    sc_out< sc_lv<addr_width> > r_adr;

    mem_ref operator [] (int index) {
      mem_ref write_ref(*this, index);
      return write_ref;
    }

    template <class C> void bind( C &c ) {
      qout(c.qout);
      r_adr(c.r_adr);
    }

    template <class C> void operator() (C& c) {
      bind(c);
    }

    void operator() (mem<T,size,SYN> &m) {
      qout(m.port_0_port_instance.qout);
      r_adr(m.port_0_port_instance.r_adr);
    }

  };


  template <class T, unsigned int size>
  class port_1_port<T,size,SYN>
  {
    enum {
      addr_width = nbits<size-1>::val,
      signedtype = mc_typedef_T_traits<T>::issigned,
      data_width = mc_typedef_T_traits<T>::bitwidth
    };
    p2p_checker reset_chk;

    class mem_ref
    {
    public:
      mem_ref( port_1_port<T,size,SYN> &my_parent, ac_int<addr_width,false> addr)
      : address(addr), parent(my_parent) {}

      inline mem_ref operator = ( T val ) {
        parent.write(address,val);
        return *this;
      }

      inline mem_ref operator = ( const mem_ref &val ) { return operator = ((T)val); }

    private:
      ac_int<addr_width,false> address;
      port_1_port<T,size,SYN> &parent;
    };

  public:
    port_1_port( const char *name = "unnamed_")
      : reset_chk( name, "call reset()", "access this memory")
      , din(ccs_concat(name,"din"))
      , w_adr(ccs_concat(name,"w_adr"))
      , w_en(ccs_concat(name,"w_en"))
      {}

    #pragma remove_out_reg
    #pragma design modulario
    void write (ac_int<addr_width,false> addr, T data=0) {
      reset_chk.test();
      sc_lv<data_width> temp_data;
      type_to_vector(data, (signedtype?true:false), temp_data);
      sc_lv<addr_width> temp_addr;
      type_to_vector(addr, (signedtype?true:false), temp_addr);
      w_en.write(1);
      w_adr.write( temp_addr );
      din.write( temp_data );
      #pragma unroll
      for (int lcnt=0; lcnt<1; lcnt++) wait();
#if defined(CALYPTO_SC)
      wait(); // Account for unreg outputs for SLEC
#elif !defined(__SYNTHESIS__)
      wait(0.3, SC_NS);  // Account for unreg outputs in simulation
#endif
      w_en.write(0);
#if !defined(CALYPTO_SC)
      // Return outputs to don't care to save area
      sc_lv<data_width> dc;
      din.write( dc );
      w_adr.write( dc );
#endif
    }

    void reset() {
      w_en.write(0);
      w_adr.write(sc_dt::Log_0);
      din.write(sc_dt::Log_0);
      reset_chk.ok();
    }

    sc_out< sc_lv<data_width> > din;
    sc_out< sc_lv<addr_width> > w_adr;
    sc_out< bool > w_en;

    mem_ref operator [] (int index) {
      mem_ref write_ref(*this, index);
      return write_ref;
    }

    template <class C> void bind( C &c ) {
      din(c.din);
      w_adr(c.w_adr);
      w_en(c.w_en);
    }

    template <class C> void operator() (C& c) {
      bind(c);
    }

    void operator() (mem<T,size,SYN> &m) {
      din(m.port_1_port_instance.din);
      w_adr(m.port_1_port_instance.w_adr);
      w_en(m.port_1_port_instance.w_en);
    }

  };

};
#endif // ifndef __INCLUDED_DUAL_PORT_RBW_H__


