# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_auto_pc_0/zynqmpsoc_auto_pc_0.xci
# IP: The module: 'zynqmpsoc_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_auto_pc_0/zynqmpsoc_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqmpsoc_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_auto_pc_0/zynqmpsoc_auto_pc_0.xci
# IP: The module: 'zynqmpsoc_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_auto_pc_0/zynqmpsoc_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqmpsoc_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
