// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2024.2/1130128 Production Release
//       HLS date: Mon Aug 26 21:59:12 PDT 2024
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: gtombesi@corsica
// Generated date: Wed Apr 30 13:18:35 EDT 2025
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model DataPath
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Constructor: sysc_sim_wrapper

CCS_RTL::sysc_sim_wrapper::sysc_sim_wrapper(
   const sc_module_name& nm
)
   : ccs_rtl(
      "ccs_rtl",
      "ccs_wrapper"
   )
   , clk("clk")
   , rst("rst")
   , conf_info_in("conf_info_in")
   , sync00("sync00")
   , in_wr_req("in_wr_req")
   , in_rd_rsp("in_rd_rsp")
   , ccs_rtl_SIG_clk("ccs_rtl_SIG_clk")
   , ccs_rtl_SIG_rst("ccs_rtl_SIG_rst")
   , ccs_rtl_SIG_conf_info_in_val("ccs_rtl_SIG_conf_info_in_val")
   , ccs_rtl_SIG_conf_info_in_rdy("ccs_rtl_SIG_conf_info_in_rdy")
   , ccs_rtl_SIG_conf_info_in_msg("ccs_rtl_SIG_conf_info_in_msg")
   , ccs_rtl_SIG_sync00_val("ccs_rtl_SIG_sync00_val")
   , ccs_rtl_SIG_sync00_rdy("ccs_rtl_SIG_sync00_rdy")
   , ccs_rtl_SIG_sync00_msg("ccs_rtl_SIG_sync00_msg")
   , ccs_rtl_SIG_in_wr_req_val("ccs_rtl_SIG_in_wr_req_val")
   , ccs_rtl_SIG_in_wr_req_rdy("ccs_rtl_SIG_in_wr_req_rdy")
   , ccs_rtl_SIG_in_wr_req_msg("ccs_rtl_SIG_in_wr_req_msg")
   , ccs_rtl_SIG_in_rd_rsp_val("ccs_rtl_SIG_in_rd_rsp_val")
   , ccs_rtl_SIG_in_rd_rsp_rdy("ccs_rtl_SIG_in_rd_rsp_rdy")
   , ccs_rtl_SIG_in_rd_rsp_msg("ccs_rtl_SIG_in_rd_rsp_msg")
{
   // Instantiate other modules
   ccs_rtl.clk(ccs_rtl_SIG_clk);
   ccs_rtl.rst(ccs_rtl_SIG_rst);
   ccs_rtl.conf_info_in_val(ccs_rtl_SIG_conf_info_in_val);
   ccs_rtl.conf_info_in_rdy(ccs_rtl_SIG_conf_info_in_rdy);
   ccs_rtl.conf_info_in_msg(ccs_rtl_SIG_conf_info_in_msg);
   ccs_rtl.sync00_val(ccs_rtl_SIG_sync00_val);
   ccs_rtl.sync00_rdy(ccs_rtl_SIG_sync00_rdy);
   ccs_rtl.sync00_msg(ccs_rtl_SIG_sync00_msg);
   ccs_rtl.in_wr_req_val(ccs_rtl_SIG_in_wr_req_val);
   ccs_rtl.in_wr_req_rdy(ccs_rtl_SIG_in_wr_req_rdy);
   ccs_rtl.in_wr_req_msg(ccs_rtl_SIG_in_wr_req_msg);
   ccs_rtl.in_rd_rsp_val(ccs_rtl_SIG_in_rd_rsp_val);
   ccs_rtl.in_rd_rsp_rdy(ccs_rtl_SIG_in_rd_rsp_rdy);
   ccs_rtl.in_rd_rsp_msg(ccs_rtl_SIG_in_rd_rsp_msg);
   
   // Register processes
   SC_METHOD(update_proc);
   sensitive  << clk << rst << conf_info_in.Connections::InBlocking_Ports_abs<conf_info_t >::val << ccs_rtl_SIG_conf_info_in_rdy << conf_info_in.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg << sync00.Connections::InBlocking_Ports_abs<bool >::val << ccs_rtl_SIG_sync00_rdy << sync00.Connections::InBlocking<bool, Connections::SYN_PORT >::msg << ccs_rtl_SIG_in_wr_req_val << in_wr_req.Connections::OutBlocking_Ports_abs<ac_int<32, true > >::rdy << ccs_rtl_SIG_in_wr_req_msg << in_rd_rsp.Connections::InBlocking_Ports_abs<read_data >::val << ccs_rtl_SIG_in_rd_rsp_rdy << in_rd_rsp.Connections::InBlocking<read_data, Connections::SYN_PORT >::msg;
   // Other constructor statements
}

// ---------------------------------------------------------------
// Process: SC_METHOD update_proc

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   
   // none.sc_in field_key=clk:2711c999-a048-4ce1-9b75-0e315109631c-1236:clk:2711c999-a048-4ce1-9b75-0e315109631c-1236
   sc_logic t_2711c999_a048_4ce1_9b75_0e315109631c_1236; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:2711c999-a048-4ce1-9b75-0e315109631c-1237:rst:2711c999-a048-4ce1-9b75-0e315109631c-1237
   sc_logic t_2711c999_a048_4ce1_9b75_0e315109631c_1237; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_2711c999_a048_4ce1_9b75_0e315109631c_1237); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_2711c999_a048_4ce1_9b75_0e315109631c_1237); // then write to RTL port
   
   // none.sc_in field_key=conf_info_in:2711c999-a048-4ce1-9b75-0e315109631c-1238:val:2711c999-a048-4ce1-9b75-0e315109631c-1249
   sc_logic t_2711c999_a048_4ce1_9b75_0e315109631c_1249; // NPS - LV to hold field
   type_to_vector(conf_info_in.Connections::InBlocking_Ports_abs<conf_info_t >::val.read(),1,t_2711c999_a048_4ce1_9b75_0e315109631c_1249); // read orig port and type convert
   ccs_rtl_SIG_conf_info_in_val.write(t_2711c999_a048_4ce1_9b75_0e315109631c_1249); // then write to RTL port
   
   // none.sc_out field_key=conf_info_in:2711c999-a048-4ce1-9b75-0e315109631c-1238:rdy:2711c999-a048-4ce1-9b75-0e315109631c-1250
   sc_logic t_2711c999_a048_4ce1_9b75_0e315109631c_1250;
   bool d_2711c999_a048_4ce1_9b75_0e315109631c_1250;
   t_2711c999_a048_4ce1_9b75_0e315109631c_1250 = ccs_rtl_SIG_conf_info_in_rdy.read();
   vector_to_type(t_2711c999_a048_4ce1_9b75_0e315109631c_1250, 1, &d_2711c999_a048_4ce1_9b75_0e315109631c_1250);
   conf_info_in.Connections::InBlocking_Ports_abs<conf_info_t >::rdy.write(d_2711c999_a048_4ce1_9b75_0e315109631c_1250);
   
   // none.sc_in field_key=conf_info_in:2711c999-a048-4ce1-9b75-0e315109631c-1238:msg:2711c999-a048-4ce1-9b75-0e315109631c-1251
   sc_lv< 96 > t_2711c999_a048_4ce1_9b75_0e315109631c_1251; // NPS - LV to hold field
   type_to_vector(conf_info_in.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg.read(),96,t_2711c999_a048_4ce1_9b75_0e315109631c_1251); // read orig port and type convert
   ccs_rtl_SIG_conf_info_in_msg.write(t_2711c999_a048_4ce1_9b75_0e315109631c_1251); // then write to RTL port
   
   // none.sc_in field_key=sync00:2711c999-a048-4ce1-9b75-0e315109631c-1252:val:2711c999-a048-4ce1-9b75-0e315109631c-1261
   sc_logic t_2711c999_a048_4ce1_9b75_0e315109631c_1261; // NPS - LV to hold field
   type_to_vector(sync00.Connections::InBlocking_Ports_abs<bool >::val.read(),1,t_2711c999_a048_4ce1_9b75_0e315109631c_1261); // read orig port and type convert
   ccs_rtl_SIG_sync00_val.write(t_2711c999_a048_4ce1_9b75_0e315109631c_1261); // then write to RTL port
   
   // none.sc_out field_key=sync00:2711c999-a048-4ce1-9b75-0e315109631c-1252:rdy:2711c999-a048-4ce1-9b75-0e315109631c-1262
   sc_logic t_2711c999_a048_4ce1_9b75_0e315109631c_1262;
   bool d_2711c999_a048_4ce1_9b75_0e315109631c_1262;
   t_2711c999_a048_4ce1_9b75_0e315109631c_1262 = ccs_rtl_SIG_sync00_rdy.read();
   vector_to_type(t_2711c999_a048_4ce1_9b75_0e315109631c_1262, 1, &d_2711c999_a048_4ce1_9b75_0e315109631c_1262);
   sync00.Connections::InBlocking_Ports_abs<bool >::rdy.write(d_2711c999_a048_4ce1_9b75_0e315109631c_1262);
   
   // none.sc_in field_key=sync00:2711c999-a048-4ce1-9b75-0e315109631c-1252:msg:2711c999-a048-4ce1-9b75-0e315109631c-1263
   sc_logic t_2711c999_a048_4ce1_9b75_0e315109631c_1263; // NPS - LV to hold field
   type_to_vector(sync00.Connections::InBlocking<bool, Connections::SYN_PORT >::msg.read(),1,t_2711c999_a048_4ce1_9b75_0e315109631c_1263); // read orig port and type convert
   ccs_rtl_SIG_sync00_msg.write(t_2711c999_a048_4ce1_9b75_0e315109631c_1263); // then write to RTL port
   
   // none.sc_out field_key=in_wr_req:2711c999-a048-4ce1-9b75-0e315109631c-1264:val:2711c999-a048-4ce1-9b75-0e315109631c-1273
   sc_logic t_2711c999_a048_4ce1_9b75_0e315109631c_1273;
   bool d_2711c999_a048_4ce1_9b75_0e315109631c_1273;
   t_2711c999_a048_4ce1_9b75_0e315109631c_1273 = ccs_rtl_SIG_in_wr_req_val.read();
   vector_to_type(t_2711c999_a048_4ce1_9b75_0e315109631c_1273, 1, &d_2711c999_a048_4ce1_9b75_0e315109631c_1273);
   in_wr_req.Connections::OutBlocking_Ports_abs<ac_int<32, true > >::val.write(d_2711c999_a048_4ce1_9b75_0e315109631c_1273);
   
   // none.sc_in field_key=in_wr_req:2711c999-a048-4ce1-9b75-0e315109631c-1264:rdy:2711c999-a048-4ce1-9b75-0e315109631c-1274
   sc_logic t_2711c999_a048_4ce1_9b75_0e315109631c_1274; // NPS - LV to hold field
   type_to_vector(in_wr_req.Connections::OutBlocking_Ports_abs<ac_int<32, true > >::rdy.read(),1,t_2711c999_a048_4ce1_9b75_0e315109631c_1274); // read orig port and type convert
   ccs_rtl_SIG_in_wr_req_rdy.write(t_2711c999_a048_4ce1_9b75_0e315109631c_1274); // then write to RTL port
   
   // none.sc_out field_key=in_wr_req:2711c999-a048-4ce1-9b75-0e315109631c-1264:msg:2711c999-a048-4ce1-9b75-0e315109631c-1275
   sc_lv< 32 > t_2711c999_a048_4ce1_9b75_0e315109631c_1275;
   sc_dt::sc_lv<32 > d_2711c999_a048_4ce1_9b75_0e315109631c_1275;
   t_2711c999_a048_4ce1_9b75_0e315109631c_1275 = ccs_rtl_SIG_in_wr_req_msg.read();
   vector_to_type(t_2711c999_a048_4ce1_9b75_0e315109631c_1275, 32, &d_2711c999_a048_4ce1_9b75_0e315109631c_1275);
   in_wr_req.Connections::OutBlocking<ac_int<32, true >, Connections::SYN_PORT >::msg.write(d_2711c999_a048_4ce1_9b75_0e315109631c_1275);
   
   // none.sc_in field_key=in_rd_rsp:2711c999-a048-4ce1-9b75-0e315109631c-1276:val:2711c999-a048-4ce1-9b75-0e315109631c-1285
   sc_logic t_2711c999_a048_4ce1_9b75_0e315109631c_1285; // NPS - LV to hold field
   type_to_vector(in_rd_rsp.Connections::InBlocking_Ports_abs<read_data >::val.read(),1,t_2711c999_a048_4ce1_9b75_0e315109631c_1285); // read orig port and type convert
   ccs_rtl_SIG_in_rd_rsp_val.write(t_2711c999_a048_4ce1_9b75_0e315109631c_1285); // then write to RTL port
   
   // none.sc_out field_key=in_rd_rsp:2711c999-a048-4ce1-9b75-0e315109631c-1276:rdy:2711c999-a048-4ce1-9b75-0e315109631c-1286
   sc_logic t_2711c999_a048_4ce1_9b75_0e315109631c_1286;
   bool d_2711c999_a048_4ce1_9b75_0e315109631c_1286;
   t_2711c999_a048_4ce1_9b75_0e315109631c_1286 = ccs_rtl_SIG_in_rd_rsp_rdy.read();
   vector_to_type(t_2711c999_a048_4ce1_9b75_0e315109631c_1286, 1, &d_2711c999_a048_4ce1_9b75_0e315109631c_1286);
   in_rd_rsp.Connections::InBlocking_Ports_abs<read_data >::rdy.write(d_2711c999_a048_4ce1_9b75_0e315109631c_1286);
   
   // none.sc_in field_key=in_rd_rsp:2711c999-a048-4ce1-9b75-0e315109631c-1276:msg:2711c999-a048-4ce1-9b75-0e315109631c-1287
   sc_lv< 64 > t_2711c999_a048_4ce1_9b75_0e315109631c_1287; // NPS - LV to hold field
   type_to_vector(in_rd_rsp.Connections::InBlocking<read_data, Connections::SYN_PORT >::msg.read(),64,t_2711c999_a048_4ce1_9b75_0e315109631c_1287); // read orig port and type convert
   ccs_rtl_SIG_in_rd_rsp_msg.write(t_2711c999_a048_4ce1_9b75_0e315109631c_1287); // then write to RTL port
}
