#!/bin/sh
mkdir -p /lib/modules/$(uname -r)
echo 8 > /proc/sys/kernel/printk
mount -t openpromfs none /proc/openprom

# start (per DDR node): contig_alloc starting address
# size (per DDR node): contig_alloc region size
# chunk_log: default accelerator page

# Default values:
#
#               #DDR0#
# 0x40000000 -> \----\
#               |    |
#               |    |
#               |    | -> reserved (software only)
#               |    |
#               |    |
# 0x5bffffff -> \    | <- 0x5bfffff0 -> Leon3 stack pointer
#               |    |
#               |    | -> shared (software and accellerators)
#               |    |
# 0x5fffffff -> \----\

#               #DDR1#
# 0x60000000 -> \----\
#               |    |
#               |    |
#               |    |
#               |    |
#               |    | -> shared (software and accellerators)
#               |    |
#               |    |
#               |    |
#               |    |
# 0x7fffffff -> \----\
#
# accelerator page: 2^20B -> 1MB

# Adjust below if necessary
cd /opt/drivers-esp
insmod contig_alloc.ko start=0x5c000000,0x60000000 size=0x4000000,0x20000000 chunk_log=20
insmod esp_cache.ko
insmod esp.ko

cd /opt/drivers
for K in `ls *.ko`; do
   insmod $K;
done

lsmod

