#!/bin/ash
#
# DropBear SSH

DSSKEY=/etc/dropbear/dropbear_dss_host_key
RSAKEY=/etc/dropbear/dropbear_rsa_host_key
PIDFILE=/var/run/dropbear.pid

test -d /etc/dropbear || exit 0

case "$1" in

start)
    if [ ! -r "$RSAKEY" ]; then
        echo "Generating RSA host key ... "
        dropbearconvert openssh dropbear /etc/dropbear/openssh_rsa_host_key "$RSAKEY"
    fi
    if [ -r "$PIDFILE" ]; then
        echo "Service dropbear already running."
    else
        echo "Starting SSH server ... "
        start-stop-daemon -S -x /sbin/dropbear -p "$PIDFILE"
    fi
    ;;

stop)
    echo "Stopping dropbear SSH server ... "
    start-stop-daemon -K -x /sbin/dropbear -p "$PIDFILE"
    ;;

restart)
    $0 stop
    $0 start
    ;;

status)
    if [ -r "$PIDFILE" ]; then
        echo "Service dropbear running (PID $(cat "$PIDFILE"))."
    else
        echo "Service dropbear not running."
    fi
    ;;

*)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1

esac
