set_property SRC_FILE_INFO {cfile:/home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg.xdc rfile:../../../../../../constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg.xdc id:1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-eth-constraints.xdc rfile:../../../../../../constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-eth-constraints.xdc id:2} [current_design]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports uart_txd]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports uart_rxd]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E12 [get_ports uart_rtsn]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D12 [get_ports uart_ctsn]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AG14 [get_ports {led[0]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AF13 [get_ports {led[1]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AE13 [get_ports {led[2]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ14 [get_ports {led[3]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AJ15 [get_ports {led[4]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH13 [get_ports {led[5]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AH14 [get_ports {led[6]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN14 [get_ports {switch[0]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP14 [get_ports {switch[1]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM14 [get_ports {switch[2]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN13 [get_ports {switch[3]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN12 [get_ports {switch[4]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP12 [get_ports {switch[5]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL13 [get_ports {switch[6]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK13 [get_ports {switch[7]}]
set_property src_info {type:XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list zynqmpsoc_i/zynq_ultra_ps_e_0/inst/pl_clk0]]
set_property src_info {type:XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {mi_hrdata[0]} {mi_hrdata[1]} {mi_hrdata[2]} {mi_hrdata[3]} {mi_hrdata[4]} {mi_hrdata[5]} {mi_hrdata[6]} {mi_hrdata[7]} {mi_hrdata[8]} {mi_hrdata[9]} {mi_hrdata[10]} {mi_hrdata[11]} {mi_hrdata[12]} {mi_hrdata[13]} {mi_hrdata[14]} {mi_hrdata[15]} {mi_hrdata[16]} {mi_hrdata[17]} {mi_hrdata[18]} {mi_hrdata[19]} {mi_hrdata[20]} {mi_hrdata[21]} {mi_hrdata[22]} {mi_hrdata[23]} {mi_hrdata[24]} {mi_hrdata[25]} {mi_hrdata[26]} {mi_hrdata[27]} {mi_hrdata[28]} {mi_hrdata[29]} {mi_hrdata[30]} {mi_hrdata[31]}]]
set_property src_info {type:XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {mo_htrans[0]} {mo_htrans[1]}]]
set_property src_info {type:XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {mo_haddr[0]} {mo_haddr[1]} {mo_haddr[2]} {mo_haddr[3]} {mo_haddr[4]} {mo_haddr[5]} {mo_haddr[6]} {mo_haddr[7]} {mo_haddr[8]} {mo_haddr[9]} {mo_haddr[10]} {mo_haddr[11]} {mo_haddr[12]} {mo_haddr[13]} {mo_haddr[14]} {mo_haddr[15]} {mo_haddr[16]} {mo_haddr[17]} {mo_haddr[18]} {mo_haddr[19]} {mo_haddr[20]} {mo_haddr[21]} {mo_haddr[22]} {mo_haddr[23]} {mo_haddr[24]} {mo_haddr[25]} {mo_haddr[26]} {mo_haddr[27]} {mo_haddr[28]} {mo_haddr[29]} {mo_haddr[30]} {mo_haddr[31]}]]
set_property src_info {type:XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {mo_hwdata[0]} {mo_hwdata[1]} {mo_hwdata[2]} {mo_hwdata[3]} {mo_hwdata[4]} {mo_hwdata[5]} {mo_hwdata[6]} {mo_hwdata[7]} {mo_hwdata[8]} {mo_hwdata[9]} {mo_hwdata[10]} {mo_hwdata[11]} {mo_hwdata[12]} {mo_hwdata[13]} {mo_hwdata[14]} {mo_hwdata[15]} {mo_hwdata[16]} {mo_hwdata[17]} {mo_hwdata[18]} {mo_hwdata[19]} {mo_hwdata[20]} {mo_hwdata[21]} {mo_hwdata[22]} {mo_hwdata[23]} {mo_hwdata[24]} {mo_hwdata[25]} {mo_hwdata[26]} {mo_hwdata[27]} {mo_hwdata[28]} {mo_hwdata[29]} {mo_hwdata[30]} {mo_hwdata[31]}]]
set_property src_info {type:XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {si_haddr[0]} {si_haddr[1]} {si_haddr[2]} {si_haddr[3]} {si_haddr[4]} {si_haddr[5]} {si_haddr[6]} {si_haddr[7]} {si_haddr[8]} {si_haddr[9]} {si_haddr[10]} {si_haddr[11]} {si_haddr[12]} {si_haddr[13]} {si_haddr[14]} {si_haddr[15]} {si_haddr[16]} {si_haddr[17]} {si_haddr[18]} {si_haddr[19]} {si_haddr[20]} {si_haddr[21]} {si_haddr[22]} {si_haddr[23]} {si_haddr[24]} {si_haddr[25]} {si_haddr[26]} {si_haddr[27]} {si_haddr[28]} {si_haddr[29]} {si_haddr[30]} {si_haddr[31]}]]
set_property src_info {type:XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {si_hprot[0]} {si_hprot[1]} {si_hprot[2]} {si_hprot[3]}]]
set_property src_info {type:XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {si_htrans[0]} {si_htrans[1]}]]
set_property src_info {type:XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {si_hwdata[0]} {si_hwdata[1]} {si_hwdata[2]} {si_hwdata[3]} {si_hwdata[4]} {si_hwdata[5]} {si_hwdata[6]} {si_hwdata[7]} {si_hwdata[8]} {si_hwdata[9]} {si_hwdata[10]} {si_hwdata[11]} {si_hwdata[12]} {si_hwdata[13]} {si_hwdata[14]} {si_hwdata[15]} {si_hwdata[16]} {si_hwdata[17]} {si_hwdata[18]} {si_hwdata[19]} {si_hwdata[20]} {si_hwdata[21]} {si_hwdata[22]} {si_hwdata[23]} {si_hwdata[24]} {si_hwdata[25]} {si_hwdata[26]} {si_hwdata[27]} {si_hwdata[28]} {si_hwdata[29]} {si_hwdata[30]} {si_hwdata[31]} {si_hwdata[32]} {si_hwdata[33]} {si_hwdata[34]} {si_hwdata[35]} {si_hwdata[36]} {si_hwdata[37]} {si_hwdata[38]} {si_hwdata[39]} {si_hwdata[40]} {si_hwdata[41]} {si_hwdata[42]} {si_hwdata[43]} {si_hwdata[44]} {si_hwdata[45]} {si_hwdata[46]} {si_hwdata[47]} {si_hwdata[48]} {si_hwdata[49]} {si_hwdata[50]} {si_hwdata[51]} {si_hwdata[52]} {si_hwdata[53]} {si_hwdata[54]} {si_hwdata[55]} {si_hwdata[56]} {si_hwdata[57]} {si_hwdata[58]} {si_hwdata[59]} {si_hwdata[60]} {si_hwdata[61]} {si_hwdata[62]} {si_hwdata[63]}]]
set_property src_info {type:XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 64 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {so_hrdata[0]} {so_hrdata[1]} {so_hrdata[2]} {so_hrdata[3]} {so_hrdata[4]} {so_hrdata[5]} {so_hrdata[6]} {so_hrdata[7]} {so_hrdata[8]} {so_hrdata[9]} {so_hrdata[10]} {so_hrdata[11]} {so_hrdata[12]} {so_hrdata[13]} {so_hrdata[14]} {so_hrdata[15]} {so_hrdata[16]} {so_hrdata[17]} {so_hrdata[18]} {so_hrdata[19]} {so_hrdata[20]} {so_hrdata[21]} {so_hrdata[22]} {so_hrdata[23]} {so_hrdata[24]} {so_hrdata[25]} {so_hrdata[26]} {so_hrdata[27]} {so_hrdata[28]} {so_hrdata[29]} {so_hrdata[30]} {so_hrdata[31]} {so_hrdata[32]} {so_hrdata[33]} {so_hrdata[34]} {so_hrdata[35]} {so_hrdata[36]} {so_hrdata[37]} {so_hrdata[38]} {so_hrdata[39]} {so_hrdata[40]} {so_hrdata[41]} {so_hrdata[42]} {so_hrdata[43]} {so_hrdata[44]} {so_hrdata[45]} {so_hrdata[46]} {so_hrdata[47]} {so_hrdata[48]} {so_hrdata[49]} {so_hrdata[50]} {so_hrdata[51]} {so_hrdata[52]} {so_hrdata[53]} {so_hrdata[54]} {so_hrdata[55]} {so_hrdata[56]} {so_hrdata[57]} {so_hrdata[58]} {so_hrdata[59]} {so_hrdata[60]} {so_hrdata[61]} {so_hrdata[62]} {so_hrdata[63]}]]
set_property src_info {type:XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list mi_hready]]
set_property src_info {type:XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list mo_hwrite]]
set_property src_info {type:XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list si_hready]]
set_property src_info {type:XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list si_hwrite]]
set_property src_info {type:XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list so_hready]]
set_property src_info {type:XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets chip_refclk]
