#ifndef CONFIG_FTSDCTRL
#define CONFIG_FTSDCTRL 0
#endif

#ifndef CONFIG_FTSDCTRL_INVCLK
#define CONFIG_FTSDCTRL_INVCLK 0
#endif

#ifndef CONFIG_FTSDCTRL_EDAC
#define CONFIG_FTSDCTRL_EDAC 0
#endif

#ifndef CONFIG_FTSDCTRL_EDAC_RS
#define CONFIG_FTSDCTRL_EDAC_RS 0
#endif

#ifndef CONFIG_FTSDCTRL_PAGE
#define CONFIG_FTSDCTRL_PAGE 0
#endif

#ifndef CONFIG_FTSDCTRL_PROGPAGE
#define CONFIG_FTSDCTRL_PROGPAGE 0
#endif

