#ifndef CONFIG_SRCTRLFT
#define CONFIG_SRCTRLFT 0
#endif

#ifndef CONFIG_SRCTRLFT_APBEN
#define CONFIG_SRCTRLFT_APBEN 0
#endif

#ifndef CONFIG_SRCTRLFT_PROMWS
#define CONFIG_SRCTRLFT_PROMWS 0
#endif

#ifndef CONFIG_SRCTRLFT_RAMWS
#define CONFIG_SRCTRLFT_RAMWS 0
#endif

#ifndef CONFIG_SRCTRLFT_IOWS
#define CONFIG_SRCTRLFT_IOWS 0
#endif

#ifndef CONFIG_SRCTRLFT_RMW
#define CONFIG_SRCTRLFT_RMW 0
#endif

#ifndef CONFIG_SRCTRLFT_EDAC
#define CONFIG_SRCTRLFT_EDAC 0
#endif

#ifndef CONFIG_SRCTRLFT_8BIT
#define CONFIG_SRCTRLFT_8BIT 0
#endif

#if defined CONFIG_SRCTRLFT_SRBANKS1
#define CFG_SR_CTRLFT_SRBANKS 1
#elif defined CONFIG_SRCTRLFT_SRBANKS2
#define CFG_SR_CTRLFT_SRBANKS 2
#elif defined CONFIG_SRCTRLFT_SRBANKS3
#define CFG_SR_CTRLFT_SRBANKS 3
#elif defined CONFIG_SRCTRLFT_SRBANKS4
#define CFG_SR_CTRLFT_SRBANKS 4
#elif defined CONFIG_SRCTRLFT_SRBANKS5
#define CFG_SR_CTRLFT_SRBANKS 5
#elif defined CONFIG_SRCTRLFT_SRBANKS6
#define CFG_SR_CTRLFT_SRBANKS 6
#elif defined CONFIG_SRCTRLFT_SRBANKS7
#define CFG_SR_CTRLFT_SRBANKS 7
#elif defined CONFIG_SRCTRLFT_SRBANKS8
#define CFG_SR_CTRLFT_SRBANKS 8
#else
#define CFG_SR_CTRLFT_SRBANKS 1
#endif

#if defined CONFIG_SRCTRLFT_BANKSZ0
#define CFG_SR_CTRLFT_BANKSZ 0
#elif defined CONFIG_SRCTRLFT_BANKSZ1
#define CFG_SR_CTRLFT_BANKSZ 1
#elif defined CONFIG_SRCTRLFT_BANKSZ2
#define CFG_SR_CTRLFT_BANKSZ 2
#elif defined CONFIG_SRCTRLFT_BANKSZ3
#define CFG_SR_CTRLFT_BANKSZ 3
#elif defined CONFIG_SRCTRLFT_BANKSZ4
#define CFG_SR_CTRLFT_BANKSZ 4
#elif defined CONFIG_SRCTRLFT_BANKSZ5
#define CFG_SR_CTRLFT_BANKSZ 5
#elif defined CONFIG_SRCTRLFT_BANKSZ6
#define CFG_SR_CTRLFT_BANKSZ 6
#elif defined CONFIG_SRCTRLFT_BANKSZ7
#define CFG_SR_CTRLFT_BANKSZ 7
#elif defined CONFIG_SRCTRLFT_BANKSZ8
#define CFG_SR_CTRLFT_BANKSZ 8
#elif defined CONFIG_SRCTRLFT_BANKSZ9
#define CFG_SR_CTRLFT_BANKSZ 9
#elif defined CONFIG_SRCTRLFT_BANKSZ10
#define CFG_SR_CTRLFT_BANKSZ 10
#elif defined CONFIG_SRCTRLFT_BANKSZ11
#define CFG_SR_CTRLFT_BANKSZ 11
#elif defined CONFIG_SRCTRLFT_BANKSZ12
#define CFG_SR_CTRLFT_BANKSZ 12
#elif defined CONFIG_SRCTRLFT_BANKSZ13
#define CFG_SR_CTRLFT_BANKSZ 13
#elif defined CONFIG_SRCTRLFT_BANKSZ14
#define CFG_SR_CTRLFT_BANKSZ 14
#elif defined CONFIG_SRCTRLFT_BANKSZ15
#define CFG_SR_CTRLFT_BANKSZ 15
#else
#define CFG_SR_CTRLFT_BANKSZ 0
#endif

#if defined CONFIG_SRCTRLFT_ROMBANKS1
#define CFG_SR_CTRLFT_ROMBANKS 1
#elif defined CONFIG_SRCTRLFT_ROMBANKS2
#define CFG_SR_CTRLFT_ROMBANKS 2
#elif defined CONFIG_SRCTRLFT_ROMBANKS3
#define CFG_SR_CTRLFT_ROMBANKS 3
#elif defined CONFIG_SRCTRLFT_ROMBANKS4
#define CFG_SR_CTRLFT_ROMBANKS 4
#elif defined CONFIG_SRCTRLFT_ROMBANKS5
#define CFG_SR_CTRLFT_ROMBANKS 5
#elif defined CONFIG_SRCTRLFT_ROMBANKS6
#define CFG_SR_CTRLFT_ROMBANKS 6
#elif defined CONFIG_SRCTRLFT_ROMBANKS7
#define CFG_SR_CTRLFT_ROMBANKS 7
#elif defined CONFIG_SRCTRLFT_ROMBANKS8
#define CFG_SR_CTRLFT_ROMBANKS 8
#else
#define CFG_SR_CTRLFT_ROMBANKS 1
#endif

#if defined CONFIG_SRCTRLFT_ROMBANKSZ0
#define CFG_SR_CTRLFT_ROMBANKSZ 0
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ1
#define CFG_SR_CTRLFT_ROMBANKSZ 1
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ2
#define CFG_SR_CTRLFT_ROMBANKSZ 2
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ3
#define CFG_SR_CTRLFT_ROMBANKSZ 3
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ4
#define CFG_SR_CTRLFT_ROMBANKSZ 4
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ5
#define CFG_SR_CTRLFT_ROMBANKSZ 5
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ6
#define CFG_SR_CTRLFT_ROMBANKSZ 6
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ7
#define CFG_SR_CTRLFT_ROMBANKSZ 7
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ8
#define CFG_SR_CTRLFT_ROMBANKSZ 8
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ9
#define CFG_SR_CTRLFT_ROMBANKSZ 9
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ10
#define CFG_SR_CTRLFT_ROMBANKSZ 10
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ11
#define CFG_SR_CTRLFT_ROMBANKSZ 11
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ12
#define CFG_SR_CTRLFT_ROMBANKSZ 12
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ13
#define CFG_SR_CTRLFT_ROMBANKSZ 13
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ14
#define CFG_SR_CTRLFT_ROMBANKSZ 14
#elif defined CONFIG_SRCTRLFT_ROMBANKSZ15
#define CFG_SR_CTRLFT_ROMBANKSZ 15
#else
#define CFG_SR_CTRLFT_ROMBANKSZ 0
#endif

#if defined CONFIG_SRCTRLFT_ROMBANKSZDEF0
#define CFG_SR_CTRLFT_ROMBANKSZDEF 0
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF1
#define CFG_SR_CTRLFT_ROMBANKSZDEF 1
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF2
#define CFG_SR_CTRLFT_ROMBANKSZDEF 2
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF3
#define CFG_SR_CTRLFT_ROMBANKSZDEF 3
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF4
#define CFG_SR_CTRLFT_ROMBANKSZDEF 4
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF5
#define CFG_SR_CTRLFT_ROMBANKSZDEF 5
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF6
#define CFG_SR_CTRLFT_ROMBANKSZDEF 6
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF7
#define CFG_SR_CTRLFT_ROMBANKSZDEF 7
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF8
#define CFG_SR_CTRLFT_ROMBANKSZDEF 8
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF9
#define CFG_SR_CTRLFT_ROMBANKSZDEF 9
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF10
#define CFG_SR_CTRLFT_ROMBANKSZDEF 10
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF11
#define CFG_SR_CTRLFT_ROMBANKSZDEF 11
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF12
#define CFG_SR_CTRLFT_ROMBANKSZDEF 12
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF13
#define CFG_SR_CTRLFT_ROMBANKSZDEF 13
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF14
#define CFG_SR_CTRLFT_ROMBANKSZDEF 14
#elif defined CONFIG_SRCTRLFT_ROMBANKSZDEF15
#define CFG_SR_CTRLFT_ROMBANKSZDEF 15
#else
#define CFG_SR_CTRLFT_ROMBANKSZDEF 0
#endif

#ifndef CONFIG_SRCTRLFT_NETLIST
#define CONFIG_SRCTRLFT_NETLIST 0
#endif
