#ifndef CONFIG_GRGPIO2_ENABLE
#define CONFIG_GRGPIO2_ENABLE 0
#endif
#ifndef CONFIG_GRGPIO2_IMASK
#define CONFIG_GRGPIO2_IMASK 0000
#endif
#ifndef CONFIG_GRGPIO2_WIDTH
#define CONFIG_GRGPIO2_WIDTH 1
#endif

