#if defined CONFIG_GRPCI2_MASTER
#define CFG_GRPCI2_MASTEREN 1
#else
#define CFG_GRPCI2_MASTEREN 0
#endif

#if defined CONFIG_GRPCI2_TARGET
#define CFG_GRPCI2_TARGETEN 1
#else
#define CFG_GRPCI2_TARGETEN 0
#endif

#if defined CONFIG_GRPCI2_DMA
#define CFG_GRPCI2_DMAEN 1
#else
#define CFG_GRPCI2_DMAEN 0
#endif

#ifndef CONFIG_GRPCI2_VENDORID
#define CONFIG_GRPCI2_VENDORID 0
#endif

#ifndef CONFIG_GRPCI2_DEVICEID
#define CONFIG_GRPCI2_DEVICEID 0
#endif

#ifndef CONFIG_GRPCI2_CLASS
#define CONFIG_GRPCI2_CLASS 0
#endif

#ifndef CONFIG_GRPCI2_REVID
#define CONFIG_GRPCI2_REVID 0
#endif

#ifndef CONFIG_GRPCI2_CAPPOINT
#define CONFIG_GRPCI2_CAPPOINT 40
#endif

#ifndef CONFIG_GRPCI2_NEXTCAPPOINT
#define CONFIG_GRPCI2_NEXTCAPPOINT 0
#endif

#ifndef CONFIG_GRPCI2_BAR0
#define CONFIG_GRPCI2_BAR0 0
#endif
#ifndef CONFIG_GRPCI2_BAR1
#define CONFIG_GRPCI2_BAR1 0
#endif
#ifndef CONFIG_GRPCI2_BAR2
#define CONFIG_GRPCI2_BAR2 0
#endif
#ifndef CONFIG_GRPCI2_BAR3
#define CONFIG_GRPCI2_BAR3 0
#endif
#ifndef CONFIG_GRPCI2_BAR4
#define CONFIG_GRPCI2_BAR4 0
#endif
#ifndef CONFIG_GRPCI2_BAR5
#define CONFIG_GRPCI2_BAR5 0
#endif

#if defined CONFIG_GRPCI2_FIFO8
#define CFG_GRPCI2_FIFO 3
#elif defined CONFIG_GRPCI2_FIFO16
#define CFG_GRPCI2_FIFO 4
#elif defined CONFIG_GRPCI2_FIFO32
#define CFG_GRPCI2_FIFO 5
#elif defined CONFIG_GRPCI2_FIFO64
#define CFG_GRPCI2_FIFO 6
#elif defined CONFIG_GRPCI2_FIFO128
#define CFG_GRPCI2_FIFO 7
#else
#define CFG_GRPCI2_FIFO 3
#endif

#if defined CONFIG_GRPCI2_FIFOCNT1
#define CFG_GRPCI2_FIFOCNT 1
#elif defined CONFIG_GRPCI2_FIFOCNT2
#define CFG_GRPCI2_FIFOCNT 2
#elif defined CONFIG_GRPCI2_FIFOCNT3
#define CFG_GRPCI2_FIFOCNT 3
#elif defined CONFIG_GRPCI2_FIFOCNT4
#define CFG_GRPCI2_FIFOCNT 4
#else
#define CFG_GRPCI2_FIFOCNT 2
#endif

#if defined CONFIG_GRPCI2_ENDIAN
#define CFG_GRPCI2_LENDIAN 1
#else
#define CFG_GRPCI2_LENDIAN 0
#endif

#if defined CONFIG_GRPCI2_DINT
#define CFG_GRPCI2_DINT 1
#else
#define CFG_GRPCI2_DINT 0
#endif
#ifndef CONFIG_GRPCI2_DINTMASK
#define CONFIG_GRPCI2_DINTMASK 0
#endif

#if defined CONFIG_GRPCI2_HINT
#define CFG_GRPCI2_HINT 1
#else
#define CFG_GRPCI2_HINT 0
#endif
#ifndef CONFIG_GRPCI2_HINTMASK
#define CONFIG_GRPCI2_HINTMASK 0
#endif

#if defined CONFIG_GRPCI2_TRACE0
#define CFG_GRPCI2_TRACEDEPTH 0
#elif defined CONFIG_GRPCI2_TRACE256
#define CFG_GRPCI2_TRACEDEPTH 256
#elif defined CONFIG_GRPCI2_TRACE512
#define CFG_GRPCI2_TRACEDEPTH 512
#elif defined CONFIG_GRPCI2_TRACE1024
#define CFG_GRPCI2_TRACEDEPTH 1024
#elif defined CONFIG_GRPCI2_TRACE2048
#define CFG_GRPCI2_TRACEDEPTH 2014
#elif defined CONFIG_GRPCI2_TRACE4096
#define CFG_GRPCI2_TRACEDEPTH 4096
#else
#define CFG_GRPCI2_TRACEDEPTH 0
#endif

#ifndef CONFIG_GRPCI2_TRACEAPB
#define CONFIG_GRPCI2_TRACEAPB 0
#endif

#if defined CONFIG_GRPCI2_BYPASS
#define CFG_GRPCI2_INBYPASS 1
#else
#define CFG_GRPCI2_INBYPASS 0
#endif

#ifndef CONFIG_GRPCI2_EXTCFG
#define CONFIG_GRPCI2_EXTCFG 0
#endif
