#ifndef CONFIG_SPICTRL_ENABLE
#define CONFIG_SPICTRL_ENABLE 0
#endif
#ifndef CONFIG_SPICTRL_NUM
#define CONFIG_SPICTRL_NUM 1
#endif
#ifndef CONFIG_SPICTRL_SLVS
#define CONFIG_SPICTRL_SLVS 1
#endif
#ifndef CONFIG_SPICTRL_FIFO
#define CONFIG_SPICTRL_FIFO 1
#endif
#ifndef CONFIG_SPICTRL_SLVREG
#define CONFIG_SPICTRL_SLVREG 0
#endif
#ifndef CONFIG_SPICTRL_ODMODE
#define CONFIG_SPICTRL_ODMODE 0
#endif
#ifndef CONFIG_SPICTRL_AM
#define CONFIG_SPICTRL_AM 0
#endif
#ifndef CONFIG_SPICTRL_ASEL
#define CONFIG_SPICTRL_ASEL 0
#endif
#ifndef CONFIG_SPICTRL_TWEN
#define CONFIG_SPICTRL_TWEN 0
#endif
#ifndef CONFIG_SPICTRL_MAXWLEN
#define CONFIG_SPICTRL_MAXWLEN 0
#endif
#ifndef CONFIG_SPICTRL_SYNCRAM
#define CONFIG_SPICTRL_SYNCRAM 0
#endif
#if defined(CONFIG_SPICTRL_DMRFT)
#define CONFIG_SPICTRL_FT 1
#elif defined(CONFIG_SPICTRL_TMRFT)
#define CONFIG_SPICTRL_FT 2
#else
#define CONFIG_SPICTRL_FT 0
#endif
