# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.cache/wt [current_project]
set_property parent.project_path /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.3 [current_project]
set_property ip_output_repo /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/include
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socgen/grlib
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socgen/esp
  /home/jescobedo/repos/juanesp/accelerators/third-party/NV_NVDLA/vlog_incdir
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/common/defs
} [current_fileset]
set_property verilog_define {XILINX_FPGA=1 WT_DCACHE=1} [current_fileset]
read_verilog {
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/util/instr_trace_item.svh
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/util/ex_trace_item.svh
}
set_property file_type "Verilog Header" [get_files /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/util/instr_trace_item.svh]
set_property file_type "Verilog Header" [get_files /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/util/ex_trace_item.svh]
read_verilog -library xil_defaultlib -sv {
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/mem/BRAM_1024x16.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/mem/BRAM_16384x1.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/mem/BRAM_2048x8.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/mem/BRAM_4096x4.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/mem/BRAM_8192x2.v
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpga-support/rtl/SyncSpRamBeNx64.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/riscv-dbg/src/dm_pkg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/include/riscv_pkg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/include/ariane_pkg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/alu.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/amo_alu.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/amo_buffer.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/register_interface/src/apb_to_reg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane_soc_pkg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi/src/axi_pkg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/include/ariane_axi_pkg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/ariane.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/ariane_regfile_ff.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane_wrap.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/fpga/src/axi2apb/src/axi2apb_64_32.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_AR_allocator.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_AW_allocator.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_BR_allocator.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_BW_allocator.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_DW_allocator.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_adapter.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_address_decoder_AR.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_address_decoder_AW.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_address_decoder_BR.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_address_decoder_BW.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_address_decoder_DW.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_ar_buffer.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_aw_buffer.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_b_buffer.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi/src/axi_cut.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/include/axi_intf.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi/src/axi_intf_bind_mst.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi/src/axi_intf_bind_slv.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi/src/axi_join.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/clint/axi_lite_interface.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/util/axi_master_connect.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi/src/axi_multicut.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_multiplexer.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_node.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_node_arbiter.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_node_intf_wrap.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_node_wrap_with_slices.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_r_buffer.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_request_block.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_res_tbl.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_node/src/axi_response_block.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_riscv_amos.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_riscv_amos_alu.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_riscv_atomics.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_riscv_atomics_wrap.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_riscv_atomics/src/axi_riscv_lrsc.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/include/std_cache_pkg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/axi_shim.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_single_slice.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/fpga/src/axi_slice/src/axi_w_buffer.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/frontend/bht.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/branch_unit.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/frontend/btb.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/cache_ctrl.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/clint/clint.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/commit_stage.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/compressed_decoder.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/controller.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/csr_buffer.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/csr_regfile.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/decoder.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
  /home/jescobedo/repos/juanesp/rtl/misc/esplink.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/ex_stage.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/exp_backoff.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/deprecated/fifo_v1.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/deprecated/fifo_v2.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/fifo_v3.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_pkg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_cast_multi.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_classifier.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_divsqrt_multi.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_fma.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_fma_multi.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_noncomp.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_opgroup_block.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_opgroup_fmt_slice.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_opgroup_multifmt_slice.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_rounding.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpnew_top.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu_wrap.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/frontend/frontend.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/id_stage.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/frontend/instr_queue.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/instr_realign.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/frontend/instr_scan.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/include/instr_tracer_pkg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/util/instr_tracer.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/common/rtl/interface_controller.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/issue_read_operands.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/issue_stage.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_bufs.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_core.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_fsm.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_input_decoder.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_interface_defs.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_interfaces.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_localmem.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_lookup.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_regs.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_reqs.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_rtl_top.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/l2/rtl/l2_write_word.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/lfsr_8bit.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/llc_bufs.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/llc_core.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/llc_input_decoder.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/llc_interface_defs.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/llc_interfaces.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/llc_localmem.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/llc_lookup_way.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/llc_process_request.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/llc_regs.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/llc_rtl_top.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/llc_update.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/load_store_unit.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/load_unit.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/lzc.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/miss_handler.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/mmu.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/mult.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/multiplier.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/perf_counters.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/register_interface/src/reg_intf_pkg.sv
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socgen/esp/plic_regmap.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/rv_plic/rtl/plic_top.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/popcount.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/fpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/pri_enc.sv
  /home/jescobedo/repos/juanesp/rtl/caches/esp-caches/llc/rtl/pri_enc_half.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/ptw.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/frontend/ras.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/re_name.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/register_interface/src/reg_intf.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/riscv_clint_wrap.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/riscv_plic_wrap.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/rr_arb_tree.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/rv_plic/rtl/rv_plic_gateway.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/rv_plic/rtl/rv_plic_target.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/scoreboard.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/serdiv.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/shift_reg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/spill_register.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/util/sram.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/std_cache_subsystem.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/std_icache.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/std_nbdcache.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/store_buffer.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/store_unit.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/stream_arbiter.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/stream_arbiter_flushable.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/stream_demux.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/common_cells/src/stream_mux.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/tag_cmp.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/tlb.sv
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_10abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_11abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_12abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_13abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_14abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_15abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_16abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_17abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_18abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_19abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_20abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_6abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_7abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_8abits.v
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/sram_b/unisim_sram_b_9abits.v
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/include/wt_cache_pkg.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_axi_adapter.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_cache_subsystem.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_dcache.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_dcache_ctrl.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_dcache_mem.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_dcache_missunit.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_dcache_wbuffer.sv
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane/src/cache_subsystem/wt_icache.sv
}
read_vhdl -library xil_defaultlib {
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socgen/esp/esp_global.vhd
  /home/jescobedo/repos/juanesp/rtl/misc/stdlib/config_types.vhd
  /home/jescobedo/repos/juanesp/rtl/misc/stdlib/config.vhd
  /home/jescobedo/repos/juanesp/rtl/misc/stdlib/version.vhd
  /home/jescobedo/repos/juanesp/rtl/misc/stdlib/stdlib.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/gencomp.vhd
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socketgen/sld_devices.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/bus/amba.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/bus/devices.vhd
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socketgen/genacc.vhd
  /home/jescobedo/repos/juanesp/rtl/cores/leon3/coretypes.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/esp_acc_regmap.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/monitor/monitor_pkg.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/nocpackage.vhd
  /home/jescobedo/repos/juanesp/rtl/misc/misc.vhd
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socketgen/allcaches.vhd
  /home/jescobedo/repos/juanesp/rtl/caches/cachepackage.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/tile.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/queues/acc_tile_q.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/adapters/ahb2axi_l.vhd
  /home/jescobedo/repos/juanesp/rtl/sim/utils/stdio.vhd
  /home/jescobedo/repos/juanesp/rtl/sim/utils/testlib.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/bus/ahbctrl.vhd
  /home/jescobedo/repos/juanesp/rtl/misc/ahbram.vhd
  /home/jescobedo/repos/juanesp/rtl/misc/ahbram_dp.vhd
  /home/jescobedo/repos/juanesp/rtl/sim/utils/sim.vhd
  /home/jescobedo/repos/juanesp/rtl/misc/ahbslm.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/ahbslv2noc.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/allclkgen.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/alldco.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/allmem.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/allpads.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/allpll.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/apb2noc.vhd
  /home/jescobedo/repos/juanesp/rtl/peripherals/uart/uart.vhd
  /home/jescobedo/repos/juanesp/rtl/peripherals/uart/apbuart.vhd
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane_esp_pkg.vhd
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/ariane_axi_wrap.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/axislv2noc.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/bypassable_queue.vhd
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socketgen/caches.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/clkgen_unisim.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/queues/cpu_tile_q.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/dco.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/jtag/demux_1to6.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/dvfs/dvfs.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/dvfs/dvfs_fsm.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/dvfs/dvfs_top.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/queues/empty_tile_q.vhd
  /home/jescobedo/repos/juanesp/rtl/cores/leon3/leon3.vhd
  /home/jescobedo/repos/juanesp/rtl/peripherals/ethernet/net.vhd
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socketgen/sldacc.vhd
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socgen/grlib/grlib_config.vhd
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socgen/esp/socmap.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/csr/esp_csr_pkg.vhd
  /home/jescobedo/repos/juanesp/rtl/tiles/tiles_pkg.vhd
  /home/jescobedo/repos/juanesp/rtl/tiles/esp.vhd
  /home/jescobedo/repos/juanesp/rtl/peripherals/ethernet/greth_pkg.vhd
  /home/jescobedo/repos/juanesp/rtl/misc/esp_init.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/csr/esp_tile_csr.vhd
  /home/jescobedo/repos/juanesp/rtl/peripherals/ethernet/eth_edcl_ahb_mst.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/fifo.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/fifo1.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/fifo2.vhd
  /home/jescobedo/repos/juanesp/rtl/caches/fifo_custom.vhd
  /home/jescobedo/repos/juanesp/rtl/caches/gencaches.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/genram_pkg.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/gp_arbiter.vhd
  /home/jescobedo/repos/juanesp/rtl/peripherals/timer/gptimer_pkg.vhd
  /home/jescobedo/repos/juanesp/rtl/peripherals/timer/gptimer.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/grgates.vhd
  /home/jescobedo/repos/juanesp/rtl/cores/ibex/ibex_esp_pkg.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/inferred_async_fifo.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/inpad.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/intack2noc.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/intreq2noc.vhd
  /home/jescobedo/repos/juanesp/rtl/peripherals/interrupt/irqmp.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/jtag/jtag_pkg.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/jtag/jtag_test.vhd
  /home/jescobedo/repos/juanesp/rtl/caches/l2_wrapper.vhd
  /home/jescobedo/repos/juanesp/rtl/caches/llc_wrapper.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/mem2ext.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/queues/mem_tile_q.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/inferred/memory_inferred.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/memory_unisim.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/memrwcol.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/queues/misc_tile_q.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/jtag/mux_6to1.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/nobypassable_queue.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/noc2ahbmst.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/noc2apb.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/proxy/noc2intreq.vhd
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socketgen/noc_NV_NVDLA.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/outpad.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/virtexup/pads_unisim.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/bus/patient_apbctrl.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/jtag/piso.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/pll.vhd
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/riscv_clint_ahb_wrap.vhd
  /home/jescobedo/repos/juanesp/rtl/cores/ariane/riscv_plic_apb_wrap.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/router.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/routing_engine.vhd
  /home/jescobedo/repos/juanesp/rtl/misc/rstgen.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/rtr_arbitration_engine.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/jtag/sipo.vhd
  /home/jescobedo/repos/juanesp/rtl/sockets/queues/slm_tile_q.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/sync_noc32_xy.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/sync_noc_set.vhd
  /home/jescobedo/repos/juanesp/rtl/noc/sync_noc_xy.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/syncram.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/syncram_dp.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/syncrambw.vhd
  /home/jescobedo/repos/juanesp/rtl/techmap/maps/syncreg.vhd
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/socketgen/tile_acc.vhd
  /home/jescobedo/repos/juanesp/rtl/tiles/tile_cpu.vhd
  /home/jescobedo/repos/juanesp/rtl/tiles/tile_empty.vhd
  /home/jescobedo/repos/juanesp/rtl/tiles/tile_io.vhd
  /home/jescobedo/repos/juanesp/rtl/tiles/tile_mem.vhd
  /home/jescobedo/repos/juanesp/rtl/tiles/tile_slm.vhd
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/top.vhd
  /home/jescobedo/repos/juanesp/rtl/misc/unread.vhd
  /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/zynqmp_top_wrapper.vhd
}
add_files /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/zynqmpsoc.bd
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_zynq_ultra_ps_e_0_0/zynqmpsoc_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_zynq_ultra_ps_e_0_0/zynqmpsoc_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_axi_ahblite_bridge_0_0/zynqmpsoc_axi_ahblite_bridge_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_ahblite_axi_bridge_0_0/zynqmpsoc_ahblite_axi_bridge_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_rst_ps8_0_75M_0/zynqmpsoc_rst_ps8_0_75M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_rst_ps8_0_75M_0/zynqmpsoc_rst_ps8_0_75M_0.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_rst_ps8_0_75M_0/zynqmpsoc_rst_ps8_0_75M_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/bd_c007_ila_lib_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/bd_c007_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/zynqmpsoc_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_axi_gpio_0_0/zynqmpsoc_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_axi_gpio_0_0/zynqmpsoc_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_axi_gpio_0_0/zynqmpsoc_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_auto_pc_0/zynqmpsoc_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/zynqmpsoc_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg.xdc
set_property used_in_implementation false [get_files /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg.xdc]

read_xdc /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-mig-pins.xdc
set_property used_in_implementation false [get_files /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-mig-pins.xdc]

read_xdc /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-mig-constraints.xdc
set_property used_in_implementation false [get_files /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-mig-constraints.xdc]

read_xdc /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-eth-pins.xdc
set_property used_in_implementation false [get_files /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-eth-pins.xdc]

read_xdc /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-dvi-pins.xdc
set_property used_in_implementation false [get_files /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-dvi-pins.xdc]

read_xdc /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-eth-constraints.xdc
set_property used_in_implementation false [get_files /home/jescobedo/repos/juanesp/constraints/xilinx-zcu102-xczu9eg/xilinx-zcu102-xczu9eg-eth-constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top zynqmp_top_wrapper -part xczu9eg-ffvb1156-2-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef zynqmp_top_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file zynqmp_top_wrapper_utilization_synth.rpt -pb zynqmp_top_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
