# Copyright (c) 2011-2023 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0

all: generate

generate: generator.py
	@python generator.py

clean:
	rm -rf ../input/*.txt

PHONY: clean generate
