# (c) Copyright 2012-2019 PRO DESIGN Electronic GmbH.                     
# All rights reserved.                                                    
#                                                                         
# This file is owned and controlled by ProDesign and must be used solely  
# for design, simulation, implementation and creation of design files     
# limited to profpga systems or technologies. Use with non-profpga        
# systems or technologies is expressly prohibited and immediately         
# terminates your license.                                                
#                                                                         
# PRODESIGN IS PROVIDING THIS DESIGN, CODE, OR INFORMATION "AS IS" SOLELY 
# FOR USE IN DEVELOPING PROGRAMS AND SOLUTIONS FOR PRODESIGN SYSTEMS. BY  
# PROVIDING THIS DESIGN, CODE, OR INFORMATION AS ONE POSSIBLE             
# IMPLEMENTATION OF THIS FEATURE, APPLICATION OR STANDARD, PRODESIGN IS   
# MAKING NO REPRESENTATION THAT THIS IMPLEMENTATION IS FREE FROM ANY      
# CLAIMS OF INFRINGEMENT, AND YOU ARE RESPONSIBLE FOR OBTAINING ANY       
# RIGHTS YOU MAY REQUIRE FOR YOUR IMPLEMENTATION. PRODESIGN EXPRESSLY     
# DISCLAIMS ANY WARRANTY WHATSOEVER WITH RESPECT TO THE ADEQUACY OF THE   
# IMPLEMENTATION, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OR          
# REPRESENTATIONS THAT THIS IMPLEMENTATION IS FREE FROM CLAIMS OF         
# INFRINGEMENT, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A   
# PARTICULAR PURPOSE.                                                     
#                                                                         
# ProDesign products are not intended for use in life support appliances, 
# devices, or systems. Use in such applications are expressly             
# prohibited.                                                             
#                                                                         
# This file was generated by profpga_brdgen version 11.2 
#   on Tue May 11 17:14:46 2021 

# pins which are connected to motherboard connector BC1 
# and connector BA1 on x-board EB-PDS-DDR3-R2 
set_property  PACKAGE_PIN G27 [get_ports {c0_ddr3_addr[0]}] #bc1_eb1_A0
set_property  PACKAGE_PIN H28 [get_ports {c0_ddr3_addr[1]}] #bc1_eb1_A1
set_property  PACKAGE_PIN H27 [get_ports {c0_ddr3_addr[2]}] #bc1_eb1_A2
set_property  PACKAGE_PIN F29 [get_ports {c0_ddr3_addr[3]}] #bc1_eb1_A3
set_property  PACKAGE_PIN G29 [get_ports {c0_ddr3_addr[4]}] #bc1_eb1_A4
set_property  PACKAGE_PIN P25 [get_ports {c0_ddr3_addr[5]}] #bc1_eb1_A5
set_property  PACKAGE_PIN R25 [get_ports {c0_ddr3_addr[6]}] #bc1_eb1_A6
set_property  PACKAGE_PIN N28 [get_ports {c0_ddr3_addr[7]}] #bc1_eb1_A7
set_property  PACKAGE_PIN P28 [get_ports {c0_ddr3_addr[8]}] #bc1_eb1_A8
set_property  PACKAGE_PIN N27 [get_ports {c0_ddr3_addr[9]}] #bc1_eb1_A9
set_property  PACKAGE_PIN N26 [get_ports {c0_ddr3_addr[10]}] #bc1_eb1_A10
set_property  PACKAGE_PIN P26 [get_ports {c0_ddr3_addr[11]}] #bc1_eb1_A11
set_property  PACKAGE_PIN R26 [get_ports {c0_ddr3_addr[12]}] #bc1_eb1_A12
set_property  PACKAGE_PIN R28 [get_ports {c0_ddr3_addr[13]}] #bc1_eb1_A13
set_property  PACKAGE_PIN T28 [get_ports {c0_ddr3_addr[14]}] #bc1_eb1_A14
set_property  PACKAGE_PIN G26 [get_ports {c0_ddr3_ba[0]}] #bc1_eb1_BA0
set_property  PACKAGE_PIN H26 [get_ports {c0_ddr3_ba[1]}] #bc1_eb1_BA1
set_property  PACKAGE_PIN F27 [get_ports {c0_ddr3_ba[2]}] #bc1_eb1_BA2
set_property  PACKAGE_PIN E27 [get_ports {c0_ddr3_cas_n}]  #bc1_eb1_CASn
set_property  PACKAGE_PIN T27 [get_ports {c0_ddr3_ck_p}] #bc1_eb1_CK
set_property  PACKAGE_PIN D26 [get_ports {c0_ddr3_cke}] #bc1_eb1_CKE
set_property  PACKAGE_PIN R27 [get_ports {c0_ddr3_ck_n}]  #bc1_eb1_CKn
#set_property  PACKAGE_PIN D28 [get_ports {c0_sys_clk_p}] #bc1_eb1_CLK_200MHZ
#set_property  PACKAGE_PIN D29 [get_ports {c0_sys_clk_n}] #bc1_eb1_CLK_200MHZn
set_property  PACKAGE_PIN E28 [get_ports {c0_ddr3_sc_n}] #bc1_eb1_20CSn
set_property  PACKAGE_PIN N24 [get_ports {c0_ddr3_dq[0]}] #bc1_eb1_DQ00_D0
set_property  PACKAGE_PIN P23 [get_ports {c0_ddr3_dq[1]}] #bc1_eb1_DQ00_D1
set_property  PACKAGE_PIN N23 [get_ports {c0_ddr3_dq[2]}] #bc1_eb1_DQ00_D2
set_property  PACKAGE_PIN T22 [get_ports {c0_ddr3_dq[3]}] #bc1_eb1_DQ00_D3
set_property  PACKAGE_PIN R22 [get_ports {c0_ddr3_dq[4]}] #bc1_eb1_DQ00_D4
set_property  PACKAGE_PIN T23 [get_ports {c0_ddr3_dq[5]}] #bc1_eb1_DQ00_D5
set_property  PACKAGE_PIN R23 [get_ports {c0_ddr3_dq[6]}] #bc1_eb1_DQ00_D6
set_property  PACKAGE_PIN R21 [get_ports {c0_ddr3_dq[7]}] #bc1_eb1_DQ00_D7
set_property  PACKAGE_PIN P24 [get_ports {c0_ddr3_dm[0]}] #bc1_eb1_DQ00_DM
set_property  PACKAGE_PIN N22 [get_ports {c0_ddr3_dqs_p[0]}] #bc1_eb1_DQ00_DQS
set_property  PACKAGE_PIN N21 [get_ports {c0_ddr3_dqs_n[0]}] #bc1_eb1_DQ00_DQSn
set_property  PACKAGE_PIN H23 [get_ports {c0_ddr3_dq[8]}] #bc1_eb1_DQ01_D0
set_property  PACKAGE_PIN G25 [get_ports {c0_ddr3_dq[9]}] #bc1_eb1_DQ01_D1
set_property  PACKAGE_PIN F25 [get_ports {c0_ddr3_dq[10]}] #bc1_eb1_DQ01_D2
set_property  PACKAGE_PIN J24 [get_ports {c0_ddr3_dq[11]}] #bc1_eb1_DQ01_D3
set_property  PACKAGE_PIN H24 [get_ports {c0_ddr3_dq[12]}] #bc1_eb1_DQ01_D4
set_property  PACKAGE_PIN F22 [get_ports {c0_ddr3_dq[13]}] #bc1_eb1_DQ01_D5
set_property  PACKAGE_PIN E22 [get_ports {c0_ddr3_dq[14]}] #bc1_eb1_DQ01_D6
set_property  PACKAGE_PIN F23 [get_ports {c0_ddr3_dq[15]}] #bc1_eb1_DQ01_D7
set_property  PACKAGE_PIN J23 [get_ports {c0_ddr3_dm[1]}] #bc1_eb1_DQ01_DM
set_property  PACKAGE_PIN G24 [get_ports {c0_ddr3_dqs_p[1]}] #bc1_eb1_DQ01_DQS
set_property  PACKAGE_PIN F24 [get_ports {c0_ddr3_dqs_n[1]}] #bc1_eb1_DQ01_DQSn
set_property  PACKAGE_PIN D23 [get_ports {c0_ddr3_dq[16]}] #bc1_eb1_DQ02_D0
set_property  PACKAGE_PIN C23 [get_ports {c0_ddr3_dq[17]}] #bc1_eb1_DQ02_D1
set_property  PACKAGE_PIN D24 [get_ports {c0_ddr3_dq[18]}] #bc1_eb1_DQ02_D2
set_property  PACKAGE_PIN C24 [get_ports {c0_ddr3_dq[19]}] #bc1_eb1_DQ02_D3
set_property  PACKAGE_PIN D25 [get_ports {c0_ddr3_dq[20]}] #bc1_eb1_DQ02_D4
set_property  PACKAGE_PIN A23 [get_ports {c0_ddr3_dq[21]}] #bc1_eb1_DQ02_D5
set_property  PACKAGE_PIN A22 [get_ports {c0_ddr3_dq[22]}] #bc1_eb1_DQ02_D6
set_property  PACKAGE_PIN B24 [get_ports {c0_ddr3_dq[23]}] #bc1_eb1_DQ02_D7
set_property  PACKAGE_PIN E25 [get_ports {c0_ddr3_dm[2]}] #bc1_eb1_DQ02_DM
set_property  PACKAGE_PIN C22 [get_ports {c0_ddr3_dqs_p[2]}] #bc1_eb1_DQ02_DQS
set_property  PACKAGE_PIN B22 [get_ports {c0_ddr3_dqs_n[2]}] #bc1_eb1_DQ02_DQSn
set_property  PACKAGE_PIN H29 [get_ports {c0_ddr3_dq[24]}] #bc1_eb1_DQ03_D0
set_property  PACKAGE_PIN G30 [get_ports {c0_ddr3_dq[25]}] #bc1_eb1_DQ03_D1
set_property  PACKAGE_PIN J33 [get_ports {c0_ddr3_dq[26]}] #bc1_eb1_DQ03_D2
set_property  PACKAGE_PIN H33 [get_ports {c0_ddr3_dq[27]}] #bc1_eb1_DQ03_D3
set_property  PACKAGE_PIN K32 [get_ports {c0_ddr3_dq[28]}] #bc1_eb1_DQ03_D4
set_property  PACKAGE_PIN K33 [get_ports {c0_ddr3_dq[29]}] #bc1_eb1_DQ03_D5
set_property  PACKAGE_PIN K31 [get_ports {c0_ddr3_dq[30]}] #bc1_eb1_DQ03_D6
set_property  PACKAGE_PIN J31 [get_ports {c0_ddr3_dq[31]}] #bc1_eb1_DQ03_D7
set_property  PACKAGE_PIN H31 [get_ports {c0_ddr3_dm[3]}] #bc1_eb1_DQ03_DM
set_property  PACKAGE_PIN K30 [get_ports {c0_ddr3_dqs_p[3]}] #bc1_eb1_DQ03_DQS
set_property  PACKAGE_PIN J30 [get_ports {c0_ddr3_dqs_n[3]}] #bc1_eb1_DQ03_DQSn
set_property  PACKAGE_PIN M31 [get_ports {c0_ddr3_dq[32]}] #bc1_eb1_DQ04_D0
set_property  PACKAGE_PIN L32 [get_ports {c0_ddr3_dq[33]}] #bc1_eb1_DQ04_D1
set_property  PACKAGE_PIN L33 [get_ports {c0_ddr3_dq[34]}] #bc1_eb1_DQ04_D2
set_property  PACKAGE_PIN N32 [get_ports {c0_ddr3_dq[35]}] #bc1_eb1_DQ04_D3
set_property  PACKAGE_PIN N33 [get_ports {c0_ddr3_dq[36]}] #bc1_eb1_DQ04_D4
set_property  PACKAGE_PIN L29 [get_ports {c0_ddr3_dq[37]}] #bc1_eb1_DQ04_D5
set_property  PACKAGE_PIN L30 [get_ports {c0_ddr3_dq[38]}] #bc1_eb1_DQ04_D6
set_property  PACKAGE_PIN N31 [get_ports {c0_ddr3_dq[39]}] #bc1_eb1_DQ04_D7
set_property  PACKAGE_PIN M30 [get_ports {c0_ddr3_dm[4]}] #bc1_eb1_DQ04_DM
set_property  PACKAGE_PIN N29 [get_ports {c0_ddr3_dqs_p[4]}] #bc1_eb1_DQ04_DQS
set_property  PACKAGE_PIN M29 [get_ports {c0_ddr3_dqs_n[4]}] #bc1_eb1_DQ04_DQSn
set_property  PACKAGE_PIN C33 [get_ports {c0_ddr3_dq[40]}] #bc1_eb1_DQ05_D0
set_property  PACKAGE_PIN G31 [get_ports {c0_ddr3_dq[41]}] #bc1_eb1_DQ05_D1
set_property  PACKAGE_PIN G32 [get_ports {c0_ddr3_dq[42]}] #bc1_eb1_DQ05_D2
set_property  PACKAGE_PIN F33 [get_ports {c0_ddr3_dq[43]}] #bc1_eb1_DQ05_D3
set_property  PACKAGE_PIN E33 [get_ports {c0_ddr3_dq[44]}] #bc1_eb1_DQ05_D4
set_property  PACKAGE_PIN F32 [get_ports {c0_ddr3_dq[45]}] #bc1_eb1_DQ05_D5
set_property  PACKAGE_PIN E32 [get_ports {c0_ddr3_dq[46]}] #bc1_eb1_DQ05_D6
set_property  PACKAGE_PIN E31 [get_ports {c0_ddr3_dq[47]}] #bc1_eb1_DQ05_D7
set_property  PACKAGE_PIN D33 [get_ports {c0_ddr3_dm[5]}] #bc1_eb1_DQ05_DM
set_property  PACKAGE_PIN C32 [get_ports {c0_ddr3_dqs_p[5]}] #bc1_eb1_DQ05_DQS
set_property  PACKAGE_PIN B32 [get_ports {c0_ddr3_dqs_n[5]}] #bc1_eb1_DQ05_DQSn
set_property  PACKAGE_PIN D30 [get_ports {c0_ddr3_dq[48]}] #bc1_eb1_DQ06_D0
set_property  PACKAGE_PIN C31 [get_ports {c0_ddr3_dq[49]}] #bc1_eb1_DQ06_D1
set_property  PACKAGE_PIN F30 [get_ports {c0_ddr3_dq[50]}] #bc1_eb1_DQ06_D2
set_property  PACKAGE_PIN E30 [get_ports {c0_ddr3_dq[51]}] #bc1_eb1_DQ06_D3
set_property  PACKAGE_PIN A30 [get_ports {c0_ddr3_dq[52]}] #bc1_eb1_DQ06_D4
set_property  PACKAGE_PIN C29 [get_ports {c0_ddr3_dq[53]}] #bc1_eb1_DQ06_D5
set_property  PACKAGE_PIN B29 [get_ports {c0_ddr3_dq[54]}] #bc1_eb1_DQ06_D6
set_property  PACKAGE_PIN B30 [get_ports {c0_ddr3_dq[55]}] #bc1_eb1_DQ06_D7
set_property  PACKAGE_PIN A29 [get_ports {c0_ddr3_dm[6]}] #bc1_eb1_DQ06_DM
set_property  PACKAGE_PIN A32 [get_ports {c0_ddr3_dqs_p[6]}] #bc1_eb1_DQ06_DQS
set_property  PACKAGE_PIN A33 [get_ports {c0_ddr3_dqs_n[6]}] #bc1_eb1_DQ06_DQSn
set_property  PACKAGE_PIN H22 [get_ports {c0_ddr3_dq[56]}] #bc1_eb1_DQ07_D0
set_property  PACKAGE_PIN G22 [get_ports {c0_ddr3_dq[57]}] #bc1_eb1_DQ07_D1
set_property  PACKAGE_PIN K22 [get_ports {c0_ddr3_dq[58]}] #bc1_eb1_DQ07_D2
set_property  PACKAGE_PIN K21 [get_ports {c0_ddr3_dq[59]}] #bc1_eb1_DQ07_D3
set_property  PACKAGE_PIN M22 [get_ports {c0_ddr3_dq[60]}] #bc1_eb1_DQ07_D4
set_property  PACKAGE_PIN L22 [get_ports {c0_ddr3_dq[61]}] #bc1_eb1_DQ07_D5
set_property  PACKAGE_PIN J21 [get_ports {c0_ddr3_dq[62]}] #bc1_eb1_DQ07_D6
set_property  PACKAGE_PIN H21 [get_ports {c0_ddr3_dq[63]}] #bc1_eb1_DQ07_D7
set_property  PACKAGE_PIN L23 [get_ports {c0_ddr3_dm[7]}] #bc1_eb1_DQ07_DM
set_property  PACKAGE_PIN M24 [get_ports {c0_ddr3_dqs_p[7]}] #bc1_eb1_DQ07_DQS
set_property  PACKAGE_PIN L24 [get_ports {c0_ddr3_dqs_n[7]}] #bc1_eb1_DQ07_DQSn
set_property  PACKAGE_PIN M27 [get_ports {c0_calib_complete}] #bc1_eb1_LED01
set_property  PACKAGE_PIN K27 [get_ports {c0_diagnostic_led}] #bc1_eb1_LED02
set_property  PACKAGE_PIN C26 [get_ports {c0_ddr3_odt}] #bc1_eb1_ODT
set_property  PACKAGE_PIN E26 [get_ports {c0_ddr3_ras_n}] #bc1_eb1_RASn
set_property  PACKAGE_PIN A24 [get_ports {c0_ddr3_reset_n}] #bc1_eb1_RESETn
set_property  PACKAGE_PIN F28 [get_ports {c0_ddr3_we_n}] #bc1_eb1_WEn

# pins which are connected to motherboard connector BC2 
# and connector BA1 on x-board EB-PDS-DDR3-R2 
set_property  PACKAGE_PIN AN41 [get_ports {c1_ddr3_addr[0]}] #bc2_eb1_A0
set_property  PACKAGE_PIN AP44 [get_ports {c1_ddr3_addr[1]}] #bc2_eb1_A1
set_property  PACKAGE_PIN AP43 [get_ports {c1_ddr3_addr[2]}] #bc2_eb1_A2
set_property  PACKAGE_PIN AP40 [get_ports {c1_ddr3_addr[3]}] #bc2_eb1_A3
set_property  PACKAGE_PIN AN39 [get_ports {c1_ddr3_addr[4]}] #bc2_eb1_A4
set_property  PACKAGE_PIN AP36 [get_ports {c1_ddr3_addr[5]}] #bc2_eb1_A5
set_property  PACKAGE_PIN AN36 [get_ports {c1_ddr3_addr[6]}] #bc2_eb1_A6
set_property  PACKAGE_PIN AR36 [get_ports {c1_ddr3_addr[7]}] #bc2_eb1_A7
set_property  PACKAGE_PIN AR35 [get_ports {c1_ddr3_addr[8]}] #bc2_eb1_A8
set_property  PACKAGE_PIN AP39 [get_ports {c1_ddr3_addr[9]}] #bc2_eb1_A9
set_property  PACKAGE_PIN AP38 [get_ports {c1_ddr3_addr[10]}] #bc2_eb1_A10
set_property  PACKAGE_PIN AN38 [get_ports {c1_ddr3_addr[11]}] #bc2_eb1_A11
set_property  PACKAGE_PIN AN37 [get_ports {c1_ddr3_addr[12]}] #bc2_eb1_A12
set_property  PACKAGE_PIN AR38 [get_ports {c1_ddr3_addr[13]}] #bc2_eb1_A13
set_property  PACKAGE_PIN AR37 [get_ports {c1_ddr3_addr[14]}] #bc2_eb1_A14
set_property  PACKAGE_PIN AT43 [get_ports {c1_ddr3_ba[0]}] #bc2_eb1_BA0
set_property  PACKAGE_PIN AR43 [get_ports {c1_ddr3_ba[1]}] #bc2_eb1_BA1
set_property  PACKAGE_PIN AP41 [get_ports {c1_ddr3_ba[2]}] #bc2_eb1_BA2
set_property  PACKAGE_PIN AR41 [get_ports {c1_ddr3_cas_n}]  #bc2_eb1_CASn
set_property  PACKAGE_PIN AP34 [get_ports {c1_ddr3_ck_p}] #bc2_eb1_CK
set_property  PACKAGE_PIN AU41 [get_ports {c1_ddr3_cke}] #bc2_eb1_CKE
set_property  PACKAGE_PIN AP35 [get_ports {c1_ddr3_ck_n}]  #bc2_eb1_CKn
#set_property  PACKAGE_PIN AU39 [get_ports {c1_sys_clk_p}] #bc2_eb1_CLK_200MHZ
#set_property  PACKAGE_PIN AU40 [get_ports {c1_sys_clk_n}] #bc2_eb1_CLK_200MHZn
set_property  PACKAGE_PIN AT42 [get_ports {c1_ddr3_sc_n}] #bc2_eb1_20CSn
set_property  PACKAGE_PIN AK41 [get_ports {c1_ddr3_dq[0]}] #bc2_eb1_DQ00_D0
set_property  PACKAGE_PIN AK40 [get_ports {c1_ddr3_dq[1]}] #bc2_eb1_DQ00_D1
set_property  PACKAGE_PIN AL40 [get_ports {c1_ddr3_dq[2]}] #bc2_eb1_DQ00_D2
set_property  PACKAGE_PIN AH43 [get_ports {c1_ddr3_dq[3]}] #bc2_eb1_DQ00_D3
set_property  PACKAGE_PIN AH44 [get_ports {c1_ddr3_dq[4]}] #bc2_eb1_DQ00_D4
set_property  PACKAGE_PIN AJ43 [get_ports {c1_ddr3_dq[5]}] #bc2_eb1_DQ00_D5
set_property  PACKAGE_PIN AJ44 [get_ports {c1_ddr3_dq[6]}] #bc2_eb1_DQ00_D6
set_property  PACKAGE_PIN AJ39 [get_ports {c1_ddr3_dq[7]}] #bc2_eb1_DQ00_D7
set_property  PACKAGE_PIN AJ41 [get_ports {c1_ddr3_dm[0]}] #bc2_eb1_DQ00_DM
set_property  PACKAGE_PIN AK42 [get_ports {c1_ddr3_dqs_p[0]}] #bc2_eb1_DQ00_DQS
set_property  PACKAGE_PIN AK43 [get_ports {c1_ddr3_dqs_n[0]}] #bc2_eb1_DQ00_DQSn
set_property  PACKAGE_PIN BC41 [get_ports {c1_ddr3_dq[8]}] #bc2_eb1_DQ01_D0
set_property  PACKAGE_PIN BD40 [get_ports {c1_ddr3_dq[9]}] #bc2_eb1_DQ01_D1
set_property  PACKAGE_PIN BD41 [get_ports {c1_ddr3_dq[10]}] #bc2_eb1_DQ01_D2
set_property  PACKAGE_PIN BC39 [get_ports {c1_ddr3_dq[11]}] #bc2_eb1_DQ01_D3
set_property  PACKAGE_PIN BD39 [get_ports {c1_ddr3_dq[12]}] #bc2_eb1_DQ01_D4
set_property  PACKAGE_PIN BB39 [get_ports {c1_ddr3_dq[13]}] #bc2_eb1_DQ01_D5
set_property  PACKAGE_PIN BB40 [get_ports {c1_ddr3_dq[14]}] #bc2_eb1_DQ01_D6
set_property  PACKAGE_PIN AY40 [get_ports {c1_ddr3_dq[15]}] #bc2_eb1_DQ01_D7
set_property  PACKAGE_PIN BB41 [get_ports {c1_ddr3_dm[1]}] #bc2_eb1_DQ01_DM
set_property  PACKAGE_PIN BC42 [get_ports {c1_ddr3_dqs_p[1]}] #bc2_eb1_DQ01_DQS
set_property  PACKAGE_PIN BC43 [get_ports {c1_ddr3_dqs_n[1]}] #bc2_eb1_DQ01_DQSn
set_property  PACKAGE_PIN AY38 [get_ports {c1_ddr3_dq[16]}] #bc2_eb1_DQ02_D0
set_property  PACKAGE_PIN BA39 [get_ports {c1_ddr3_dq[17]}] #bc2_eb1_DQ02_D1
set_property  PACKAGE_PIN BA37 [get_ports {c1_ddr3_dq[18]}] #bc2_eb1_DQ02_D2
set_property  PACKAGE_PIN BA38 [get_ports {c1_ddr3_dq[19]}] #bc2_eb1_DQ02_D3
set_property  PACKAGE_PIN AY37 [get_ports {c1_ddr3_dq[20]}] #bc2_eb1_DQ02_D4
set_property  PACKAGE_PIN BC38 [get_ports {c1_ddr3_dq[21]}] #bc2_eb1_DQ02_D5
set_property  PACKAGE_PIN BD38 [get_ports {c1_ddr3_dq[22]}] #bc2_eb1_DQ02_D6
set_property  PACKAGE_PIN BB37 [get_ports {c1_ddr3_dq[23]}] #bc2_eb1_DQ02_D7
set_property  PACKAGE_PIN AY36 [get_ports {c1_ddr3_dm[2]}] #bc2_eb1_DQ02_DM
set_property  PACKAGE_PIN AW38 [get_ports {c1_ddr3_dqs_p[2]}] #bc2_eb1_DQ02_DQS
set_property  PACKAGE_PIN AW39 [get_ports {c1_ddr3_dqs_n[2]}] #bc2_eb1_DQ02_DQSn
set_property  PACKAGE_PIN AL34 [get_ports {c1_ddr3_dq[24]}] #bc2_eb1_DQ03_D0
set_property  PACKAGE_PIN AM34 [get_ports {c1_ddr3_dq[25]}] #bc2_eb1_DQ03_D1
set_property  PACKAGE_PIN AL35 [get_ports {c1_ddr3_dq[26]}] #bc2_eb1_DQ03_D2
set_property  PACKAGE_PIN AM35 [get_ports {c1_ddr3_dq[27]}] #bc2_eb1_DQ03_D3
set_property  PACKAGE_PIN AJ35 [get_ports {c1_ddr3_dq[28]}] #bc2_eb1_DQ03_D4
set_property  PACKAGE_PIN AK35 [get_ports {c1_ddr3_dq[29]}] #bc2_eb1_DQ03_D5
set_property  PACKAGE_PIN AH32 [get_ports {c1_ddr3_dq[30]}] #bc2_eb1_DQ03_D6
set_property  PACKAGE_PIN AH33 [get_ports {c1_ddr3_dq[31]}] #bc2_eb1_DQ03_D7
set_property  PACKAGE_PIN AJ33 [get_ports {c1_ddr3_dm[3]}] #bc2_eb1_DQ03_DM
set_property  PACKAGE_PIN AK33 [get_ports {c1_ddr3_dqs_p[3]}] #bc2_eb1_DQ03_DQS
set_property  PACKAGE_PIN AL33 [get_ports {c1_ddr3_dqs_n[3]}] #bc2_eb1_DQ03_DQSn
set_property  PACKAGE_PIN AW41 [get_ports {c1_ddr3_dq[32]}] #bc2_eb1_DQ04_D0
set_property  PACKAGE_PIN AY43 [get_ports {c1_ddr3_dq[33]}] #bc2_eb1_DQ04_D1
set_property  PACKAGE_PIN BA43 [get_ports {c1_ddr3_dq[34]}] #bc2_eb1_DQ04_D2
set_property  PACKAGE_PIN AY41 [get_ports {c1_ddr3_dq[35]}] #bc2_eb1_DQ04_D3
set_property  PACKAGE_PIN AY42 [get_ports {c1_ddr3_dq[36]}] #bc2_eb1_DQ04_D4
set_property  PACKAGE_PIN BA44 [get_ports {c1_ddr3_dq[37]}] #bc2_eb1_DQ04_D5
set_property  PACKAGE_PIN BB44 [get_ports {c1_ddr3_dq[38]}] #bc2_eb1_DQ04_D6
set_property  PACKAGE_PIN BA42 [get_ports {c1_ddr3_dq[39]}] #bc2_eb1_DQ04_D7
set_property  PACKAGE_PIN AW40 [get_ports {c1_ddr3_dm[4]}] #bc2_eb1_DQ04_DM
set_property  PACKAGE_PIN AW43 [get_ports {c1_ddr3_dqs_p[4]}] #bc2_eb1_DQ04_DQS
set_property  PACKAGE_PIN AW44 [get_ports {c1_ddr3_dqs_n[4]}] #bc2_eb1_DQ04_DQSn
set_property  PACKAGE_PIN AJ36 [get_ports {c1_ddr3_dq[40]}] #bc2_eb1_DQ05_D0
set_property  PACKAGE_PIN AH37 [get_ports {c1_ddr3_dq[41]}] #bc2_eb1_DQ05_D1
set_property  PACKAGE_PIN AH38 [get_ports {c1_ddr3_dq[42]}] #bc2_eb1_DQ05_D2
set_property  PACKAGE_PIN AJ38 [get_ports {c1_ddr3_dq[43]}] #bc2_eb1_DQ05_D3
set_property  PACKAGE_PIN AK38 [get_ports {c1_ddr3_dq[44]}] #bc2_eb1_DQ05_D4
set_property  PACKAGE_PIN AL37 [get_ports {c1_ddr3_dq[45]}] #bc2_eb1_DQ05_D5
set_property  PACKAGE_PIN AL38 [get_ports {c1_ddr3_dq[46]}] #bc2_eb1_DQ05_D6
set_property  PACKAGE_PIN AK36 [get_ports {c1_ddr3_dq[47]}] #bc2_eb1_DQ05_D7
set_property  PACKAGE_PIN AH36 [get_ports {c1_ddr3_dm[5]}] #bc2_eb1_DQ05_DM
set_property  PACKAGE_PIN AM36 [get_ports {c1_ddr3_dqs_p[5]}] #bc2_eb1_DQ05_DQS
set_property  PACKAGE_PIN AM37 [get_ports {c1_ddr3_dqs_n[5]}] #bc2_eb1_DQ05_DQSn
set_property  PACKAGE_PIN AM40 [get_ports {c1_ddr3_dq[48]}] #bc2_eb1_DQ06_D0
set_property  PACKAGE_PIN AM41 [get_ports {c1_ddr3_dq[49]}] #bc2_eb1_DQ06_D1
set_property  PACKAGE_PIN AL39 [get_ports {c1_ddr3_dq[50]}] #bc2_eb1_DQ06_D2
set_property  PACKAGE_PIN AM39 [get_ports {c1_ddr3_dq[51]}] #bc2_eb1_DQ06_D3
set_property  PACKAGE_PIN AL43 [get_ports {c1_ddr3_dq[52]}] #bc2_eb1_DQ06_D4
set_property  PACKAGE_PIN AL44 [get_ports {c1_ddr3_dq[53]}] #bc2_eb1_DQ06_D5
set_property  PACKAGE_PIN AM44 [get_ports {c1_ddr3_dq[54]}] #bc2_eb1_DQ06_D6
set_property  PACKAGE_PIN AN43 [get_ports {c1_ddr3_dq[55]}] #bc2_eb1_DQ06_D7
set_property  PACKAGE_PIN AL42 [get_ports {c1_ddr3_dm[6]}] #bc2_eb1_DQ06_DM
set_property  PACKAGE_PIN AM42 [get_ports {c1_ddr3_dqs_p[6]}] #bc2_eb1_DQ06_DQS
set_property  PACKAGE_PIN AN42 [get_ports {c1_ddr3_dqs_n[6]}] #bc2_eb1_DQ06_DQSn
set_property  PACKAGE_PIN BC34 [get_ports {c1_ddr3_dq[56]}] #bc2_eb1_DQ07_D0
set_property  PACKAGE_PIN BD34 [get_ports {c1_ddr3_dq[57]}] #bc2_eb1_DQ07_D1
set_property  PACKAGE_PIN BB36 [get_ports {c1_ddr3_dq[58]}] #bc2_eb1_DQ07_D2
set_property  PACKAGE_PIN BC36 [get_ports {c1_ddr3_dq[59]}] #bc2_eb1_DQ07_D3
set_property  PACKAGE_PIN AW35 [get_ports {c1_ddr3_dq[60]}] #bc2_eb1_DQ07_D4
set_property  PACKAGE_PIN AY35 [get_ports {c1_ddr3_dq[61]}] #bc2_eb1_DQ07_D5
set_property  PACKAGE_PIN BA35 [get_ports {c1_ddr3_dq[62]}] #bc2_eb1_DQ07_D6
set_property  PACKAGE_PIN BB35 [get_ports {c1_ddr3_dq[63]}] #bc2_eb1_DQ07_D7
set_property  PACKAGE_PIN BA34 [get_ports {c1_ddr3_dm[7]}] #bc2_eb1_DQ07_DM
set_property  PACKAGE_PIN BD35 [get_ports {c1_ddr3_dqs_p[7]}] #bc2_eb1_DQ07_DQS
set_property  PACKAGE_PIN BD36 [get_ports {c1_ddr3_dqs_n[7]}] #bc2_eb1_DQ07_DQSn
set_property  PACKAGE_PIN AT37 [get_ports {c1_calib_complete}] #bc2_eb1_LED01
set_property  PACKAGE_PIN AV34 [get_ports {c1_diagnostic_led}] #bc2_eb1_LED02
set_property  PACKAGE_PIN AV41 [get_ports {c1_ddr3_odt}] #bc2_eb1_ODT
set_property  PACKAGE_PIN AR40 [get_ports {c1_ddr3_ras_n}] #bc2_eb1_RASn
set_property  PACKAGE_PIN BC37 [get_ports {c1_ddr3_reset_n}] #bc2_eb1_RESETn
set_property  PACKAGE_PIN AR42 [get_ports {c1_ddr3_we_n}] #bc2_eb1_WEn

# pins which are connected to motherboard connector BD1 
# and connector BA1 on x-board EB-PDS-DDR3-R2 
set_property  PACKAGE_PIN E13 [get_ports {c2_ddr3_addr[0]}] #bd1_eb1_A0
set_property  PACKAGE_PIN A13 [get_ports {c2_ddr3_addr[1]}] #bd1_eb1_A1
set_property  PACKAGE_PIN B14 [get_ports {c2_ddr3_addr[2]}] #bd1_eb1_A2
set_property  PACKAGE_PIN F13 [get_ports {c2_ddr3_addr[3]}] #bd1_eb1_A3
set_property  PACKAGE_PIN F14 [get_ports {c2_ddr3_addr[4]}] #bd1_eb1_A4
set_property  PACKAGE_PIN G17 [get_ports {c2_ddr3_addr[5]}] #bd1_eb1_A5
set_property  PACKAGE_PIN H17 [get_ports {c2_ddr3_addr[6]}] #bd1_eb1_A6
set_property  PACKAGE_PIN J16 [get_ports {c2_ddr3_addr[7]}] #bd1_eb1_A7
set_property  PACKAGE_PIN K16 [get_ports {c2_ddr3_addr[8]}] #bd1_eb1_A8
set_property  PACKAGE_PIN G14 [get_ports {c2_ddr3_addr[9]}] #bd1_eb1_A9
set_property  PACKAGE_PIN G15 [get_ports {c2_ddr3_addr[10]}] #bd1_eb1_A10
set_property  PACKAGE_PIN H14 [get_ports {c2_ddr3_addr[11]}] #bd1_eb1_A11
set_property  PACKAGE_PIN J14 [get_ports {c2_ddr3_addr[12]}] #bd1_eb1_A12
set_property  PACKAGE_PIN J15 [get_ports {c2_ddr3_addr[13]}] #bd1_eb1_A13
set_property  PACKAGE_PIN K15 [get_ports {c2_ddr3_addr[14]}] #bd1_eb1_A14
set_property  PACKAGE_PIN A14 [get_ports {c2_ddr3_ba[0]}] #bd1_eb1_BA0
set_property  PACKAGE_PIN A15 [get_ports {c2_ddr3_ba[1]}] #bd1_eb1_BA1
set_property  PACKAGE_PIN D13 [get_ports {c2_ddr3_ba[2]}] #bd1_eb1_BA2
set_property  PACKAGE_PIN C13 [get_ports {c2_ddr3_cas_n}]  #bd1_eb1_CASn
set_property  PACKAGE_PIN H16 [get_ports {c2_ddr3_ck_p}] #bd1_eb1_CK
set_property  PACKAGE_PIN F17 [get_ports {c2_ddr3_cke}] #bd1_eb1_CKE
set_property  PACKAGE_PIN G16 [get_ports {c2_ddr3_ck_n}]  #bd1_eb1_CKn
#set_property  PACKAGE_PIN F15 [get_ports {c2_sys_clk_p}] #bd1_eb1_CLK_200MHZ
#set_property  PACKAGE_PIN E15 [get_ports {c2_sys_clk_n}] #bd1_eb1_CLK_200MHZn
set_property  PACKAGE_PIN D14 [get_ports {c2_ddr3_sc_n}] #bd1_eb1_20CSn
set_property  PACKAGE_PIN N13 [get_ports {c2_ddr3_dq[0]}] #bd1_eb1_DQ00_D0
set_property  PACKAGE_PIN N12 [get_ports {c2_ddr3_dq[1]}] #bd1_eb1_DQ00_D1
set_property  PACKAGE_PIN M12 [get_ports {c2_ddr3_dq[2]}] #bd1_eb1_DQ00_D2
set_property  PACKAGE_PIN T13 [get_ports {c2_ddr3_dq[3]}] #bd1_eb1_DQ00_D3
set_property  PACKAGE_PIN R13 [get_ports {c2_ddr3_dq[4]}] #bd1_eb1_DQ00_D4
set_property  PACKAGE_PIN T12 [get_ports {c2_ddr3_dq[5]}] #bd1_eb1_DQ00_D5
set_property  PACKAGE_PIN R12 [get_ports {c2_ddr3_dq[6]}] #bd1_eb1_DQ00_D6
set_property  PACKAGE_PIN R11 [get_ports {c2_ddr3_dq[7]}] #bd1_eb1_DQ00_D7
set_property  PACKAGE_PIN P13 [get_ports {c2_ddr3_dm[0]}] #bd1_eb1_DQ00_DM
set_property  PACKAGE_PIN N11 [get_ports {c2_ddr3_dqs_p[0]}] #bd1_eb1_DQ00_DQS
set_property  PACKAGE_PIN M11 [get_ports {c2_ddr3_dqs_n[0]}] #bd1_eb1_DQ00_DQSn
set_property  PACKAGE_PIN A8 [get_ports {c2_ddr3_dq[8]}] #bd1_eb1_DQ01_D0
set_property  PACKAGE_PIN A10 [get_ports {c2_ddr3_dq[9]}] #bd1_eb1_DQ01_D1
set_property  PACKAGE_PIN A9 [get_ports {c2_ddr3_dq[10]}] #bd1_eb1_DQ01_D2
set_property  PACKAGE_PIN B12 [get_ports {c2_ddr3_dq[11]}] #bd1_eb1_DQ01_D3
set_property  PACKAGE_PIN A12 [get_ports {c2_ddr3_dq[12]}] #bd1_eb1_DQ01_D4
set_property  PACKAGE_PIN C12 [get_ports {c2_ddr3_dq[13]}] #bd1_eb1_DQ01_D5
set_property  PACKAGE_PIN C11 [get_ports {c2_ddr3_dq[14]}] #bd1_eb1_DQ01_D6
set_property  PACKAGE_PIN D9 [get_ports {c2_ddr3_dq[15]}] #bd1_eb1_DQ01_D7
set_property  PACKAGE_PIN B9 [get_ports {c2_ddr3_dm[1]}] #bd1_eb1_DQ01_DM
set_property  PACKAGE_PIN B11 [get_ports {c2_ddr3_dqs_p[1]}] #bd1_eb1_DQ01_DQS
set_property  PACKAGE_PIN B10 [get_ports {c2_ddr3_dqs_n[1]}] #bd1_eb1_DQ01_DQSn
set_property  PACKAGE_PIN E11 [get_ports {c2_ddr3_dq[16]}] #bd1_eb1_DQ02_D0
set_property  PACKAGE_PIN D11 [get_ports {c2_ddr3_dq[17]}] #bd1_eb1_DQ02_D1
set_property  PACKAGE_PIN E10 [get_ports {c2_ddr3_dq[18]}] #bd1_eb1_DQ02_D2
set_property  PACKAGE_PIN D10 [get_ports {c2_ddr3_dq[19]}] #bd1_eb1_DQ02_D3
set_property  PACKAGE_PIN G11 [get_ports {c2_ddr3_dq[20]}] #bd1_eb1_DQ02_D4
set_property  PACKAGE_PIN H12 [get_ports {c2_ddr3_dq[21]}] #bd1_eb1_DQ02_D5
set_property  PACKAGE_PIN G12 [get_ports {c2_ddr3_dq[22]}] #bd1_eb1_DQ02_D6
set_property  PACKAGE_PIN G10 [get_ports {c2_ddr3_dq[23]}] #bd1_eb1_DQ02_D7
set_property  PACKAGE_PIN H11 [get_ports {c2_ddr3_dm[2]}] #bd1_eb1_DQ02_DM
set_property  PACKAGE_PIN F12 [get_ports {c2_ddr3_dqs_p[2]}] #bd1_eb1_DQ02_DQS
set_property  PACKAGE_PIN E12 [get_ports {c2_ddr3_dqs_n[2]}] #bd1_eb1_DQ02_DQSn
set_property  PACKAGE_PIN K10 [get_ports {c2_ddr3_dq[24]}] #bd1_eb1_DQ03_D0
set_property  PACKAGE_PIN J10 [get_ports {c2_ddr3_dq[25]}] #bd1_eb1_DQ03_D1
set_property  PACKAGE_PIN K11 [get_ports {c2_ddr3_dq[26]}] #bd1_eb1_DQ03_D2
set_property  PACKAGE_PIN J11 [get_ports {c2_ddr3_dq[27]}] #bd1_eb1_DQ03_D3
set_property  PACKAGE_PIN G9 [get_ports {c2_ddr3_dq[28]}] #bd1_eb1_DQ03_D4
set_property  PACKAGE_PIN F9 [get_ports {c2_ddr3_dq[29]}] #bd1_eb1_DQ03_D5
set_property  PACKAGE_PIN J9 [get_ports {c2_ddr3_dq[30]}] #bd1_eb1_DQ03_D6
set_property  PACKAGE_PIN H9 [get_ports {c2_ddr3_dq[31]}] #bd1_eb1_DQ03_D7
set_property  PACKAGE_PIN J13 [get_ports {c2_ddr3_dm[3]}] #bd1_eb1_DQ03_DM
set_property  PACKAGE_PIN L12 [get_ports {c2_ddr3_dqs_p[3]}] #bd1_eb1_DQ03_DQS
set_property  PACKAGE_PIN K12 [get_ports {c2_ddr3_dqs_n[3]}] #bd1_eb1_DQ03_DQSn
set_property  PACKAGE_PIN K17 [get_ports {c2_ddr3_dq[32]}] #bd1_eb1_DQ04_D0
set_property  PACKAGE_PIN M20 [get_ports {c2_ddr3_dq[33]}] #bd1_eb1_DQ04_D1
set_property  PACKAGE_PIN L20 [get_ports {c2_ddr3_dq[34]}] #bd1_eb1_DQ04_D2
set_property  PACKAGE_PIN J19 [get_ports {c2_ddr3_dq[35]}] #bd1_eb1_DQ04_D3
set_property  PACKAGE_PIN H19 [get_ports {c2_ddr3_dq[36]}] #bd1_eb1_DQ04_D4
set_property  PACKAGE_PIN L18 [get_ports {c2_ddr3_dq[37]}] #bd1_eb1_DQ04_D5
set_property  PACKAGE_PIN K18 [get_ports {c2_ddr3_dq[38]}] #bd1_eb1_DQ04_D6
set_property  PACKAGE_PIN M19 [get_ports {c2_ddr3_dq[39]}] #bd1_eb1_DQ04_D7
set_property  PACKAGE_PIN L17 [get_ports {c2_ddr3_dm[4]}] #bd1_eb1_DQ04_DM
set_property  PACKAGE_PIN J18 [get_ports {c2_ddr3_dqs_p[4]}] #bd1_eb1_DQ04_DQS
set_property  PACKAGE_PIN H18 [get_ports {c2_ddr3_dqs_n[4]}] #bd1_eb1_DQ04_DQSn
set_property  PACKAGE_PIN A18 [get_ports {c2_ddr3_dq[40]}] #bd1_eb1_DQ05_D0
set_property  PACKAGE_PIN B20 [get_ports {c2_ddr3_dq[41]}] #bd1_eb1_DQ05_D1
set_property  PACKAGE_PIN A20 [get_ports {c2_ddr3_dq[42]}] #bd1_eb1_DQ05_D2
set_property  PACKAGE_PIN C21 [get_ports {c2_ddr3_dq[43]}] #bd1_eb1_DQ05_D3
set_property  PACKAGE_PIN B21 [get_ports {c2_ddr3_dq[44]}] #bd1_eb1_DQ05_D4
set_property  PACKAGE_PIN D18 [get_ports {c2_ddr3_dq[45]}] #bd1_eb1_DQ05_D5
set_property  PACKAGE_PIN C18 [get_ports {c2_ddr3_dq[46]}] #bd1_eb1_DQ05_D6
set_property  PACKAGE_PIN D20 [get_ports {c2_ddr3_dq[47]}] #bd1_eb1_DQ05_D7
set_property  PACKAGE_PIN A19 [get_ports {c2_ddr3_dm[5]}] #bd1_eb1_DQ05_DM
set_property  PACKAGE_PIN C19 [get_ports {c2_ddr3_dqs_p[5]}] #bd1_eb1_DQ05_DQS
set_property  PACKAGE_PIN B19 [get_ports {c2_ddr3_dqs_n[5]}] #bd1_eb1_DQ05_DQSn
set_property  PACKAGE_PIN G19 [get_ports {c2_ddr3_dq[48]}] #bd1_eb1_DQ06_D0
set_property  PACKAGE_PIN F19 [get_ports {c2_ddr3_dq[49]}] #bd1_eb1_DQ06_D1
set_property  PACKAGE_PIN F20 [get_ports {c2_ddr3_dq[50]}] #bd1_eb1_DQ06_D2
set_property  PACKAGE_PIN E20 [get_ports {c2_ddr3_dq[51]}] #bd1_eb1_DQ06_D3
set_property  PACKAGE_PIN E18 [get_ports {c2_ddr3_dq[52]}] #bd1_eb1_DQ06_D4
set_property  PACKAGE_PIN K20 [get_ports {c2_ddr3_dq[53]}] #bd1_eb1_DQ06_D5
set_property  PACKAGE_PIN J20 [get_ports {c2_ddr3_dq[54]}] #bd1_eb1_DQ06_D6
set_property  PACKAGE_PIN G21 [get_ports {c2_ddr3_dq[55]}] #bd1_eb1_DQ06_D7
set_property  PACKAGE_PIN F18 [get_ports {c2_ddr3_dm[6]}] #bd1_eb1_DQ06_DM
set_property  PACKAGE_PIN E21 [get_ports {c2_ddr3_dqs_p[6]}] #bd1_eb1_DQ06_DQS
set_property  PACKAGE_PIN D21 [get_ports {c2_ddr3_dqs_n[6]}] #bd1_eb1_DQ06_DQSn
set_property  PACKAGE_PIN T18 [get_ports {c2_ddr3_dq[56]}] #bd1_eb1_DQ07_D0
set_property  PACKAGE_PIN R18 [get_ports {c2_ddr3_dq[57]}] #bd1_eb1_DQ07_D1
set_property  PACKAGE_PIN T17 [get_ports {c2_ddr3_dq[58]}] #bd1_eb1_DQ07_D2
set_property  PACKAGE_PIN R17 [get_ports {c2_ddr3_dq[59]}] #bd1_eb1_DQ07_D3
set_property  PACKAGE_PIN P18 [get_ports {c2_ddr3_dq[60]}] #bd1_eb1_DQ07_D4
set_property  PACKAGE_PIN N18 [get_ports {c2_ddr3_dq[61]}] #bd1_eb1_DQ07_D5
set_property  PACKAGE_PIN R20 [get_ports {c2_ddr3_dq[62]}] #bd1_eb1_DQ07_D6
set_property  PACKAGE_PIN P20 [get_ports {c2_ddr3_dq[63]}] #bd1_eb1_DQ07_D7
set_property  PACKAGE_PIN P19 [get_ports {c2_ddr3_dm[7]}] #bd1_eb1_DQ07_DM
set_property  PACKAGE_PIN T20 [get_ports {c2_ddr3_dqs_p[7]}] #bd1_eb1_DQ07_DQS
set_property  PACKAGE_PIN T19 [get_ports {c2_ddr3_dqs_n[7]}] #bd1_eb1_DQ07_DQSn
set_property  PACKAGE_PIN R16 [get_ports {c2_calib_complete}] #bd1_eb1_LED01
set_property  PACKAGE_PIN M14 [get_ports {c2_diagnostic_led}] #bd1_eb1_LED02
set_property  PACKAGE_PIN E17 [get_ports {c2_ddr3_odt}] #bd1_eb1_ODT
set_property  PACKAGE_PIN C14 [get_ports {c2_ddr3_ras_n}] #bd1_eb1_RASn
set_property  PACKAGE_PIN F10 [get_ports {c2_ddr3_reset_n}] #bd1_eb1_RESETn
set_property  PACKAGE_PIN D15 [get_ports {c2_ddr3_we_n}] #bd1_eb1_WEn

# pins which are connected to motherboard connector BD2 
# and connector BA1 on x-board EB-PDS-GBITETHERNET-R1 
set_property  PACKAGE_PIN Y32 [get_ports {bd2_eb1_ETH1_CLK_TO_MAC}] #UNCONNECTED?
set_property  PACKAGE_PIN W33 [get_ports {erx_col}] #bd2_eb1_ETH1_COL_CLK_MAC_FREQ}]
set_property  PACKAGE_PIN W34 [get_ports {erx_crs}] #bd2_eb1_ETH1_CRS_RGMII_SEL0}]
set_property  PACKAGE_PIN U40 [get_ports {bd2_eb1_ETH1_GTX_CLK_TCK}]
set_property  PACKAGE_PIN V32 [get_ports {emdc}] #bd2_eb1_ETH1_MDC}]
set_property  PACKAGE_PIN V31 [get_ports {emdio}] #bd2_eb1_ETH1_MDIO}]
set_property  PACKAGE_PIN W39 [get_ports {bd2_eb1_ETH1_NINTERRUPT}] #UNCONNECTED?
set_property  PACKAGE_PIN V42 [get_ports {reset_o2}] #bd2_eb1_ETH1_NRESET}]
set_property  PACKAGE_PIN Y40 [get_ports {erx_clk}] #bd2_eb1_ETH1_RX_CLK}]
set_property  PACKAGE_PIN W38 [get_ports {erx_dv}] #bd2_eb1_ETH1_RX_DV_RCK}]
set_property  PACKAGE_PIN U39 [get_ports {erx_er}] #bd2_eb1_ETH1_RX_ER_RXDV_ER}]
set_property  PACKAGE_PIN Y43 [get_ports {erxd[0]}] #bd2_eb1_ETH1_RXD0_RX0}]
set_property  PACKAGE_PIN Y42 [get_ports {erxd[1]}] #bd2_eb1_ETH1_RXD1_RX1}]
set_property  PACKAGE_PIN Y38 [get_ports {erxd[2]}] #bd2_eb1_ETH1_RXD2_RX2}]
set_property  PACKAGE_PIN Y37 [get_ports {erxd[3]}] #bd2_eb1_ETH1_RXD3_RX3}]
set_property  PACKAGE_PIN U42 [get_ports {bd2_eb1_ETH1_RXD4}] #UNCONNECTED?
set_property  PACKAGE_PIN U41 [get_ports {bd2_eb1_ETH1_RXD5}] #UNCONNECTED?
set_property  PACKAGE_PIN W44 [get_ports {bd2_eb1_ETH1_RXD6}] #UNCONNECTED?
set_property  PACKAGE_PIN W43 [get_ports {bd2_eb1_ETH1_RXD7}] #UNCONNECTED?
set_property  PACKAGE_PIN W30 [get_ports {etx_clk}] #bd2_eb1_ETH1_TX_CLK_RGMII_SEL1}]
set_property  PACKAGE_PIN V37 [get_ports {etx_en}] #bd2_eb1_ETH1_TX_EN_TXEN_ER}]
set_property  PACKAGE_PIN V36 [get_ports {etx_er}] #bd2_eb1_ETH1_TX_ER}]
set_property  PACKAGE_PIN V44 [get_ports {etxd[0]}] #bd2_eb1_ETH1_TXD0_TX0}]
set_property  PACKAGE_PIN V43 [get_ports {etxd[1]}] #bd2_eb1_ETH1_TXD1_TX1}]
set_property  PACKAGE_PIN Y36 [get_ports {etxd[2]}] #bd2_eb1_ETH1_TXD2_TX2}]
set_property  PACKAGE_PIN Y35 [get_ports {etxd[3]}] #bd2_eb1_ETH1_TXD3_TX3}]
set_property  PACKAGE_PIN W36 [get_ports {bd2_eb1_ETH1_TXD4}] #UNCONNECTED?
set_property  PACKAGE_PIN W35 [get_ports {bd2_eb1_ETH1_TXD5}] #UNCONNECTED?
set_property  PACKAGE_PIN U31 [get_ports {bd2_eb1_ETH1_TXD6}] #UNCONNECTED?
set_property  PACKAGE_PIN U30 [get_ports {bd2_eb1_ETH1_TXD7}] #UNCONNECTED?
set_property  PACKAGE_PIN Y30 [get_ports {bd2_eb1_ETH2_CLK_TO_MAC}] # ALL ETH2 UNCONNECTED?
set_property  PACKAGE_PIN W31 [get_ports {bd2_eb1_ETH2_NINTERRUPT}]
set_property  PACKAGE_PIN V29 [get_ports {bd2_eb1_ETH2_NRESET}]
set_property  PACKAGE_PIN Y41 [get_ports {bd2_eb1_ETH2_RX_CLK}]
set_property  PACKAGE_PIN V41 [get_ports {bd2_eb1_ETH2_RX_DV_RCK}]
set_property  PACKAGE_PIN V34 [get_ports {bd2_eb1_ETH2_RXD0_RX0}]
set_property  PACKAGE_PIN V33 [get_ports {bd2_eb1_ETH2_RXD1_RX1}]
set_property  PACKAGE_PIN U37 [get_ports {bd2_eb1_ETH2_RXD2_RX2}]
set_property  PACKAGE_PIN U36 [get_ports {bd2_eb1_ETH2_RXD3_RX3}]
set_property  PACKAGE_PIN U35 [get_ports {bd2_eb1_ETH2_RXD4}]
set_property  PACKAGE_PIN U34 [get_ports {bd2_eb1_ETH2_RXD5}]
set_property  PACKAGE_PIN V39 [get_ports {bd2_eb1_ETH2_RXD6}]
set_property  PACKAGE_PIN V38 [get_ports {bd2_eb1_ETH2_RXD7}]
set_property  PACKAGE_PIN W29 [get_ports {bd2_eb1_ETH2_TX_CLK_RGMII_SEL1}]

# pins which are connected to motherboard connector TC1 
# and connector BA2 on x-board IC-PDS-CABLE-R1 
set_property  PACKAGE_PIN J40 [get_ports {mb1_TC1_CLKIO_N_0_mb1_TA3_CLKIO_N_7}]
set_property  PACKAGE_PIN L42 [get_ports {mb1_TC1_CLKIO_N_1_mb1_TA3_CLKIO_N_6}]
set_property  PACKAGE_PIN C39 [get_ports {mb1_TC1_CLKIO_N_2_mb1_TA3_CLKIO_N_4}]
set_property  PACKAGE_PIN C41 [get_ports {mb1_TC1_CLKIO_N_3_mb1_TA3_CLKIO_N_3}]
set_property  PACKAGE_PIN H41 [get_ports {mb1_TC1_CLKIO_N_4_mb1_TA3_CLKIO_N_2}]
set_property  PACKAGE_PIN K42 [get_ports {mb1_TC1_CLKIO_N_5_mb1_TA3_IO_010_N_05}]
set_property  PACKAGE_PIN D38 [get_ports {mb1_TC1_CLKIO_N_6_mb1_TA3_CLKIO_N_1}]
set_property  PACKAGE_PIN D40 [get_ports {mb1_TC1_CLKIO_N_7_mb1_TA3_CLKIO_N_0}]
set_property  PACKAGE_PIN K40 [get_ports {mb1_TC1_CLKIO_P_0_mb1_TA3_CLKIO_P_7}]
set_property  PACKAGE_PIN M42 [get_ports {mb1_TC1_CLKIO_P_1_mb1_TA3_CLKIO_P_6}]
set_property  PACKAGE_PIN C38 [get_ports {mb1_TC1_CLKIO_P_2_mb1_TA3_CLKIO_P_4}]
set_property  PACKAGE_PIN D41 [get_ports {mb1_TC1_CLKIO_P_3_mb1_TA3_CLKIO_P_3}]
set_property  PACKAGE_PIN J41 [get_ports {mb1_TC1_CLKIO_P_4_mb1_TA3_CLKIO_P_2}]
set_property  PACKAGE_PIN K41 [get_ports {mb1_TC1_CLKIO_P_5_mb1_TA3_IO_011_P_05}]
set_property  PACKAGE_PIN E38 [get_ports {mb1_TC1_CLKIO_P_6_mb1_TA3_CLKIO_P_1}]
set_property  PACKAGE_PIN D39 [get_ports {mb1_TC1_CLKIO_P_7_mb1_TA3_CLKIO_P_0}]
set_property  PACKAGE_PIN C34 [get_ports {mb1_TC1_IO_004_N_02_mb1_TA3_IO_006_N_03}]
set_property  PACKAGE_PIN D34 [get_ports {mb1_TC1_IO_005_P_02_mb1_TA3_IO_007_P_03}]
set_property  PACKAGE_PIN A34 [get_ports {mb1_TC1_IO_006_N_03_mb1_TA3_IO_004_N_02}]
set_property  PACKAGE_PIN B34 [get_ports {mb1_TC1_IO_007_P_03_mb1_TA3_IO_005_P_02}]
set_property  PACKAGE_PIN E35 [get_ports {mb1_TC1_IO_008_N_04_mb1_TA3_IO_022_N_11}]
set_property  PACKAGE_PIN F35 [get_ports {mb1_TC1_IO_009_P_04_mb1_TA3_IO_023_P_11}]
set_property  PACKAGE_PIN D36 [get_ports {mb1_TC1_IO_010_N_05_mb1_TA3_CLKIO_N_5}]
set_property  PACKAGE_PIN D35 [get_ports {mb1_TC1_IO_011_P_05_mb1_TA3_CLKIO_P_5}]
set_property  PACKAGE_PIN E40 [get_ports {mb1_TC1_IO_012_N_06_mb1_TA3_IO_012_N_06}]
set_property  PACKAGE_PIN F40 [get_ports {mb1_TC1_IO_013_P_06_mb1_TA3_IO_013_P_06}]
set_property  PACKAGE_PIN E42 [get_ports {mb1_TC1_IO_014_N_07_mb1_TA3_IO_016_N_08}]
set_property  PACKAGE_PIN E41 [get_ports {mb1_TC1_IO_015_P_07_mb1_TA3_IO_017_P_08}]
set_property  PACKAGE_PIN C44 [get_ports {mb1_TC1_IO_016_N_08_mb1_TA3_IO_014_N_07}]
set_property  PACKAGE_PIN C43 [get_ports {mb1_TC1_IO_017_P_08_mb1_TA3_IO_015_P_07}]
set_property  PACKAGE_PIN E43 [get_ports {mb1_TC1_IO_018_N_09_mb1_TA3_IO_032_N_16}]
set_property  PACKAGE_PIN F42 [get_ports {mb1_TC1_IO_019_P_09_mb1_TA3_IO_033_P_16}]
set_property  PACKAGE_PIN F44 [get_ports {mb1_TC1_IO_020_N_10_mb1_TA3_IO_030_N_15}]
set_property  PACKAGE_PIN F43 [get_ports {mb1_TC1_IO_021_P_10_mb1_TA3_IO_031_P_15}]
set_property  PACKAGE_PIN D44 [get_ports {mb1_TC1_IO_022_N_11_mb1_TA3_IO_008_N_04}]
set_property  PACKAGE_PIN D43 [get_ports {mb1_TC1_IO_023_P_11_mb1_TA3_IO_009_P_04}]
set_property  PACKAGE_PIN P36 [get_ports {mb1_TC1_IO_024_N_12_mb1_TA3_IO_026_N_13}]
set_property  PACKAGE_PIN P35 [get_ports {mb1_TC1_IO_025_P_12_mb1_TA3_IO_027_P_13}]
set_property  PACKAGE_PIN N37 [get_ports {mb1_TC1_IO_026_N_13_mb1_TA3_IO_024_N_12}]
set_property  PACKAGE_PIN N36 [get_ports {mb1_TC1_IO_027_P_13_mb1_TA3_IO_025_P_12}]
set_property  PACKAGE_PIN R37 [get_ports {mb1_TC1_IO_028_N_14_mb1_TA3_IO_042_N_21}]
set_property  PACKAGE_PIN R36 [get_ports {mb1_TC1_IO_029_P_14_mb1_TA3_IO_043_P_21}]
set_property  PACKAGE_PIN N39 [get_ports {mb1_TC1_IO_030_N_15_mb1_TA3_IO_020_N_10}]
set_property  PACKAGE_PIN N38 [get_ports {mb1_TC1_IO_031_P_15_mb1_TA3_IO_021_P_10}]
set_property  PACKAGE_PIN M40 [get_ports {mb1_TC1_IO_032_N_16_mb1_TA3_IO_018_N_09}]
set_property  PACKAGE_PIN M39 [get_ports {mb1_TC1_IO_033_P_16_mb1_TA3_IO_019_P_09}]
set_property  PACKAGE_PIN R35 [get_ports {mb1_TC1_IO_034_N_17_mb1_TA3_IO_036_N_18}]
set_property  PACKAGE_PIN T35 [get_ports {mb1_TC1_IO_035_P_17_mb1_TA3_IO_037_P_18}]
set_property  PACKAGE_PIN T40 [get_ports {mb1_TC1_IO_036_N_18_mb1_TA3_IO_034_N_17}]
set_property  PACKAGE_PIN T39 [get_ports {mb1_TC1_IO_037_P_18_mb1_TA3_IO_035_P_17}]
set_property  PACKAGE_PIN M41 [get_ports {mb1_TC1_IO_038_N_19_mb1_TA3_IO_052_N_26}]
set_property  PACKAGE_PIN N41 [get_ports {mb1_TC1_IO_039_P_19_mb1_TA3_IO_053_P_26}]
set_property  PACKAGE_PIN N42 [get_ports {mb1_TC1_IO_040_N_20_mb1_TA3_IO_050_N_25}]
set_property  PACKAGE_PIN P41 [get_ports {mb1_TC1_IO_041_P_20_mb1_TA3_IO_051_P_25}]
set_property  PACKAGE_PIN P40 [get_ports {mb1_TC1_IO_042_N_21_mb1_TA3_IO_028_N_14}]
set_property  PACKAGE_PIN P39 [get_ports {mb1_TC1_IO_043_P_21_mb1_TA3_IO_029_P_14}]
set_property  PACKAGE_PIN P38 [get_ports {mb1_TC1_IO_044_N_22_mb1_TA3_IO_046_N_23}]
set_property  PACKAGE_PIN R38 [get_ports {mb1_TC1_IO_045_P_22_mb1_TA3_IO_047_P_23}]
set_property  PACKAGE_PIN T38 [get_ports {mb1_TC1_IO_046_N_23_mb1_TA3_IO_044_N_22}]
set_property  PACKAGE_PIN T37 [get_ports {mb1_TC1_IO_047_P_23_mb1_TA3_IO_045_P_22}]
set_property  PACKAGE_PIN R41 [get_ports {mb1_TC1_IO_048_N_24_mb1_TA3_IO_062_N_31}]
set_property  PACKAGE_PIN R40 [get_ports {mb1_TC1_IO_049_P_24_mb1_TA3_IO_063_P_31}]
set_property  PACKAGE_PIN R42 [get_ports {mb1_TC1_IO_050_N_25_mb1_TA3_IO_040_N_20}]
set_property  PACKAGE_PIN T42 [get_ports {mb1_TC1_IO_051_P_25_mb1_TA3_IO_041_P_20}]
set_property  PACKAGE_PIN R43 [get_ports {mb1_TC1_IO_052_N_26_mb1_TA3_IO_038_N_19}]
set_property  PACKAGE_PIN T43 [get_ports {mb1_TC1_IO_053_P_26_mb1_TA3_IO_039_P_19}]
set_property  PACKAGE_PIN T44 [get_ports {mb1_TC1_IO_054_N_27_mb1_TA3_IO_056_N_28}]
set_property  PACKAGE_PIN U44 [get_ports {mb1_TC1_IO_055_P_27_mb1_TA3_IO_057_P_28}]
set_property  PACKAGE_PIN N44 [get_ports {mb1_TC1_IO_056_N_28_mb1_TA3_IO_054_N_27}]
set_property  PACKAGE_PIN P44 [get_ports {mb1_TC1_IO_057_P_28_mb1_TA3_IO_055_P_27}]
set_property  PACKAGE_PIN N43 [get_ports {mb1_TC1_IO_058_N_29_mb1_TA3_IO_072_N_36}]
set_property  PACKAGE_PIN P43 [get_ports {mb1_TC1_IO_059_P_29_mb1_TA3_IO_073_P_36}]
set_property  PACKAGE_PIN T34 [get_ports {mb1_TC1_IO_060_N_30_mb1_TA3_IO_070_N_35}]
set_property  PACKAGE_PIN T33 [get_ports {mb1_TC1_IO_061_P_30_mb1_TA3_IO_071_P_35}]
set_property  PACKAGE_PIN P31 [get_ports {mb1_TC1_IO_062_N_31_mb1_TA3_IO_048_N_24}]
set_property  PACKAGE_PIN P30 [get_ports {mb1_TC1_IO_063_P_31_mb1_TA3_IO_049_P_24}]
set_property  PACKAGE_PIN T30 [get_ports {mb1_TC1_IO_064_N_32_mb1_TA3_IO_066_N_33}]
set_property  PACKAGE_PIN T29 [get_ports {mb1_TC1_IO_065_P_32_mb1_TA3_IO_067_P_33}]
set_property  PACKAGE_PIN R33 [get_ports {mb1_TC1_IO_066_N_33_mb1_TA3_IO_064_N_32}]
set_property  PACKAGE_PIN R32 [get_ports {mb1_TC1_IO_067_P_33_mb1_TA3_IO_065_P_32}]
set_property  PACKAGE_PIN P34 [get_ports {mb1_TC1_IO_068_N_34_mb1_TA3_IO_082_N_41}]
set_property  PACKAGE_PIN P33 [get_ports {mb1_TC1_IO_069_P_34_mb1_TA3_IO_083_P_41}]
set_property  PACKAGE_PIN R31 [get_ports {mb1_TC1_IO_070_N_35_mb1_TA3_IO_060_N_30}]
set_property  PACKAGE_PIN R30 [get_ports {mb1_TC1_IO_071_P_35_mb1_TA3_IO_061_P_30}]
set_property  PACKAGE_PIN E37 [get_ports {mb1_TC1_IO_072_N_36_mb1_TA3_IO_058_N_29}]
set_property  PACKAGE_PIN E36 [get_ports {mb1_TC1_IO_073_P_36_mb1_TA3_IO_059_P_29}]
set_property  PACKAGE_PIN A38 [get_ports {mb1_TC1_IO_074_N_37_mb1_TA3_IO_076_N_38}]
set_property  PACKAGE_PIN A37 [get_ports {mb1_TC1_IO_075_P_37_mb1_TA3_IO_077_P_38}]
set_property  PACKAGE_PIN G44 [get_ports {mb1_TC1_IO_076_N_38_mb1_TA3_IO_074_N_37}]
set_property  PACKAGE_PIN H44 [get_ports {mb1_TC1_IO_077_P_38_mb1_TA3_IO_075_P_37}]
set_property  PACKAGE_PIN B37 [get_ports {mb1_TC1_IO_078_N_39_mb1_TA3_IO_092_N_46}]
set_property  PACKAGE_PIN C37 [get_ports {mb1_TC1_IO_079_P_39_mb1_TA3_IO_093_P_46}]
set_property  PACKAGE_PIN L44 [get_ports {mb1_TC1_IO_080_N_40_mb1_TA3_IO_090_N_45}]
set_property  PACKAGE_PIN M44 [get_ports {mb1_TC1_IO_081_P_40_mb1_TA3_IO_091_P_45}]
set_property  PACKAGE_PIN F39 [get_ports {mb1_TC1_IO_082_N_41_mb1_TA3_IO_068_N_34}]
set_property  PACKAGE_PIN F38 [get_ports {mb1_TC1_IO_083_P_41_mb1_TA3_IO_069_P_34}]
set_property  PACKAGE_PIN A40 [get_ports {mb1_TC1_IO_084_N_42_mb1_TA3_IO_086_N_43}]
set_property  PACKAGE_PIN A39 [get_ports {mb1_TC1_IO_085_P_42_mb1_TA3_IO_087_P_43}]
set_property  PACKAGE_PIN B40 [get_ports {mb1_TC1_IO_086_N_43_mb1_TA3_IO_084_N_42}]
set_property  PACKAGE_PIN B39 [get_ports {mb1_TC1_IO_087_P_43_mb1_TA3_IO_085_P_42}]
set_property  PACKAGE_PIN J44 [get_ports {mb1_TC1_IO_088_N_44_mb1_TA3_IO_102_N_51}]
set_property  PACKAGE_PIN J43 [get_ports {mb1_TC1_IO_089_P_44_mb1_TA3_IO_103_P_51}]
set_property  PACKAGE_PIN B42 [get_ports {mb1_TC1_IO_090_N_45_mb1_TA3_IO_080_N_40}]
set_property  PACKAGE_PIN C42 [get_ports {mb1_TC1_IO_091_P_45_mb1_TA3_IO_081_P_40}]
set_property  PACKAGE_PIN K43 [get_ports {mb1_TC1_IO_092_N_46_mb1_TA3_IO_078_N_39}]
set_property  PACKAGE_PIN L43 [get_ports {mb1_TC1_IO_093_P_46_mb1_TA3_IO_079_P_39}]
set_property  PACKAGE_PIN A42 [get_ports {mb1_TC1_IO_094_N_47_mb1_TA3_IO_096_N_48}]
set_property  PACKAGE_PIN B41 [get_ports {mb1_TC1_IO_095_P_47_mb1_TA3_IO_097_P_48}]
set_property  PACKAGE_PIN G40 [get_ports {mb1_TC1_IO_096_N_48_mb1_TA3_IO_094_N_47}]
set_property  PACKAGE_PIN G39 [get_ports {mb1_TC1_IO_097_P_48_mb1_TA3_IO_095_P_47}]
set_property  PACKAGE_PIN G35 [get_ports {mb1_TC1_IO_098_N_49_mb1_TA3_IO_112_N_56}]
set_property  PACKAGE_PIN G34 [get_ports {mb1_TC1_IO_099_P_49_mb1_TA3_IO_113_P_56}]
set_property  PACKAGE_PIN G37 [get_ports {mb1_TC1_IO_100_N_50_mb1_TA3_IO_110_N_55}]
set_property  PACKAGE_PIN G36 [get_ports {mb1_TC1_IO_101_P_50_mb1_TA3_IO_111_P_55}]
set_property  PACKAGE_PIN H38 [get_ports {mb1_TC1_IO_102_N_51_mb1_TA3_IO_088_N_44}]
set_property  PACKAGE_PIN J38 [get_ports {mb1_TC1_IO_103_P_51_mb1_TA3_IO_089_P_44}]
set_property  PACKAGE_PIN H37 [get_ports {mb1_TC1_IO_104_N_52_mb1_TA3_IO_106_N_53}]
set_property  PACKAGE_PIN H36 [get_ports {mb1_TC1_IO_105_P_52_mb1_TA3_IO_107_P_53}]
set_property  PACKAGE_PIN H39 [get_ports {mb1_TC1_IO_106_N_53_mb1_TA3_IO_104_N_52}]
set_property  PACKAGE_PIN J39 [get_ports {mb1_TC1_IO_107_P_53_mb1_TA3_IO_105_P_52}]
set_property  PACKAGE_PIN G42 [get_ports {mb1_TC1_IO_108_N_54_mb1_TA3_IO_122_N_61}]
set_property  PACKAGE_PIN G41 [get_ports {mb1_TC1_IO_109_P_54_mb1_TA3_IO_123_P_61}]
set_property  PACKAGE_PIN L40 [get_ports {mb1_TC1_IO_110_N_55_mb1_TA3_IO_100_N_50}]
set_property  PACKAGE_PIN L39 [get_ports {mb1_TC1_IO_111_P_55_mb1_TA3_IO_101_P_50}]
set_property  PACKAGE_PIN H43 [get_ports {mb1_TC1_IO_112_N_56_mb1_TA3_IO_098_N_49}]
set_property  PACKAGE_PIN H42 [get_ports {mb1_TC1_IO_113_P_56_mb1_TA3_IO_099_P_49}]
set_property  PACKAGE_PIN K38 [get_ports {mb1_TC1_IO_114_N_57_mb1_TA3_IO_116_N_58}]
set_property  PACKAGE_PIN L38 [get_ports {mb1_TC1_IO_115_P_57_mb1_TA3_IO_117_P_58}]
set_property  PACKAGE_PIN J36 [get_ports {mb1_TC1_IO_116_N_58_mb1_TA3_IO_114_N_57}]
set_property  PACKAGE_PIN K36 [get_ports {mb1_TC1_IO_117_P_58_mb1_TA3_IO_115_P_57}]
set_property  PACKAGE_PIN J35 [get_ports {mb1_TC1_IO_120_N_60_mb1_TA3_IO_130}]
set_property  PACKAGE_PIN J34 [get_ports {mb1_TC1_IO_121_P_60_mb1_TA3_IO_131}]
set_property  PACKAGE_PIN K37 [get_ports {mb1_TC1_IO_122_N_61_mb1_TA3_IO_108_N_54}]
set_property  PACKAGE_PIN L37 [get_ports {mb1_TC1_IO_123_P_61_mb1_TA3_IO_109_P_54}]
set_property  PACKAGE_PIN M35 [get_ports {mb1_TC1_IO_124_N_62_mb1_TA3_IO_126_N_63}]
set_property  PACKAGE_PIN M34 [get_ports {mb1_TC1_IO_125_P_62_mb1_TA3_IO_127_P_63}]
set_property  PACKAGE_PIN M37 [get_ports {mb1_TC1_IO_126_N_63_mb1_TA3_IO_124_N_62}]
set_property  PACKAGE_PIN M36 [get_ports {mb1_TC1_IO_127_P_63_mb1_TA3_IO_125_P_62}]
set_property  PACKAGE_PIN N34 [get_ports {mb1_TC1_IO_130_mb1_TA3_IO_120_N_60}]
set_property  PACKAGE_PIN T32 [get_ports {mb1_TC1_IO_131_mb1_TA3_IO_121_P_60}]

# pins which are connected to motherboard connector TC2 
# and connector BA2 on x-board IC-PDS-CABLE-R1 
set_property  PACKAGE_PIN AU27 [get_ports {mb1_TC2_CLKIO_N_0_mb1_TA4_CLKIO_N_7}]
set_property  PACKAGE_PIN AR27 [get_ports {mb1_TC2_CLKIO_N_1_mb1_TA4_CLKIO_N_6}]
set_property  PACKAGE_PIN AU31 [get_ports {mb1_TC2_CLKIO_N_2_mb1_TA4_CLKIO_N_4}]
set_property  PACKAGE_PIN AR31 [get_ports {mb1_TC2_CLKIO_N_3_mb1_TA4_CLKIO_N_3}]
set_property  PACKAGE_PIN AV28 [get_ports {mb1_TC2_CLKIO_N_4_mb1_TA4_CLKIO_N_2}]
set_property  PACKAGE_PIN AT28 [get_ports {mb1_TC2_CLKIO_N_5_mb1_TA4_IO_010_N_05}]
set_property  PACKAGE_PIN AV32 [get_ports {mb1_TC2_CLKIO_N_6_mb1_TA4_CLKIO_N_1}]
set_property  PACKAGE_PIN AT32 [get_ports {mb1_TC2_CLKIO_N_7_mb1_TA4_CLKIO_N_0}]
set_property  PACKAGE_PIN AU26 [get_ports {mb1_TC2_CLKIO_P_0_mb1_TA4_CLKIO_P_7}]
set_property  PACKAGE_PIN AR26 [get_ports {mb1_TC2_CLKIO_P_1_mb1_TA4_CLKIO_P_6}]
set_property  PACKAGE_PIN AU30 [get_ports {mb1_TC2_CLKIO_P_2_mb1_TA4_CLKIO_P_4}]
set_property  PACKAGE_PIN AP31 [get_ports {mb1_TC2_CLKIO_P_3_mb1_TA4_CLKIO_P_3}]
set_property  PACKAGE_PIN AV27 [get_ports {mb1_TC2_CLKIO_P_4_mb1_TA4_CLKIO_P_2}]
set_property  PACKAGE_PIN AT27 [get_ports {mb1_TC2_CLKIO_P_5_mb1_TA4_IO_011_P_05}]
set_property  PACKAGE_PIN AU32 [get_ports {mb1_TC2_CLKIO_P_6_mb1_TA4_CLKIO_P_1}]
set_property  PACKAGE_PIN AR32 [get_ports {mb1_TC2_CLKIO_P_7_mb1_TA4_CLKIO_P_0}]
set_property  PACKAGE_PIN BC32 [get_ports {mb1_TC2_IO_004_N_02_mb1_TA4_IO_006_N_03}]
set_property  PACKAGE_PIN BC31 [get_ports {mb1_TC2_IO_005_P_02_mb1_TA4_IO_007_P_03}]
set_property  PACKAGE_PIN BD31 [get_ports {mb1_TC2_IO_006_N_03_mb1_TA4_IO_004_N_02}]
set_property  PACKAGE_PIN BD30 [get_ports {mb1_TC2_IO_007_P_03_mb1_TA4_IO_005_P_02}]
set_property  PACKAGE_PIN BB30 [get_ports {mb1_TC2_IO_008_N_04_mb1_TA4_IO_022_N_11}]
set_property  PACKAGE_PIN BA30 [get_ports {mb1_TC2_IO_009_P_04_mb1_TA4_IO_023_P_11}]
set_property  PACKAGE_PIN BB32 [get_ports {mb1_TC2_IO_010_N_05_mb1_TA4_CLKIO_N_5}]
set_property  PACKAGE_PIN BB31 [get_ports {mb1_TC2_IO_011_P_05_mb1_TA4_CLKIO_P_5}]
set_property  PACKAGE_PIN AM32 [get_ports {mb1_TC2_IO_012_N_06_mb1_TA4_IO_012_N_06}]
set_property  PACKAGE_PIN AL32 [get_ports {mb1_TC2_IO_013_P_06_mb1_TA4_IO_013_P_06}]
set_property  PACKAGE_PIN AL30 [get_ports {mb1_TC2_IO_014_N_07_mb1_TA4_IO_016_N_08}]
set_property  PACKAGE_PIN AL29 [get_ports {mb1_TC2_IO_015_P_07_mb1_TA4_IO_017_P_08}]
set_property  PACKAGE_PIN AM31 [get_ports {mb1_TC2_IO_016_N_08_mb1_TA4_IO_014_N_07}]
set_property  PACKAGE_PIN AM30 [get_ports {mb1_TC2_IO_017_P_08_mb1_TA4_IO_015_P_07}]
set_property  PACKAGE_PIN AN32 [get_ports {mb1_TC2_IO_018_N_09_mb1_TA4_IO_032_N_16}]
set_property  PACKAGE_PIN AN31 [get_ports {mb1_TC2_IO_019_P_09_mb1_TA4_IO_033_P_16}]
set_property  PACKAGE_PIN AN29 [get_ports {mb1_TC2_IO_020_N_10_mb1_TA4_IO_030_N_15}]
set_property  PACKAGE_PIN AM29 [get_ports {mb1_TC2_IO_021_P_10_mb1_TA4_IO_031_P_15}]
set_property  PACKAGE_PIN AK31 [get_ports {mb1_TC2_IO_022_N_11_mb1_TA4_IO_008_N_04}]
set_property  PACKAGE_PIN AK30 [get_ports {mb1_TC2_IO_023_P_11_mb1_TA4_IO_009_P_04}]
set_property  PACKAGE_PIN AJ24 [get_ports {mb1_TC2_IO_024_N_12_mb1_TA4_IO_026_N_13}]
set_property  PACKAGE_PIN AJ23 [get_ports {mb1_TC2_IO_025_P_12_mb1_TA4_IO_027_P_13}]
set_property  PACKAGE_PIN AM22 [get_ports {mb1_TC2_IO_026_N_13_mb1_TA4_IO_024_N_12}]
set_property  PACKAGE_PIN AL22 [get_ports {mb1_TC2_IO_027_P_13_mb1_TA4_IO_025_P_12}]
set_property  PACKAGE_PIN AK22 [get_ports {mb1_TC2_IO_028_N_14_mb1_TA4_IO_042_N_21}]
set_property  PACKAGE_PIN AK21 [get_ports {mb1_TC2_IO_029_P_14_mb1_TA4_IO_043_P_21}]
set_property  PACKAGE_PIN AL23 [get_ports {mb1_TC2_IO_030_N_15_mb1_TA4_IO_020_N_10}]
set_property  PACKAGE_PIN AK23 [get_ports {mb1_TC2_IO_031_P_15_mb1_TA4_IO_021_P_10}]
set_property  PACKAGE_PIN AM24 [get_ports {mb1_TC2_IO_032_N_16_mb1_TA4_IO_018_N_09}]
set_property  PACKAGE_PIN AL24 [get_ports {mb1_TC2_IO_033_P_16_mb1_TA4_IO_019_P_09}]
set_property  PACKAGE_PIN AN21 [get_ports {mb1_TC2_IO_034_N_17_mb1_TA4_IO_036_N_18}]
set_property  PACKAGE_PIN AM21 [get_ports {mb1_TC2_IO_035_P_17_mb1_TA4_IO_037_P_18}]
set_property  PACKAGE_PIN AW23 [get_ports {mb1_TC2_IO_036_N_18_mb1_TA4_IO_034_N_17}]
set_property  PACKAGE_PIN AV23 [get_ports {mb1_TC2_IO_037_P_18_mb1_TA4_IO_035_P_17}]
set_property  PACKAGE_PIN AY23 [get_ports {mb1_TC2_IO_038_N_19_mb1_TA4_IO_052_N_26}]
set_property  PACKAGE_PIN AY22 [get_ports {mb1_TC2_IO_039_P_19_mb1_TA4_IO_053_P_26}]
set_property  PACKAGE_PIN BA25 [get_ports {mb1_TC2_IO_040_N_20_mb1_TA4_IO_050_N_25}]
set_property  PACKAGE_PIN AY25 [get_ports {mb1_TC2_IO_041_P_20_mb1_TA4_IO_051_P_25}]
set_property  PACKAGE_PIN AU25 [get_ports {mb1_TC2_IO_042_N_21_mb1_TA4_IO_028_N_14}]
set_property  PACKAGE_PIN AU24 [get_ports {mb1_TC2_IO_043_P_21_mb1_TA4_IO_029_P_14}]
set_property  PACKAGE_PIN AW24 [get_ports {mb1_TC2_IO_044_N_22_mb1_TA4_IO_046_N_23}]
set_property  PACKAGE_PIN AV24 [get_ports {mb1_TC2_IO_045_P_22_mb1_TA4_IO_047_P_23}]
set_property  PACKAGE_PIN AV22 [get_ports {mb1_TC2_IO_046_N_23_mb1_TA4_IO_044_N_22}]
set_property  PACKAGE_PIN AU22 [get_ports {mb1_TC2_IO_047_P_23_mb1_TA4_IO_045_P_22}]
set_property  PACKAGE_PIN AT24 [get_ports {mb1_TC2_IO_048_N_24_mb1_TA4_IO_062_N_31}]
set_property  PACKAGE_PIN AT23 [get_ports {mb1_TC2_IO_049_P_24_mb1_TA4_IO_063_P_31}]
set_property  PACKAGE_PIN AR23 [get_ports {mb1_TC2_IO_050_N_25_mb1_TA4_IO_040_N_20}]
set_property  PACKAGE_PIN AP23 [get_ports {mb1_TC2_IO_051_P_25_mb1_TA4_IO_041_P_20}]
set_property  PACKAGE_PIN AP24 [get_ports {mb1_TC2_IO_052_N_26_mb1_TA4_IO_038_N_19}]
set_property  PACKAGE_PIN AN24 [get_ports {mb1_TC2_IO_053_P_26_mb1_TA4_IO_039_P_19}]
set_property  PACKAGE_PIN AN23 [get_ports {mb1_TC2_IO_054_N_27_mb1_TA4_IO_056_N_28}]
set_property  PACKAGE_PIN AN22 [get_ports {mb1_TC2_IO_055_P_27_mb1_TA4_IO_057_P_28}]
set_property  PACKAGE_PIN AT25 [get_ports {mb1_TC2_IO_056_N_28_mb1_TA4_IO_054_N_27}]
set_property  PACKAGE_PIN AR25 [get_ports {mb1_TC2_IO_057_P_28_mb1_TA4_IO_055_P_27}]
set_property  PACKAGE_PIN AT22 [get_ports {mb1_TC2_IO_058_N_29_mb1_TA4_IO_072_N_36}]
set_property  PACKAGE_PIN AR22 [get_ports {mb1_TC2_IO_059_P_29_mb1_TA4_IO_073_P_36}]
set_property  PACKAGE_PIN BA23 [get_ports {mb1_TC2_IO_060_N_30_mb1_TA4_IO_070_N_35}]
set_property  PACKAGE_PIN BA22 [get_ports {mb1_TC2_IO_061_P_30_mb1_TA4_IO_071_P_35}]
set_property  PACKAGE_PIN BC24 [get_ports {mb1_TC2_IO_062_N_31_mb1_TA4_IO_048_N_24}]
set_property  PACKAGE_PIN BB24 [get_ports {mb1_TC2_IO_063_P_31_mb1_TA4_IO_049_P_24}]
set_property  PACKAGE_PIN BD23 [get_ports {mb1_TC2_IO_064_N_32_mb1_TA4_IO_066_N_33}]
set_property  PACKAGE_PIN BC23 [get_ports {mb1_TC2_IO_065_P_32_mb1_TA4_IO_067_P_33}]
set_property  PACKAGE_PIN BC22 [get_ports {mb1_TC2_IO_066_N_33_mb1_TA4_IO_064_N_32}]
set_property  PACKAGE_PIN BB22 [get_ports {mb1_TC2_IO_067_P_33_mb1_TA4_IO_065_P_32}]
set_property  PACKAGE_PIN BB25 [get_ports {mb1_TC2_IO_068_N_34_mb1_TA4_IO_082_N_41}]
set_property  PACKAGE_PIN BA24 [get_ports {mb1_TC2_IO_069_P_34_mb1_TA4_IO_083_P_41}]
set_property  PACKAGE_PIN BD25 [get_ports {mb1_TC2_IO_070_N_35_mb1_TA4_IO_060_N_30}]
set_property  PACKAGE_PIN BD24 [get_ports {mb1_TC2_IO_071_P_35_mb1_TA4_IO_061_P_30}]
set_property  PACKAGE_PIN AY33 [get_ports {mb1_TC2_IO_072_N_36_mb1_TA4_IO_058_N_29}]
set_property  PACKAGE_PIN AW33 [get_ports {mb1_TC2_IO_073_P_36_mb1_TA4_IO_059_P_29}]
set_property  PACKAGE_PIN AW31 [get_ports {mb1_TC2_IO_074_N_37_mb1_TA4_IO_076_N_38}]
set_property  PACKAGE_PIN AV31 [get_ports {mb1_TC2_IO_075_P_37_mb1_TA4_IO_077_P_38}]
set_property  PACKAGE_PIN AU29 [get_ports {mb1_TC2_IO_076_N_38_mb1_TA4_IO_074_N_37}]
set_property  PACKAGE_PIN AT29 [get_ports {mb1_TC2_IO_077_P_38_mb1_TA4_IO_075_P_37}]
set_property  PACKAGE_PIN AY30 [get_ports {mb1_TC2_IO_078_N_39_mb1_TA4_IO_092_N_46}]
set_property  PACKAGE_PIN AW30 [get_ports {mb1_TC2_IO_079_P_39_mb1_TA4_IO_093_P_46}]
set_property  PACKAGE_PIN AP26 [get_ports {mb1_TC2_IO_080_N_40_mb1_TA4_IO_090_N_45}]
set_property  PACKAGE_PIN AP25 [get_ports {mb1_TC2_IO_081_P_40_mb1_TA4_IO_091_P_45}]
set_property  PACKAGE_PIN AY32 [get_ports {mb1_TC2_IO_082_N_41_mb1_TA4_IO_068_N_34}]
set_property  PACKAGE_PIN AY31 [get_ports {mb1_TC2_IO_083_P_41_mb1_TA4_IO_069_P_34}]
set_property  PACKAGE_PIN AP33 [get_ports {mb1_TC2_IO_084_N_42_mb1_TA4_IO_086_N_43}]
set_property  PACKAGE_PIN AN33 [get_ports {mb1_TC2_IO_085_P_42_mb1_TA4_IO_087_P_43}]
set_property  PACKAGE_PIN AP30 [get_ports {mb1_TC2_IO_086_N_43_mb1_TA4_IO_084_N_42}]
set_property  PACKAGE_PIN AP29 [get_ports {mb1_TC2_IO_087_P_43_mb1_TA4_IO_085_P_42}]
set_property  PACKAGE_PIN AN28 [get_ports {mb1_TC2_IO_088_N_44_mb1_TA4_IO_102_N_51}]
set_property  PACKAGE_PIN AN27 [get_ports {mb1_TC2_IO_089_P_44_mb1_TA4_IO_103_P_51}]
set_property  PACKAGE_PIN AT30 [get_ports {mb1_TC2_IO_090_N_45_mb1_TA4_IO_080_N_40}]
set_property  PACKAGE_PIN AR30 [get_ports {mb1_TC2_IO_091_P_45_mb1_TA4_IO_081_P_40}]
set_property  PACKAGE_PIN AR28 [get_ports {mb1_TC2_IO_092_N_46_mb1_TA4_IO_078_N_39}]
set_property  PACKAGE_PIN AP28 [get_ports {mb1_TC2_IO_093_P_46_mb1_TA4_IO_079_P_39}]
set_property  PACKAGE_PIN AT33 [get_ports {mb1_TC2_IO_094_N_47_mb1_TA4_IO_096_N_48}]
set_property  PACKAGE_PIN AR33 [get_ports {mb1_TC2_IO_095_P_47_mb1_TA4_IO_097_P_48}]
set_property  PACKAGE_PIN BD26 [get_ports {mb1_TC2_IO_096_N_48_mb1_TA4_IO_094_N_47}]
set_property  PACKAGE_PIN BC26 [get_ports {mb1_TC2_IO_097_P_48_mb1_TA4_IO_095_P_47}]
set_property  PACKAGE_PIN BC29 [get_ports {mb1_TC2_IO_098_N_49_mb1_TA4_IO_112_N_56}]
set_property  PACKAGE_PIN BB29 [get_ports {mb1_TC2_IO_099_P_49_mb1_TA4_IO_113_P_56}]
set_property  PACKAGE_PIN BD29 [get_ports {mb1_TC2_IO_100_N_50_mb1_TA4_IO_110_N_55}]
set_property  PACKAGE_PIN BD28 [get_ports {mb1_TC2_IO_101_P_50_mb1_TA4_IO_111_P_55}]
set_property  PACKAGE_PIN BA28 [get_ports {mb1_TC2_IO_102_N_51_mb1_TA4_IO_088_N_44}]
set_property  PACKAGE_PIN BA27 [get_ports {mb1_TC2_IO_103_P_51_mb1_TA4_IO_089_P_44}]
set_property  PACKAGE_PIN BC28 [get_ports {mb1_TC2_IO_104_N_52_mb1_TA4_IO_106_N_53}]
set_property  PACKAGE_PIN BC27 [get_ports {mb1_TC2_IO_105_P_52_mb1_TA4_IO_107_P_53}]
set_property  PACKAGE_PIN BB27 [get_ports {mb1_TC2_IO_106_N_53_mb1_TA4_IO_104_N_52}]
set_property  PACKAGE_PIN BB26 [get_ports {mb1_TC2_IO_107_P_53_mb1_TA4_IO_105_P_52}]
set_property  PACKAGE_PIN BA29 [get_ports {mb1_TC2_IO_108_N_54_mb1_TA4_IO_122_N_61}]
set_property  PACKAGE_PIN AY28 [get_ports {mb1_TC2_IO_109_P_54_mb1_TA4_IO_123_P_61}]
set_property  PACKAGE_PIN AY27 [get_ports {mb1_TC2_IO_110_N_55_mb1_TA4_IO_100_N_50}]
set_property  PACKAGE_PIN AY26 [get_ports {mb1_TC2_IO_111_P_55_mb1_TA4_IO_101_P_50}]
set_property  PACKAGE_PIN AW29 [get_ports {mb1_TC2_IO_112_N_56_mb1_TA4_IO_098_N_49}]
set_property  PACKAGE_PIN AW28 [get_ports {mb1_TC2_IO_113_P_56_mb1_TA4_IO_099_P_49}]
set_property  PACKAGE_PIN AW26 [get_ports {mb1_TC2_IO_114_N_57_mb1_TA4_IO_116_N_58}]
set_property  PACKAGE_PIN AV26 [get_ports {mb1_TC2_IO_115_P_57_mb1_TA4_IO_117_P_58}]
set_property  PACKAGE_PIN AN26 [get_ports {mb1_TC2_IO_116_N_58_mb1_TA4_IO_114_N_57}]
set_property  PACKAGE_PIN AM26 [get_ports {mb1_TC2_IO_117_P_58_mb1_TA4_IO_115_P_57}]
set_property  PACKAGE_PIN AK26 [get_ports {mb1_TC2_IO_120_N_60_mb1_TA4_IO_130}]
set_property  PACKAGE_PIN AJ26 [get_ports {mb1_TC2_IO_121_P_60_mb1_TA4_IO_131}]
set_property  PACKAGE_PIN AM27 [get_ports {mb1_TC2_IO_122_N_61_mb1_TA4_IO_108_N_54}]
set_property  PACKAGE_PIN AL27 [get_ports {mb1_TC2_IO_123_P_61_mb1_TA4_IO_109_P_54}]
set_property  PACKAGE_PIN AK25 [get_ports {mb1_TC2_IO_124_N_62_mb1_TA4_IO_126_N_63}]
set_property  PACKAGE_PIN AJ25 [get_ports {mb1_TC2_IO_125_P_62_mb1_TA4_IO_127_P_63}]
set_property  PACKAGE_PIN AM25 [get_ports {mb1_TC2_IO_126_N_63_mb1_TA4_IO_124_N_62}]
set_property  PACKAGE_PIN AL25 [get_ports {mb1_TC2_IO_127_P_63_mb1_TA4_IO_125_P_62}]
set_property  PACKAGE_PIN AW25 [get_ports {mb1_TC2_IO_130_mb1_TA4_IO_120_N_60}]
set_property  PACKAGE_PIN AJ21 [get_ports {mb1_TC2_IO_131_mb1_TA4_IO_121_P_60}]

# pins which are connected to motherboard connector TD1 
# and connector BA1 on x-board IC-PDS-CABLE-R1 
set_property  PACKAGE_PIN L3 [get_ports {mb1_TD1_CLKIO_N_0_mb1_TB3_CLKIO_N_7}]
set_property  PACKAGE_PIN N3 [get_ports {mb1_TD1_CLKIO_N_1_mb1_TB3_CLKIO_N_6}]
set_property  PACKAGE_PIN D6 [get_ports {mb1_TD1_CLKIO_N_2_mb1_TB3_CLKIO_N_4}]
set_property  PACKAGE_PIN C3 [get_ports {mb1_TD1_CLKIO_N_3_mb1_TB3_CLKIO_N_3}]
set_property  PACKAGE_PIN M4 [get_ports {mb1_TD1_CLKIO_N_4_mb1_TB3_CLKIO_N_2}]
set_property  PACKAGE_PIN P3 [get_ports {mb1_TD1_CLKIO_N_5_mb1_TB3_IO_010_N_05}]
set_property  PACKAGE_PIN D5 [get_ports {mb1_TD1_CLKIO_N_6_mb1_TB3_CLKIO_N_1}]
set_property  PACKAGE_PIN C4 [get_ports {mb1_TD1_CLKIO_N_7_mb1_TB3_CLKIO_N_0}]
set_property  PACKAGE_PIN L4 [get_ports {mb1_TD1_CLKIO_P_0_mb1_TB3_CLKIO_P_7}]
set_property  PACKAGE_PIN N4 [get_ports {mb1_TD1_CLKIO_P_1_mb1_TB3_CLKIO_P_6}]
set_property  PACKAGE_PIN E6 [get_ports {mb1_TD1_CLKIO_P_2_mb1_TB3_CLKIO_P_4}]
set_property  PACKAGE_PIN D3 [get_ports {mb1_TD1_CLKIO_P_3_mb1_TB3_CLKIO_P_3}]
set_property  PACKAGE_PIN M5 [get_ports {mb1_TD1_CLKIO_P_4_mb1_TB3_CLKIO_P_2}]
set_property  PACKAGE_PIN P4 [get_ports {mb1_TD1_CLKIO_P_5_mb1_TB3_IO_011_P_05}]
set_property  PACKAGE_PIN E5 [get_ports {mb1_TD1_CLKIO_P_6_mb1_TB3_CLKIO_P_1}]
set_property  PACKAGE_PIN D4 [get_ports {mb1_TD1_CLKIO_P_7_mb1_TB3_CLKIO_P_0}]
set_property  PACKAGE_PIN H7 [get_ports {mb1_TD1_IO_004_N_02_mb1_TB3_IO_006_N_03}]
set_property  PACKAGE_PIN H8 [get_ports {mb1_TD1_IO_005_P_02_mb1_TB3_IO_007_P_03}]
set_property  PACKAGE_PIN F5 [get_ports {mb1_TD1_IO_006_N_03_mb1_TB3_IO_004_N_02}]
set_property  PACKAGE_PIN G5 [get_ports {mb1_TD1_IO_007_P_03_mb1_TB3_IO_005_P_02}]
set_property  PACKAGE_PIN H6 [get_ports {mb1_TD1_IO_008_N_04_mb1_TB3_IO_022_N_11}]
set_property  PACKAGE_PIN J6 [get_ports {mb1_TD1_IO_009_P_04_mb1_TB3_IO_023_P_11}]
set_property  PACKAGE_PIN E7 [get_ports {mb1_TD1_IO_010_N_05_mb1_TB3_CLKIO_N_5}]
set_property  PACKAGE_PIN F7 [get_ports {mb1_TD1_IO_011_P_05_mb1_TB3_CLKIO_P_5}]
set_property  PACKAGE_PIN F4 [get_ports {mb1_TD1_IO_012_N_06_mb1_TB3_IO_012_N_06}]
set_property  PACKAGE_PIN G4 [get_ports {mb1_TD1_IO_013_P_06_mb1_TB3_IO_013_P_06}]
set_property  PACKAGE_PIN E1 [get_ports {mb1_TD1_IO_014_N_07_mb1_TB3_IO_016_N_08}]
set_property  PACKAGE_PIN E2 [get_ports {mb1_TD1_IO_015_P_07_mb1_TB3_IO_017_P_08}]
set_property  PACKAGE_PIN H2 [get_ports {mb1_TD1_IO_016_N_08_mb1_TB3_IO_014_N_07}]
set_property  PACKAGE_PIN H3 [get_ports {mb1_TD1_IO_017_P_08_mb1_TB3_IO_015_P_07}]
set_property  PACKAGE_PIN G1 [get_ports {mb1_TD1_IO_018_N_09_mb1_TB3_IO_032_N_16}]
set_property  PACKAGE_PIN H1 [get_ports {mb1_TD1_IO_019_P_09_mb1_TB3_IO_033_P_16}]
set_property  PACKAGE_PIN F2 [get_ports {mb1_TD1_IO_020_N_10_mb1_TB3_IO_030_N_15}]
set_property  PACKAGE_PIN G2 [get_ports {mb1_TD1_IO_021_P_10_mb1_TB3_IO_031_P_15}]
set_property  PACKAGE_PIN E3 [get_ports {mb1_TD1_IO_022_N_11_mb1_TB3_IO_008_N_04}]
set_property  PACKAGE_PIN F3 [get_ports {mb1_TD1_IO_023_P_11_mb1_TB3_IO_009_P_04}]
set_property  PACKAGE_PIN U6 [get_ports {mb1_TD1_IO_024_N_12_mb1_TB3_IO_026_N_13}]
set_property  PACKAGE_PIN U7 [get_ports {mb1_TD1_IO_025_P_12_mb1_TB3_IO_027_P_13}]
set_property  PACKAGE_PIN R8 [get_ports {mb1_TD1_IO_026_N_13_mb1_TB3_IO_024_N_12}]
set_property  PACKAGE_PIN T9 [get_ports {mb1_TD1_IO_027_P_13_mb1_TB3_IO_025_P_12}]
set_property  PACKAGE_PIN V9 [get_ports {mb1_TD1_IO_028_N_14_mb1_TB3_IO_042_N_21}]
set_property  PACKAGE_PIN V10 [get_ports {mb1_TD1_IO_029_P_14_mb1_TB3_IO_043_P_21}]
set_property  PACKAGE_PIN T7 [get_ports {mb1_TD1_IO_030_N_15_mb1_TB3_IO_020_N_10}]
set_property  PACKAGE_PIN T8 [get_ports {mb1_TD1_IO_031_P_15_mb1_TB3_IO_021_P_10}]
set_property  PACKAGE_PIN U9 [get_ports {mb1_TD1_IO_032_N_16_mb1_TB3_IO_018_N_09}]
set_property  PACKAGE_PIN U10 [get_ports {mb1_TD1_IO_033_P_16_mb1_TB3_IO_019_P_09}]
set_property  PACKAGE_PIN V7 [get_ports {mb1_TD1_IO_034_N_17_mb1_TB3_IO_036_N_18}]
set_property  PACKAGE_PIN V8 [get_ports {mb1_TD1_IO_035_P_17_mb1_TB3_IO_037_P_18}]
set_property  PACKAGE_PIN U1 [get_ports {mb1_TD1_IO_036_N_18_mb1_TB3_IO_034_N_17}]
set_property  PACKAGE_PIN U2 [get_ports {mb1_TD1_IO_037_P_18_mb1_TB3_IO_035_P_17}]
set_property  PACKAGE_PIN T4 [get_ports {mb1_TD1_IO_038_N_19_mb1_TB3_IO_052_N_26}]
set_property  PACKAGE_PIN T5 [get_ports {mb1_TD1_IO_039_P_19_mb1_TB3_IO_053_P_26}]
set_property  PACKAGE_PIN T2 [get_ports {mb1_TD1_IO_040_N_20_mb1_TB3_IO_050_N_25}]
set_property  PACKAGE_PIN T3 [get_ports {mb1_TD1_IO_041_P_20_mb1_TB3_IO_051_P_25}]
set_property  PACKAGE_PIN V3 [get_ports {mb1_TD1_IO_042_N_21_mb1_TB3_IO_028_N_14}]
set_property  PACKAGE_PIN V4 [get_ports {mb1_TD1_IO_043_P_21_mb1_TB3_IO_029_P_14}]
set_property  PACKAGE_PIN U4 [get_ports {mb1_TD1_IO_044_N_22_mb1_TB3_IO_046_N_23}]
set_property  PACKAGE_PIN U5 [get_ports {mb1_TD1_IO_045_P_22_mb1_TB3_IO_047_P_23}]
set_property  PACKAGE_PIN V1 [get_ports {mb1_TD1_IO_046_N_23_mb1_TB3_IO_044_N_22}]
set_property  PACKAGE_PIN V2 [get_ports {mb1_TD1_IO_047_P_23_mb1_TB3_IO_045_P_22}]
set_property  PACKAGE_PIN W3 [get_ports {mb1_TD1_IO_048_N_24_mb1_TB3_IO_062_N_31}]
set_property  PACKAGE_PIN W4 [get_ports {mb1_TD1_IO_049_P_24_mb1_TB3_IO_063_P_31}]
set_property  PACKAGE_PIN W5 [get_ports {mb1_TD1_IO_050_N_25_mb1_TB3_IO_040_N_20}]
set_property  PACKAGE_PIN Y5 [get_ports {mb1_TD1_IO_051_P_25_mb1_TB3_IO_041_P_20}]
set_property  PACKAGE_PIN AA4 [get_ports {mb1_TD1_IO_052_N_26_mb1_TB3_IO_038_N_19}]
set_property  PACKAGE_PIN AA5 [get_ports {mb1_TD1_IO_053_P_26_mb1_TB3_IO_039_P_19}]
set_property  PACKAGE_PIN W1 [get_ports {mb1_TD1_IO_054_N_27_mb1_TB3_IO_056_N_28}]
set_property  PACKAGE_PIN Y1 [get_ports {mb1_TD1_IO_055_P_27_mb1_TB3_IO_057_P_28}]
set_property  PACKAGE_PIN AA2 [get_ports {mb1_TD1_IO_056_N_28_mb1_TB3_IO_054_N_27}]
set_property  PACKAGE_PIN AA3 [get_ports {mb1_TD1_IO_057_P_28_mb1_TB3_IO_055_P_27}]
set_property  PACKAGE_PIN Y2 [get_ports {mb1_TD1_IO_058_N_29_mb1_TB3_IO_072_N_36}]
set_property  PACKAGE_PIN Y3 [get_ports {mb1_TD1_IO_059_P_29_mb1_TB3_IO_073_P_36}]
set_property  PACKAGE_PIN W9 [get_ports {mb1_TD1_IO_060_N_30_mb1_TB3_IO_070_N_35}]
set_property  PACKAGE_PIN W10 [get_ports {mb1_TD1_IO_061_P_30_mb1_TB3_IO_071_P_35}]
set_property  PACKAGE_PIN AA9 [get_ports {mb1_TD1_IO_062_N_31_mb1_TB3_IO_048_N_24}]
set_property  PACKAGE_PIN AA10 [get_ports {mb1_TD1_IO_063_P_31_mb1_TB3_IO_049_P_24}]
set_property  PACKAGE_PIN AA7 [get_ports {mb1_TD1_IO_064_N_32_mb1_TB3_IO_066_N_33}]
set_property  PACKAGE_PIN AA8 [get_ports {mb1_TD1_IO_065_P_32_mb1_TB3_IO_067_P_33}]
set_property  PACKAGE_PIN W8 [get_ports {mb1_TD1_IO_066_N_33_mb1_TB3_IO_064_N_32}]
set_property  PACKAGE_PIN Y8 [get_ports {mb1_TD1_IO_067_P_33_mb1_TB3_IO_065_P_32}]
set_property  PACKAGE_PIN Y6 [get_ports {mb1_TD1_IO_068_N_34_mb1_TB3_IO_082_N_41}]
set_property  PACKAGE_PIN Y7 [get_ports {mb1_TD1_IO_069_P_34_mb1_TB3_IO_083_P_41}]
set_property  PACKAGE_PIN V6 [get_ports {mb1_TD1_IO_070_N_35_mb1_TB3_IO_060_N_30}]
set_property  PACKAGE_PIN W6 [get_ports {mb1_TD1_IO_071_P_35_mb1_TB3_IO_061_P_30}]
set_property  PACKAGE_PIN C6 [get_ports {mb1_TD1_IO_072_N_36_mb1_TB3_IO_058_N_29}]
set_property  PACKAGE_PIN C7 [get_ports {mb1_TD1_IO_073_P_36_mb1_TB3_IO_059_P_29}]
set_property  PACKAGE_PIN A7 [get_ports {mb1_TD1_IO_074_N_37_mb1_TB3_IO_076_N_38}]
set_property  PACKAGE_PIN B7 [get_ports {mb1_TD1_IO_075_P_37_mb1_TB3_IO_077_P_38}]
set_property  PACKAGE_PIN P1 [get_ports {mb1_TD1_IO_076_N_38_mb1_TB3_IO_074_N_37}]
set_property  PACKAGE_PIN R1 [get_ports {mb1_TD1_IO_077_P_38_mb1_TB3_IO_075_P_37}]
set_property  PACKAGE_PIN C8 [get_ports {mb1_TD1_IO_078_N_39_mb1_TB3_IO_092_N_46}]
set_property  PACKAGE_PIN D8 [get_ports {mb1_TD1_IO_079_P_39_mb1_TB3_IO_093_P_46}]
set_property  PACKAGE_PIN N1 [get_ports {mb1_TD1_IO_080_N_40_mb1_TB3_IO_090_N_45}]
set_property  PACKAGE_PIN N2 [get_ports {mb1_TD1_IO_081_P_40_mb1_TB3_IO_091_P_45}]
set_property  PACKAGE_PIN B5 [get_ports {mb1_TD1_IO_082_N_41_mb1_TB3_IO_068_N_34}]
set_property  PACKAGE_PIN B6 [get_ports {mb1_TD1_IO_083_P_41_mb1_TB3_IO_069_P_34}]
set_property  PACKAGE_PIN A3 [get_ports {mb1_TD1_IO_084_N_42_mb1_TB3_IO_086_N_43}]
set_property  PACKAGE_PIN B4 [get_ports {mb1_TD1_IO_085_P_42_mb1_TB3_IO_087_P_43}]
set_property  PACKAGE_PIN C1 [get_ports {mb1_TD1_IO_086_N_43_mb1_TB3_IO_084_N_42}]
set_property  PACKAGE_PIN D1 [get_ports {mb1_TD1_IO_087_P_43_mb1_TB3_IO_085_P_42}]
set_property  PACKAGE_PIN R2 [get_ports {mb1_TD1_IO_088_N_44_mb1_TB3_IO_102_N_51}]
set_property  PACKAGE_PIN R3 [get_ports {mb1_TD1_IO_089_P_44_mb1_TB3_IO_103_P_51}]
set_property  PACKAGE_PIN A4 [get_ports {mb1_TD1_IO_090_N_45_mb1_TB3_IO_080_N_40}]
set_property  PACKAGE_PIN A5 [get_ports {mb1_TD1_IO_091_P_45_mb1_TB3_IO_081_P_40}]
set_property  PACKAGE_PIN M1 [get_ports {mb1_TD1_IO_092_N_46_mb1_TB3_IO_078_N_39}]
set_property  PACKAGE_PIN M2 [get_ports {mb1_TD1_IO_093_P_46_mb1_TB3_IO_079_P_39}]
set_property  PACKAGE_PIN B2 [get_ports {mb1_TD1_IO_094_N_47_mb1_TB3_IO_096_N_48}]
set_property  PACKAGE_PIN C2 [get_ports {mb1_TD1_IO_095_P_47_mb1_TB3_IO_097_P_48}]
set_property  PACKAGE_PIN K8 [get_ports {mb1_TD1_IO_096_N_48_mb1_TB3_IO_094_N_47}]
set_property  PACKAGE_PIN L9 [get_ports {mb1_TD1_IO_097_P_48_mb1_TB3_IO_095_P_47}]
set_property  PACKAGE_PIN K6 [get_ports {mb1_TD1_IO_098_N_49_mb1_TB3_IO_112_N_56}]
set_property  PACKAGE_PIN K7 [get_ports {mb1_TD1_IO_099_P_49_mb1_TB3_IO_113_P_56}]
set_property  PACKAGE_PIN K5 [get_ports {mb1_TD1_IO_100_N_50_mb1_TB3_IO_110_N_55}]
set_property  PACKAGE_PIN L5 [get_ports {mb1_TD1_IO_101_P_50_mb1_TB3_IO_111_P_55}]
set_property  PACKAGE_PIN M9 [get_ports {mb1_TD1_IO_102_N_51_mb1_TB3_IO_088_N_44}]
set_property  PACKAGE_PIN M10 [get_ports {mb1_TD1_IO_103_P_51_mb1_TB3_IO_089_P_44}]
set_property  PACKAGE_PIN L7 [get_ports {mb1_TD1_IO_104_N_52_mb1_TB3_IO_106_N_53}]
set_property  PACKAGE_PIN L8 [get_ports {mb1_TD1_IO_105_P_52_mb1_TB3_IO_107_P_53}]
set_property  PACKAGE_PIN M6 [get_ports {mb1_TD1_IO_106_N_53_mb1_TB3_IO_104_N_52}]
set_property  PACKAGE_PIN M7 [get_ports {mb1_TD1_IO_107_P_53_mb1_TB3_IO_105_P_52}]
set_property  PACKAGE_PIN K2 [get_ports {mb1_TD1_IO_108_N_54_mb1_TB3_IO_122_N_61}]
set_property  PACKAGE_PIN L2 [get_ports {mb1_TD1_IO_109_P_54_mb1_TB3_IO_123_P_61}]
set_property  PACKAGE_PIN J4 [get_ports {mb1_TD1_IO_110_N_55_mb1_TB3_IO_100_N_50}]
set_property  PACKAGE_PIN J5 [get_ports {mb1_TD1_IO_111_P_55_mb1_TB3_IO_101_P_50}]
set_property  PACKAGE_PIN J1 [get_ports {mb1_TD1_IO_112_N_56_mb1_TB3_IO_098_N_49}]
set_property  PACKAGE_PIN K1 [get_ports {mb1_TD1_IO_113_P_56_mb1_TB3_IO_099_P_49}]
set_property  PACKAGE_PIN J3 [get_ports {mb1_TD1_IO_114_N_57_mb1_TB3_IO_116_N_58}]
set_property  PACKAGE_PIN K3 [get_ports {mb1_TD1_IO_115_P_57_mb1_TB3_IO_117_P_58}]
set_property  PACKAGE_PIN N8 [get_ports {mb1_TD1_IO_116_N_58_mb1_TB3_IO_114_N_57}]
set_property  PACKAGE_PIN N9 [get_ports {mb1_TD1_IO_117_P_58_mb1_TB3_IO_115_P_57}]
set_property  PACKAGE_PIN P9 [get_ports {mb1_TD1_IO_120_N_60_mb1_TB3_IO_130}]
set_property  PACKAGE_PIN P10 [get_ports {mb1_TD1_IO_121_P_60_mb1_TB3_IO_131}]
set_property  PACKAGE_PIN P5 [get_ports {mb1_TD1_IO_122_N_61_mb1_TB3_IO_108_N_54}]
set_property  PACKAGE_PIN R5 [get_ports {mb1_TD1_IO_123_P_61_mb1_TB3_IO_109_P_54}]
set_property  PACKAGE_PIN N6 [get_ports {mb1_TD1_IO_124_N_62_mb1_TB3_IO_126_N_63}]
set_property  PACKAGE_PIN P6 [get_ports {mb1_TD1_IO_125_P_62_mb1_TB3_IO_127_P_63}]
set_property  PACKAGE_PIN N7 [get_ports {mb1_TD1_IO_126_N_63_mb1_TB3_IO_124_N_62}]
set_property  PACKAGE_PIN P8 [get_ports {mb1_TD1_IO_127_P_63_mb1_TB3_IO_125_P_62}]
set_property  PACKAGE_PIN T10 [get_ports {mb1_TD1_IO_130_mb1_TB3_IO_120_N_60}]
set_property  PACKAGE_PIN Y10 [get_ports {mb1_TD1_IO_131_mb1_TB3_IO_121_P_60}]

# pins which are connected to motherboard connector TD2 
# and connector BA1 on x-board EB-PDS-DDR3-R2 
set_property  PACKAGE_PIN AY15 [get_ports {c3_ddr3_addr[0]}] #td2_eb1_A0
set_property  PACKAGE_PIN AW14 [get_ports {c3_ddr3_addr[1]}] #td2_eb1_A1
set_property  PACKAGE_PIN AV14 [get_ports {c3_ddr3_addr[2]}] #td2_eb1_A2
set_property  PACKAGE_PIN BA17 [get_ports {c3_ddr3_addr[3]}] #td2_eb1_A3
set_property  PACKAGE_PIN AY17 [get_ports {c3_ddr3_addr[4]}] #td2_eb1_A4
set_property  PACKAGE_PIN BA13 [get_ports {c3_ddr3_addr[5]}] #td2_eb1_A5
set_property  PACKAGE_PIN BA14 [get_ports {c3_ddr3_addr[6]}] #td2_eb1_A6
set_property  PACKAGE_PIN BD15 [get_ports {c3_ddr3_addr[7]}] #td2_eb1_A7
set_property  PACKAGE_PIN BD16 [get_ports {c3_ddr3_addr[8]}] #td2_eb1_A8
set_property  PACKAGE_PIN BB14 [get_ports {c3_ddr3_addr[9]}] #td2_eb1_A9
set_property  PACKAGE_PIN BB15 [get_ports {c3_ddr3_addr[10]}] #td2_eb1_A10
set_property  PACKAGE_PIN BD14 [get_ports {c3_ddr3_addr[11]}] #td2_eb1_A11
set_property  PACKAGE_PIN BC14 [get_ports {c3_ddr3_addr[12]}] #td2_eb1_A12
set_property  PACKAGE_PIN BB16 [get_ports {c3_ddr3_addr[13]}] #td2_eb1_A13
set_property  PACKAGE_PIN BB17 [get_ports {c3_ddr3_addr[14]}] #td2_eb1_A14
set_property  PACKAGE_PIN AU14 [get_ports {c3_ddr3_ba[0]}] #td2_eb1_BA0
set_property  PACKAGE_PIN AT14 [get_ports {c3_ddr3_ba[1]}] #td2_eb1_BA1
set_property  PACKAGE_PIN BA15 [get_ports {c3_ddr3_ba[2]}] #td2_eb1_BA2
set_property  PACKAGE_PIN AW15 [get_ports {c3_ddr3_cas_n}]  #td2_eb1_CASn
set_property  PACKAGE_PIN BC17 [get_ports {c3_ddr3_ck_p}] #td2_eb1_CK
set_property  PACKAGE_PIN AP16 [get_ports {c3_ddr3_cke}] #td2_eb1_CKE
set_property  PACKAGE_PIN BC16 [get_ports {c3_ddr3_ck_n}]  #td2_eb1_CKn
#set_property  PACKAGE_PIN AT15 [get_ports {c3_sys_clk_p}] #td2_eb1_CLK_200MHZ
#set_property  PACKAGE_PIN AU15 [get_ports {c3_sys_clk_n}] #td2_eb1_CLK_200MHZn
set_property  PACKAGE_PIN AY16 [get_ports {c3_ddr3_sc_n}] #td2_eb1_20CSn
set_property  PACKAGE_PIN BC21 [get_ports {c3_ddr3_dq[0]}] #td2_eb1_DQ00_D0
set_property  PACKAGE_PIN BC18 [get_ports {c3_ddr3_dq[1]}] #td2_eb1_DQ00_D1
set_property  PACKAGE_PIN BD18 [get_ports {c3_ddr3_dq[2]}] #td2_eb1_DQ00_D2
set_property  PACKAGE_PIN BA20 [get_ports {c3_ddr3_dq[3]}] #td2_eb1_DQ00_D3
set_property  PACKAGE_PIN BB20 [get_ports {c3_ddr3_dq[4]}] #td2_eb1_DQ00_D4
set_property  PACKAGE_PIN BC19 [get_ports {c3_ddr3_dq[5]}] #td2_eb1_DQ00_D5
set_property  PACKAGE_PIN BD19 [get_ports {c3_ddr3_dq[6]}] #td2_eb1_DQ00_D6
set_property  PACKAGE_PIN BA19 [get_ports {c3_ddr3_dq[7]}] #td2_eb1_DQ00_D7
set_property  PACKAGE_PIN BB21 [get_ports {c3_ddr3_dm[0]}] #td2_eb1_DQ00_DM
set_property  PACKAGE_PIN BD21 [get_ports {c3_ddr3_dqs_p[0]}] #td2_eb1_DQ00_DQS
set_property  PACKAGE_PIN BD20 [get_ports {c3_ddr3_dqs_n[0]}] #td2_eb1_DQ00_DQSn
set_property  PACKAGE_PIN AY21 [get_ports {c3_ddr3_dq[8]}] #td2_eb1_DQ01_D0
set_property  PACKAGE_PIN AY18 [get_ports {c3_ddr3_dq[9]}] #td2_eb1_DQ01_D1
set_property  PACKAGE_PIN BA18 [get_ports {c3_ddr3_dq[10]}] #td2_eb1_DQ01_D2
set_property  PACKAGE_PIN AW19 [get_ports {c3_ddr3_dq[11]}] #td2_eb1_DQ01_D3
set_property  PACKAGE_PIN AW18 [get_ports {c3_ddr3_dq[12]}] #td2_eb1_DQ01_D4
set_property  PACKAGE_PIN AT19 [get_ports {c3_ddr3_dq[13]}] #td2_eb1_DQ01_D5
set_property  PACKAGE_PIN AU19 [get_ports {c3_ddr3_dq[14]}] #td2_eb1_DQ01_D6
set_property  PACKAGE_PIN AV19 [get_ports {c3_ddr3_dq[15]}] #td2_eb1_DQ01_D7
set_property  PACKAGE_PIN AW21 [get_ports {c3_ddr3_dm[1]}] #td2_eb1_DQ01_DM
set_property  PACKAGE_PIN AW20 [get_ports {c3_ddr3_dqs_p[1]}] #td2_eb1_DQ01_DQS
set_property  PACKAGE_PIN AY20 [get_ports {c3_ddr3_dqs_n[1]}] #td2_eb1_DQ01_DQSn
set_property  PACKAGE_PIN AR20 [get_ports {c3_ddr3_dq[16]}] #td2_eb1_DQ02_D0
set_property  PACKAGE_PIN AT20 [get_ports {c3_ddr3_dq[17]}] #td2_eb1_DQ02_D1
set_property  PACKAGE_PIN AU21 [get_ports {c3_ddr3_dq[18]}] #td2_eb1_DQ02_D2
set_property  PACKAGE_PIN AU20 [get_ports {c3_ddr3_dq[19]}] #td2_eb1_DQ02_D3
set_property  PACKAGE_PIN AT18 [get_ports {c3_ddr3_dq[20]}] #td2_eb1_DQ02_D4
set_property  PACKAGE_PIN AP20 [get_ports {c3_ddr3_dq[21]}] #td2_eb1_DQ02_D5
set_property  PACKAGE_PIN AP19 [get_ports {c3_ddr3_dq[22]}] #td2_eb1_DQ02_D6
set_property  PACKAGE_PIN AN18 [get_ports {c3_ddr3_dq[23]}] #td2_eb1_DQ02_D7
set_property  PACKAGE_PIN AR18 [get_ports {c3_ddr3_dm[2]}] #td2_eb1_DQ02_DM
set_property  PACKAGE_PIN AP21 [get_ports {c3_ddr3_dqs_p[2]}] #td2_eb1_DQ02_DQS
set_property  PACKAGE_PIN AR21 [get_ports {c3_ddr3_dqs_n[2]}] #td2_eb1_DQ02_DQSn
set_property  PACKAGE_PIN AK20 [get_ports {c3_ddr3_dq[24]}] #td2_eb1_DQ03_D0
set_property  PACKAGE_PIN AL20 [get_ports {c3_ddr3_dq[25]}] #td2_eb1_DQ03_D1
set_property  PACKAGE_PIN AM20 [get_ports {c3_ddr3_dq[26]}] #td2_eb1_DQ03_D2
set_property  PACKAGE_PIN AN19 [get_ports {c3_ddr3_dq[27]}] #td2_eb1_DQ03_D3
set_property  PACKAGE_PIN AL19 [get_ports {c3_ddr3_dq[28]}] #td2_eb1_DQ03_D4
set_property  PACKAGE_PIN AM19 [get_ports {c3_ddr3_dq[29]}] #td2_eb1_DQ03_D5
set_property  PACKAGE_PIN AJ20 [get_ports {c3_ddr3_dq[30]}] #td2_eb1_DQ03_D6
set_property  PACKAGE_PIN AJ19 [get_ports {c3_ddr3_dq[31]}] #td2_eb1_DQ03_D7
set_property  PACKAGE_PIN AK18 [get_ports {c3_ddr3_dm[3]}] #td2_eb1_DQ03_DM
set_property  PACKAGE_PIN AK17 [get_ports {c3_ddr3_dqs_p[3]}] #td2_eb1_DQ03_DQS
set_property  PACKAGE_PIN AL17 [get_ports {c3_ddr3_dqs_n[3]}] #td2_eb1_DQ03_DQSn
set_property  PACKAGE_PIN AM11 [get_ports {c3_ddr3_dq[32]}] #td2_eb1_DQ04_D0
set_property  PACKAGE_PIN AJ11 [get_ports {c3_ddr3_dq[33]}] #td2_eb1_DQ04_D1
set_property  PACKAGE_PIN AJ10 [get_ports {c3_ddr3_dq[34]}] #td2_eb1_DQ04_D2
set_property  PACKAGE_PIN AL10 [get_ports {c3_ddr3_dq[35]}] #td2_eb1_DQ04_D3
set_property  PACKAGE_PIN AM10 [get_ports {c3_ddr3_dq[36]}] #td2_eb1_DQ04_D4
set_property  PACKAGE_PIN AK13 [get_ports {c3_ddr3_dq[37]}] #td2_eb1_DQ04_D5
set_property  PACKAGE_PIN AK12 [get_ports {c3_ddr3_dq[38]}] #td2_eb1_DQ04_D6
set_property  PACKAGE_PIN AK11 [get_ports {c3_ddr3_dq[39]}] #td2_eb1_DQ04_D7
set_property  PACKAGE_PIN AM12 [get_ports {c3_ddr3_dm[4]}] #td2_eb1_DQ04_DM
set_property  PACKAGE_PIN AL13 [get_ports {c3_ddr3_dqs_p[4]}] #td2_eb1_DQ04_DQS
set_property  PACKAGE_PIN AL12 [get_ports {c3_ddr3_dqs_n[4]}] #td2_eb1_DQ04_DQSn
set_property  PACKAGE_PIN AR10 [get_ports {c3_ddr3_dq[40]}] #td2_eb1_DQ05_D0
set_property  PACKAGE_PIN AR13 [get_ports {c3_ddr3_dq[41]}] #td2_eb1_DQ05_D1
set_property  PACKAGE_PIN AT13 [get_ports {c3_ddr3_dq[42]}] #td2_eb1_DQ05_D2
set_property  PACKAGE_PIN AN13 [get_ports {c3_ddr3_dq[43]}] #td2_eb1_DQ05_D3
set_property  PACKAGE_PIN AP13 [get_ports {c3_ddr3_dq[44]}] #td2_eb1_DQ05_D4
set_property  PACKAGE_PIN AP11 [get_ports {c3_ddr3_dq[45]}] #td2_eb1_DQ05_D5
set_property  PACKAGE_PIN AR11 [get_ports {c3_ddr3_dq[46]}] #td2_eb1_DQ05_D6
set_property  PACKAGE_PIN AR12 [get_ports {c3_ddr3_dq[47]}] #td2_eb1_DQ05_D7
set_property  PACKAGE_PIN AP10 [get_ports {c3_ddr3_dm[5]}] #td2_eb1_DQ05_DM
set_property  PACKAGE_PIN AN12 [get_ports {c3_ddr3_dqs_p[5]}] #td2_eb1_DQ05_DQS
set_property  PACKAGE_PIN AN11 [get_ports {c3_ddr3_dqs_n[5]}] #td2_eb1_DQ05_DQSn
set_property  PACKAGE_PIN AU12 [get_ports {c3_ddr3_dq[48]}] #td2_eb1_DQ06_D0
set_property  PACKAGE_PIN AU11 [get_ports {c3_ddr3_dq[49]}] #td2_eb1_DQ06_D1
set_property  PACKAGE_PIN AV12 [get_ports {c3_ddr3_dq[50]}] #td2_eb1_DQ06_D2
set_property  PACKAGE_PIN AV11 [get_ports {c3_ddr3_dq[51]}] #td2_eb1_DQ06_D3
set_property  PACKAGE_PIN AY13 [get_ports {c3_ddr3_dq[52]}] #td2_eb1_DQ06_D4
set_property  PACKAGE_PIN AW11 [get_ports {c3_ddr3_dq[53]}] #td2_eb1_DQ06_D5
set_property  PACKAGE_PIN AY11 [get_ports {c3_ddr3_dq[54]}] #td2_eb1_DQ06_D6
set_property  PACKAGE_PIN AW10 [get_ports {c3_ddr3_dq[55]}] #td2_eb1_DQ06_D7
set_property  PACKAGE_PIN AW13 [get_ports {c3_ddr3_dm[6]}] #td2_eb1_DQ06_DM
set_property  PACKAGE_PIN AT10 [get_ports {c3_ddr3_dqs_p[6]}] #td2_eb1_DQ06_DQS
set_property  PACKAGE_PIN AU10 [get_ports {c3_ddr3_dqs_n[6]}] #td2_eb1_DQ06_DQSn
set_property  PACKAGE_PIN BB11 [get_ports {c3_ddr3_dq[56]}] #td2_eb1_DQ07_D0
set_property  PACKAGE_PIN BC11 [get_ports {c3_ddr3_dq[57]}] #td2_eb1_DQ07_D1
set_property  PACKAGE_PIN BC13 [get_ports {c3_ddr3_dq[58]}] #td2_eb1_DQ07_D2
set_property  PACKAGE_PIN BD13 [get_ports {c3_ddr3_dq[59]}] #td2_eb1_DQ07_D3
set_property  PACKAGE_PIN BB12 [get_ports {c3_ddr3_dq[60]}] #td2_eb1_DQ07_D4
set_property  PACKAGE_PIN BC12 [get_ports {c3_ddr3_dq[61]}] #td2_eb1_DQ07_D5
set_property  PACKAGE_PIN BD11 [get_ports {c3_ddr3_dq[62]}] #td2_eb1_DQ07_D6
set_property  PACKAGE_PIN BD10 [get_ports {c3_ddr3_dq[63]}] #td2_eb1_DQ07_D7
set_property  PACKAGE_PIN BA10 [get_ports {c3_ddr3_dm[7]}] #td2_eb1_DQ07_DM
set_property  PACKAGE_PIN AY12 [get_ports {c3_ddr3_dqs_p[7]}] #td2_eb1_DQ07_DQS
set_property  PACKAGE_PIN BA12 [get_ports {c3_ddr3_dqs_n[7]}] #td2_eb1_DQ07_DQSn
set_property  PACKAGE_PIN AM17 [get_ports {c3_calib_complete}] #td2_eb1_LED01
set_property  PACKAGE_PIN AJ15 [get_ports {c3_diagnostic_led}] #td2_eb1_LED02
set_property  PACKAGE_PIN AP15 [get_ports {c3_ddr3_odt}] #td2_eb1_ODT
set_property  PACKAGE_PIN AV16[get_ports {c3_ddr3_ras_n}] #td2_eb1_RASn
set_property  PACKAGE_PIN AP18 [get_ports {c3_ddr3_reset_n}] #td2_eb1_RESETn
set_property  PACKAGE_PIN AR15 [get_ports {reset}] #td2_eb1_SW
set_property  PACKAGE_PIN AW16 [get_ports {c3_ddr3_we_n}] #td2_eb1_WEn

# VREF/DCI constraints for banks related to connector BA1
#   set_property DCI_CASCADE {17 19} [get_iobanks 18]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 18]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 17]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 19]

# VREF/DCI constraints for banks related to connector BA2
#   set_property INTERNAL_VREF {0.90} [get_iobanks 13]
#   set_property DCI_CASCADE {11 13} [get_iobanks 12]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 12]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 11]

# VREF/DCI constraints for banks related to connector BB1
#   set_property INTERNAL_VREF {0.90} [get_iobanks 42]
#   set_property DCI_CASCADE {40 42} [get_iobanks 41]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 41]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 40]

# VREF/DCI constraints for banks related to connector BB2
#   set_property INTERNAL_VREF {0.90} [get_iobanks 16]

# VREF/DCI constraints for banks related to connector TA1
#   set_property DCI_CASCADE {20 22} [get_iobanks 21]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 21]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 22]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 20]

# VREF/DCI constraints for banks related to connector TA2
#   set_property INTERNAL_VREF {0.90} [get_iobanks 34]
#   set_property DCI_CASCADE {34 36} [get_iobanks 35]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 35]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 36]

# VREF/DCI constraints for banks related to connector TB1
#   set_property DCI_CASCADE {37 39} [get_iobanks 38]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 38]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 37]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 39]

# VREF/DCI constraints for banks related to connector TB2
#   set_property INTERNAL_VREF {0.90} [get_iobanks 31]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 33]
#   set_property DCI_CASCADE {31 33} [get_iobanks 32]
#   set_property INTERNAL_VREF {0.90} [get_iobanks 32]
