# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/zynqmpsoc_system_ila_0_0.xci
# IP: The module: 'zynqmpsoc_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/bd_c007.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c007 || ORIG_REF_NAME==bd_c007} -quiet] -quiet

# IP: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/bd_c007_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c007_ila_lib_0 || ORIG_REF_NAME==bd_c007_ila_lib_0} -quiet] -quiet

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c007_ila_lib_0 || ORIG_REF_NAME==bd_c007_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c007_ila_lib_0 || ORIG_REF_NAME==bd_c007_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/bd_c007_ila_lib_0_ooc.xdc

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/bd_c007_ooc.xdc

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/zynqmpsoc_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqmpsoc_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/zynqmpsoc_system_ila_0_0.xci
# IP: The module: 'zynqmpsoc_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/bd_c007.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c007 || ORIG_REF_NAME==bd_c007} -quiet] -quiet

# IP: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/bd_c007_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_c007_ila_lib_0 || ORIG_REF_NAME==bd_c007_ila_lib_0} -quiet] -quiet

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c007_ila_lib_0 || ORIG_REF_NAME==bd_c007_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c007_ila_lib_0 || ORIG_REF_NAME==bd_c007_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/ip/ip_0/bd_c007_ila_lib_0_ooc.xdc

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/bd_0/bd_c007_ooc.xdc

# XDC: /home/jescobedo/repos/juanesp/socs/xilinx-zcu102-xczu9eg/vivado/esp-xilinx-zcu102-xczu9eg.srcs/sources_1/bd/zynqmpsoc/ip/zynqmpsoc_system_ila_0_0/zynqmpsoc_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqmpsoc_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
