# Copyright (c) 2011-2023 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
# TODO: read HLS configuration from device registers instead
EXTRA_CFLAGS ?= -DFFT_FX_WIDTH=32
APPNAME := fft
include $(DRIVERS)/common.mk
