# Copyright (c) 2011-2025 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
# TODO: read HLS configuration from device registers instead
EXTRA_CFLAGS ?=
APPNAME := crypto
include $(DRIVERS)/common.mk
