# Copyright (c) 2011-2025 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
APPNAME := dummy_multicast_yx
EXTRA_CFLAGS ?= -I$(ESP_ROOT)/accelerators/stratus_hls/dummy_stratus/sw/linux/include
include $(DRIVERS)/common.mk
