// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2025.1/1166825 Production Release
//       HLS date: Sun Feb 16 14:04:49 PST 2025
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: gtombesi@corsica
// Generated date: Thu May 08 19:13:31 EDT 2025
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model LeakyreluEngine
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Constructor: sysc_sim_wrapper

CCS_RTL::sysc_sim_wrapper::sysc_sim_wrapper(
   const sc_module_name& nm
)
   : ccs_rtl(
      "ccs_rtl",
      "ccs_wrapper"
   )
   , clk("clk")
   , rst("rst")
   , vec_in_a("vec_in_a")
   , vec_in_b("vec_in_b")
   , vec_out("vec_out")
   , ccs_rtl_SIG_clk("ccs_rtl_SIG_clk")
   , ccs_rtl_SIG_rst("ccs_rtl_SIG_rst")
   , ccs_rtl_SIG_vec_in_a_val("ccs_rtl_SIG_vec_in_a_val")
   , ccs_rtl_SIG_vec_in_a_rdy("ccs_rtl_SIG_vec_in_a_rdy")
   , ccs_rtl_SIG_vec_in_a_msg("ccs_rtl_SIG_vec_in_a_msg")
   , ccs_rtl_SIG_vec_in_b_val("ccs_rtl_SIG_vec_in_b_val")
   , ccs_rtl_SIG_vec_in_b_rdy("ccs_rtl_SIG_vec_in_b_rdy")
   , ccs_rtl_SIG_vec_in_b_msg("ccs_rtl_SIG_vec_in_b_msg")
   , ccs_rtl_SIG_vec_out_val("ccs_rtl_SIG_vec_out_val")
   , ccs_rtl_SIG_vec_out_rdy("ccs_rtl_SIG_vec_out_rdy")
   , ccs_rtl_SIG_vec_out_msg("ccs_rtl_SIG_vec_out_msg")
   , SIG_SC_LOGIC_0("SIG_SC_LOGIC_0")
   , SIG_SC_LOGIC_1("SIG_SC_LOGIC_1")
{
   // Instantiate other modules
   ccs_rtl.clk(ccs_rtl_SIG_clk);
   ccs_rtl.rst(ccs_rtl_SIG_rst);
   ccs_rtl.vec_in_a_val(ccs_rtl_SIG_vec_in_a_val);
   ccs_rtl.vec_in_a_rdy(ccs_rtl_SIG_vec_in_a_rdy);
   ccs_rtl.vec_in_a_msg(ccs_rtl_SIG_vec_in_a_msg);
   ccs_rtl.vec_in_b_val(ccs_rtl_SIG_vec_in_b_val);
   ccs_rtl.vec_in_b_rdy(ccs_rtl_SIG_vec_in_b_rdy);
   ccs_rtl.vec_in_b_msg(ccs_rtl_SIG_vec_in_b_msg);
   ccs_rtl.vec_out_val(ccs_rtl_SIG_vec_out_val);
   ccs_rtl.vec_out_rdy(ccs_rtl_SIG_vec_out_rdy);
   ccs_rtl.vec_out_msg(ccs_rtl_SIG_vec_out_msg);
   
   // Register processes
   SC_METHOD(update_proc);
   sensitive  << clk << rst << vec_in_a.Connections::InBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::val << ccs_rtl_SIG_vec_in_a_rdy << vec_in_a.Connections::InBlocking<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT >::msg << vec_in_b.Connections::InBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::val << ccs_rtl_SIG_vec_in_b_rdy << vec_in_b.Connections::InBlocking<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT >::msg << ccs_rtl_SIG_vec_out_val << vec_out.Connections::OutBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::rdy << ccs_rtl_SIG_vec_out_msg;
   // Other constructor statements
   SIG_SC_LOGIC_0.write(SC_LOGIC_0);
   SIG_SC_LOGIC_1.write(SC_LOGIC_1);
}

// ---------------------------------------------------------------
// Process: SC_METHOD update_proc

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   
   // none.sc_in field_key=clk:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1332:clk:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1332
   sc_logic t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1332; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1333:rst:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1333
   sc_logic t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1333; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1333); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1333); // then write to RTL port
   
   // none.sc_in field_key=vec_in_a:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1334:val:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1345
   sc_logic t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1345; // NPS - LV to hold field
   type_to_vector(vec_in_a.Connections::InBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::val.read(),1,t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1345); // read orig port and type convert
   ccs_rtl_SIG_vec_in_a_val.write(t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1345); // then write to RTL port
   
   // none.sc_out field_key=vec_in_a:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1334:rdy:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1346
   sc_logic t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1346;
   bool d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1346;
   t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1346 = ccs_rtl_SIG_vec_in_a_rdy.read();
   vector_to_type(t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1346, 1, &d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1346);
   vec_in_a.Connections::InBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::rdy.write(d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1346);
   
   // none.sc_in field_key=vec_in_a:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1334:msg:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1347
   sc_lv< 512 > t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1347; // NPS - LV to hold field
   type_to_vector(vec_in_a.Connections::InBlocking<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT >::msg.read(),512,t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1347); // read orig port and type convert
   ccs_rtl_SIG_vec_in_a_msg.write(t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1347); // then write to RTL port
   
   // none.sc_in field_key=vec_in_b:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1348:val:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1353
   sc_logic t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1353; // NPS - LV to hold field
   type_to_vector(vec_in_b.Connections::InBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::val.read(),1,t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1353); // read orig port and type convert
   ccs_rtl_SIG_vec_in_b_val.write(t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1353); // then write to RTL port
   
   // none.sc_out field_key=vec_in_b:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1348:rdy:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1354
   sc_logic t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1354;
   bool d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1354;
   t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1354 = ccs_rtl_SIG_vec_in_b_rdy.read();
   vector_to_type(t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1354, 1, &d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1354);
   vec_in_b.Connections::InBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::rdy.write(d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1354);
   
   // none.sc_in field_key=vec_in_b:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1348:msg:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1355
   sc_lv< 512 > t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1355; // NPS - LV to hold field
   type_to_vector(vec_in_b.Connections::InBlocking<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT >::msg.read(),512,t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1355); // read orig port and type convert
   ccs_rtl_SIG_vec_in_b_msg.write(t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1355); // then write to RTL port
   
   // none.sc_out field_key=vec_out:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1356:val:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1365
   sc_logic t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1365;
   bool d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1365;
   t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1365 = ccs_rtl_SIG_vec_out_val.read();
   vector_to_type(t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1365, 1, &d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1365);
   vec_out.Connections::OutBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::val.write(d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1365);
   
   // none.sc_in field_key=vec_out:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1356:rdy:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1366
   sc_logic t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1366; // NPS - LV to hold field
   type_to_vector(vec_out.Connections::OutBlocking_Ports_abs<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 > >::rdy.read(),1,t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1366); // read orig port and type convert
   ccs_rtl_SIG_vec_out_rdy.write(t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1366); // then write to RTL port
   
   // none.sc_out field_key=vec_out:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1356:msg:159b9fbe-58e9-4abd-a026-d5b455ed1bcd-1367
   sc_lv< 512 > t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1367;
   sc_dt::sc_lv<512 > d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1367;
   if ( ccs_rtl_SIG_vec_out_val.read() == SC_LOGIC_1 ) {
      t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1367 = ccs_rtl_SIG_vec_out_msg.read();
      vector_to_type(t_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1367, 512, &d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1367);
      vec_out.Connections::OutBlocking<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT >::msg.write(d_159b9fbe_58e9_4abd_a026_d5b455ed1bcd_1367);
   }
}
