// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.h
//
//    HLS version: 2025.1/1166825 Production Release
//       HLS date: Sun Feb 16 14:04:49 PST 2025
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: gtombesi@corsica
// Generated date: Thu May 08 19:13:31 EDT 2025
//
// ----------------------------------------------------------------------------
#ifndef INCLUDED_SYSC_SIM_WRAPPER_H
#define INCLUDED_SYSC_SIM_WRAPPER_H
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model LeakyreluEngine
// -------------------------------------
// 

#ifndef TO_QUOTED_STRING
#define TO_QUOTED_STRING(x) TO_QUOTED_STRING1(x)
#define TO_QUOTED_STRING1(x) #x
#endif
extern double __scv_hold_time;


#ifndef SC_USE_STD_STRING
#define SC_USE_STD_STRING
#endif

#include "../../../../inc/leakyrelu_com.h"
#include <systemc.h>
#include <mc_stall_ctrl.h>
#include <mc_scv_trans.h>
#include "mc_dut_wrapper.h"


namespace CCS_RTL {
   class sysc_sim_wrapper : public sc_module
   {
   public:
      // Module instance pointers
      HDL::ccs_DUT_wrapper ccs_rtl;
      
      // Interface Ports
      sc_core::sc_in<bool > clk;
      sc_core::sc_in<bool > rst;
      Connections::In<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT > vec_in_a;
      Connections::In<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT > vec_in_b;
      Connections::Out<array_t<ac_fixed<32, 16, true, AC_TRN, AC_WRAP >, 16 >, Connections::SYN_PORT > vec_out;
      
      // Named Objects
      
      // Data objects
      sc_signal< bool >                          ccs_rtl_SIG_clk;
      sc_signal< sc_logic >                      ccs_rtl_SIG_rst;
      sc_signal< sc_logic >                      ccs_rtl_SIG_vec_in_a_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_vec_in_a_rdy;
      sc_signal< sc_lv<512> >                    ccs_rtl_SIG_vec_in_a_msg;
      sc_signal< sc_logic >                      ccs_rtl_SIG_vec_in_b_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_vec_in_b_rdy;
      sc_signal< sc_lv<512> >                    ccs_rtl_SIG_vec_in_b_msg;
      sc_signal< sc_logic >                      ccs_rtl_SIG_vec_out_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_vec_out_rdy;
      sc_signal< sc_lv<512> >                    ccs_rtl_SIG_vec_out_msg;
      sc_signal< sc_logic >                      SIG_SC_LOGIC_0;
      sc_signal< sc_logic >                      SIG_SC_LOGIC_1;
      
      // Declare processes (SC_METHOD and SC_THREAD)
      void update_proc();
      
      // Constructor
      SC_HAS_PROCESS(sysc_sim_wrapper);
      sysc_sim_wrapper(
         const sc_module_name& nm
      );
      ~sysc_sim_wrapper()
      {
      }
      
      // C++ class functions
   };
} // end namespace CCS_RTL
#endif //INCLUDED_SYSC_SIM_WRAPPER_H
