#ifndef _PRECISION_TEST_FPDATA_H_
#define _PRECISION_TEST_FPDATA_H_

// Script version 1.3

// SMALL_NUM_INSTANCE  1
// MEDIUM_NUM_INSTANCE 1
// FAST_NUM_INSTANCE   1

//
// LAYER 1
//

// LAYER1-SMALL-Team:      1d
// LAYER1-SMALL-uArch:     MEDIUM
// LAYER1-SMALL-Inst:      1
// LAYER1-SMALL-Area:      0.23973448
// LAYER1-SMALL-EffLat:    2.1146
// LAYER1-SMALL-GitRev:    24417d1a6ed7e2fb773167725812769eb763b4ff

// LAYER1-MEDIUM-Team:     1d
// LAYER1-MEDIUM-uArch:    MEDIUM
// LAYER1-MEDIUM-Inst:     1
// LAYER1-MEDIUM-Area:     0.23973448
// LAYER1-MEDIUM-EffLat:   2.1146
// LAYER1-MEDIUM-GitRev:   24417d1a6ed7e2fb773167725812769eb763b4ff

// LAYER1-FAST-Team:       1d
// LAYER1-FAST-uArch:      MEDIUM
// LAYER1-FAST-Inst:       1
// LAYER1-FAST-Area:       0.23973448
// LAYER1-FAST-EffLat:     2.1146
// LAYER1-FAST-GitRev:     24417d1a6ed7e2fb773167725812769eb763b4ff

//
// Layer 1
//

#define SMALL_LAYER_FPDATA_WL_1     32
#define SMALL_LAYER_W_FPDATA_WL_1   32
#define SMALL_LAYER_FPDATA_IL_1     17
#define SMALL_LAYER_W_FPDATA_IL_1   16

#define MEDIUM_LAYER_FPDATA_WL_1    32
#define MEDIUM_LAYER_W_FPDATA_WL_1  32
#define MEDIUM_LAYER_FPDATA_IL_1    17
#define MEDIUM_LAYER_W_FPDATA_IL_1  16

#define FAST_LAYER_FPDATA_WL_1      32
#define FAST_LAYER_W_FPDATA_WL_1    32
#define FAST_LAYER_FPDATA_IL_1      17
#define FAST_LAYER_W_FPDATA_IL_1    16

#ifdef TARGET_LAYER_1
// This is the target layer
#define LAYER_FPDATA_WL_1     FPDATA_WL
#define LAYER_W_FPDATA_WL_1   W_FPDATA_WL
#define LAYER_FPDATA_IL_1     FPDATA_IL
#define LAYER_W_FPDATA_IL_1   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_1     SMALL_LAYER_FPDATA_WL_1
#define LAYER_W_FPDATA_WL_1   SMALL_LAYER_W_FPDATA_WL_1
#define LAYER_FPDATA_IL_1     SMALL_LAYER_FPDATA_IL_1
#define LAYER_W_FPDATA_IL_1   SMALL_LAYER_W_FPDATA_IL_1
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_1     MEDIUM_LAYER_FPDATA_WL_1
#define LAYER_W_FPDATA_WL_1   MEDIUM_LAYER_W_FPDATA_WL_1
#define LAYER_FPDATA_IL_1     MEDIUM_LAYER_FPDATA_IL_1
#define LAYER_W_FPDATA_IL_1   MEDIUM_LAYER_W_FPDATA_IL_1
#else
#define LAYER_FPDATA_WL_1     FAST_LAYER_FPDATA_WL_1
#define LAYER_W_FPDATA_WL_1   FAST_LAYER_W_FPDATA_WL_1
#define LAYER_FPDATA_IL_1     FAST_LAYER_FPDATA_IL_1
#define LAYER_W_FPDATA_IL_1   FAST_LAYER_W_FPDATA_IL_1
#endif
#endif // TARGET_LAYER_1

//
// LAYER 2
//

// LAYER2-SMALL-Team:      2d
// LAYER2-SMALL-uArch:     MEDIUM
// LAYER2-SMALL-Inst:      1
// LAYER2-SMALL-Area:      0.23973448
// LAYER2-SMALL-EffLat:    1.88905
// LAYER2-SMALL-GitRev:    340d76a650de337b42cc4a385c152c0fda2ddf07

// LAYER2-MEDIUM-Team:     2d
// LAYER2-MEDIUM-uArch:    MEDIUM
// LAYER2-MEDIUM-Inst:     1
// LAYER2-MEDIUM-Area:     0.23973448
// LAYER2-MEDIUM-EffLat:   1.88905
// LAYER2-MEDIUM-GitRev:   340d76a650de337b42cc4a385c152c0fda2ddf07

// LAYER2-FAST-Team:       2d
// LAYER2-FAST-uArch:      MEDIUM
// LAYER2-FAST-Inst:       1
// LAYER2-FAST-Area:       0.23973448
// LAYER2-FAST-EffLat:     1.88905
// LAYER2-FAST-GitRev:     340d76a650de337b42cc4a385c152c0fda2ddf07

//
// Layer 2
//

#define SMALL_LAYER_FPDATA_WL_2     32
#define SMALL_LAYER_W_FPDATA_WL_2   32
#define SMALL_LAYER_FPDATA_IL_2     17
#define SMALL_LAYER_W_FPDATA_IL_2   16

#define MEDIUM_LAYER_FPDATA_WL_2    32
#define MEDIUM_LAYER_W_FPDATA_WL_2  32
#define MEDIUM_LAYER_FPDATA_IL_2    17
#define MEDIUM_LAYER_W_FPDATA_IL_2  16

#define FAST_LAYER_FPDATA_WL_2      32
#define FAST_LAYER_W_FPDATA_WL_2    32
#define FAST_LAYER_FPDATA_IL_2      17
#define FAST_LAYER_W_FPDATA_IL_2    16

#ifdef TARGET_LAYER_2
// This is the target layer
#define LAYER_FPDATA_WL_2     FPDATA_WL
#define LAYER_W_FPDATA_WL_2   W_FPDATA_WL
#define LAYER_FPDATA_IL_2     FPDATA_IL
#define LAYER_W_FPDATA_IL_2   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_2     SMALL_LAYER_FPDATA_WL_2
#define LAYER_W_FPDATA_WL_2   SMALL_LAYER_W_FPDATA_WL_2
#define LAYER_FPDATA_IL_2     SMALL_LAYER_FPDATA_IL_2
#define LAYER_W_FPDATA_IL_2   SMALL_LAYER_W_FPDATA_IL_2
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_2     MEDIUM_LAYER_FPDATA_WL_2
#define LAYER_W_FPDATA_WL_2   MEDIUM_LAYER_W_FPDATA_WL_2
#define LAYER_FPDATA_IL_2     MEDIUM_LAYER_FPDATA_IL_2
#define LAYER_W_FPDATA_IL_2   MEDIUM_LAYER_W_FPDATA_IL_2
#else
#define LAYER_FPDATA_WL_2     FAST_LAYER_FPDATA_WL_2
#define LAYER_W_FPDATA_WL_2   FAST_LAYER_W_FPDATA_WL_2
#define LAYER_FPDATA_IL_2     FAST_LAYER_FPDATA_IL_2
#define LAYER_W_FPDATA_IL_2   FAST_LAYER_W_FPDATA_IL_2
#endif
#endif // TARGET_LAYER_2

//
// LAYER 3
//

// LAYER3-SMALL-Team:      3d
// LAYER3-SMALL-uArch:     MEDIUM
// LAYER3-SMALL-Inst:      1
// LAYER3-SMALL-Area:      0.23973448
// LAYER3-SMALL-EffLat:    7.30877
// LAYER3-SMALL-GitRev:    1eb8dd568133105325fdf8421bd8879e3a693fad

// LAYER3-MEDIUM-Team:     3d
// LAYER3-MEDIUM-uArch:    MEDIUM
// LAYER3-MEDIUM-Inst:     1
// LAYER3-MEDIUM-Area:     0.23973448
// LAYER3-MEDIUM-EffLat:   7.30877
// LAYER3-MEDIUM-GitRev:   1eb8dd568133105325fdf8421bd8879e3a693fad

// LAYER3-FAST-Team:       3d
// LAYER3-FAST-uArch:      MEDIUM
// LAYER3-FAST-Inst:       1
// LAYER3-FAST-Area:       0.23973448
// LAYER3-FAST-EffLat:     7.30877
// LAYER3-FAST-GitRev:     1eb8dd568133105325fdf8421bd8879e3a693fad

//
// Layer 3
//

#define SMALL_LAYER_FPDATA_WL_3     32
#define SMALL_LAYER_W_FPDATA_WL_3   32
#define SMALL_LAYER_FPDATA_IL_3     17
#define SMALL_LAYER_W_FPDATA_IL_3   16

#define MEDIUM_LAYER_FPDATA_WL_3    32
#define MEDIUM_LAYER_W_FPDATA_WL_3  32
#define MEDIUM_LAYER_FPDATA_IL_3    17
#define MEDIUM_LAYER_W_FPDATA_IL_3  16

#define FAST_LAYER_FPDATA_WL_3      32
#define FAST_LAYER_W_FPDATA_WL_3    32
#define FAST_LAYER_FPDATA_IL_3      17
#define FAST_LAYER_W_FPDATA_IL_3    16

#ifdef TARGET_LAYER_3
// This is the target layer
#define LAYER_FPDATA_WL_3     FPDATA_WL
#define LAYER_W_FPDATA_WL_3   W_FPDATA_WL
#define LAYER_FPDATA_IL_3     FPDATA_IL
#define LAYER_W_FPDATA_IL_3   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_3     SMALL_LAYER_FPDATA_WL_3
#define LAYER_W_FPDATA_WL_3   SMALL_LAYER_W_FPDATA_WL_3
#define LAYER_FPDATA_IL_3     SMALL_LAYER_FPDATA_IL_3
#define LAYER_W_FPDATA_IL_3   SMALL_LAYER_W_FPDATA_IL_3
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_3     MEDIUM_LAYER_FPDATA_WL_3
#define LAYER_W_FPDATA_WL_3   MEDIUM_LAYER_W_FPDATA_WL_3
#define LAYER_FPDATA_IL_3     MEDIUM_LAYER_FPDATA_IL_3
#define LAYER_W_FPDATA_IL_3   MEDIUM_LAYER_W_FPDATA_IL_3
#else
#define LAYER_FPDATA_WL_3     FAST_LAYER_FPDATA_WL_3
#define LAYER_W_FPDATA_WL_3   FAST_LAYER_W_FPDATA_WL_3
#define LAYER_FPDATA_IL_3     FAST_LAYER_FPDATA_IL_3
#define LAYER_W_FPDATA_IL_3   FAST_LAYER_W_FPDATA_IL_3
#endif
#endif // TARGET_LAYER_3

//
// LAYER 4
//

// LAYER4-SMALL-Team:      this
// LAYER4-SMALL-uArch:     this
// LAYER4-SMALL-Inst:      this
// LAYER4-SMALL-Area:      this
// LAYER4-SMALL-EffLat:    this
// LAYER4-SMALL-GitRev:    this

// LAYER4-MEDIUM-Team:     this
// LAYER4-MEDIUM-uArch:    this
// LAYER4-MEDIUM-Inst:     this
// LAYER4-MEDIUM-Area:     this
// LAYER4-MEDIUM-EffLat:   this
// LAYER4-MEDIUM-GitRev:   this

// LAYER4-FAST-Team:       this
// LAYER4-FAST-uArch:      this
// LAYER4-FAST-Inst:       this
// LAYER4-FAST-Area:       this
// LAYER4-FAST-EffLat:     this
// LAYER4-FAST-GitRev:     this

//
// Layer 4
//

#define SMALL_LAYER_FPDATA_WL_4     this
#define SMALL_LAYER_W_FPDATA_WL_4   this
#define SMALL_LAYER_FPDATA_IL_4     this
#define SMALL_LAYER_W_FPDATA_IL_4   this

#define MEDIUM_LAYER_FPDATA_WL_4    this
#define MEDIUM_LAYER_W_FPDATA_WL_4  this
#define MEDIUM_LAYER_FPDATA_IL_4    this
#define MEDIUM_LAYER_W_FPDATA_IL_4  this

#define FAST_LAYER_FPDATA_WL_4      this
#define FAST_LAYER_W_FPDATA_WL_4    this
#define FAST_LAYER_FPDATA_IL_4      this
#define FAST_LAYER_W_FPDATA_IL_4    this

#ifdef TARGET_LAYER_4
// This is the target layer
#define LAYER_FPDATA_WL_4     FPDATA_WL
#define LAYER_W_FPDATA_WL_4   W_FPDATA_WL
#define LAYER_FPDATA_IL_4     FPDATA_IL
#define LAYER_W_FPDATA_IL_4   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_4     SMALL_LAYER_FPDATA_WL_4
#define LAYER_W_FPDATA_WL_4   SMALL_LAYER_W_FPDATA_WL_4
#define LAYER_FPDATA_IL_4     SMALL_LAYER_FPDATA_IL_4
#define LAYER_W_FPDATA_IL_4   SMALL_LAYER_W_FPDATA_IL_4
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_4     MEDIUM_LAYER_FPDATA_WL_4
#define LAYER_W_FPDATA_WL_4   MEDIUM_LAYER_W_FPDATA_WL_4
#define LAYER_FPDATA_IL_4     MEDIUM_LAYER_FPDATA_IL_4
#define LAYER_W_FPDATA_IL_4   MEDIUM_LAYER_W_FPDATA_IL_4
#else
#define LAYER_FPDATA_WL_4     FAST_LAYER_FPDATA_WL_4
#define LAYER_W_FPDATA_WL_4   FAST_LAYER_W_FPDATA_WL_4
#define LAYER_FPDATA_IL_4     FAST_LAYER_FPDATA_IL_4
#define LAYER_W_FPDATA_IL_4   FAST_LAYER_W_FPDATA_IL_4
#endif
#endif // TARGET_LAYER_4

//
// LAYER 5
//

// LAYER5-SMALL-Team:      5x
// LAYER5-SMALL-uArch:     FAST
// LAYER5-SMALL-Inst:      1
// LAYER5-SMALL-Area:      0.5
// LAYER5-SMALL-EffLat:    58.619
// LAYER5-SMALL-GitRev:    fd69a351a5aa21fdaceb6e7eb0013156854d3e93

// LAYER5-MEDIUM-Team:     5x
// LAYER5-MEDIUM-uArch:    FAST
// LAYER5-MEDIUM-Inst:     1
// LAYER5-MEDIUM-Area:     0.5
// LAYER5-MEDIUM-EffLat:   58.619
// LAYER5-MEDIUM-GitRev:   fd69a351a5aa21fdaceb6e7eb0013156854d3e93

// LAYER5-FAST-Team:       5x
// LAYER5-FAST-uArch:      FAST
// LAYER5-FAST-Inst:       1
// LAYER5-FAST-Area:       0.5
// LAYER5-FAST-EffLat:     58.619
// LAYER5-FAST-GitRev:     fd69a351a5aa21fdaceb6e7eb0013156854d3e93

//
// Layer 5
//

#define SMALL_LAYER_FPDATA_WL_5     32
#define SMALL_LAYER_W_FPDATA_WL_5   32
#define SMALL_LAYER_FPDATA_IL_5     17
#define SMALL_LAYER_W_FPDATA_IL_5   16

#define MEDIUM_LAYER_FPDATA_WL_5    32
#define MEDIUM_LAYER_W_FPDATA_WL_5  32
#define MEDIUM_LAYER_FPDATA_IL_5    17
#define MEDIUM_LAYER_W_FPDATA_IL_5  16

#define FAST_LAYER_FPDATA_WL_5      32
#define FAST_LAYER_W_FPDATA_WL_5    32
#define FAST_LAYER_FPDATA_IL_5      17
#define FAST_LAYER_W_FPDATA_IL_5    16

#ifdef TARGET_LAYER_5
// This is the target layer
#define LAYER_FPDATA_WL_5     FPDATA_WL
#define LAYER_W_FPDATA_WL_5   W_FPDATA_WL
#define LAYER_FPDATA_IL_5     FPDATA_IL
#define LAYER_W_FPDATA_IL_5   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_5     SMALL_LAYER_FPDATA_WL_5
#define LAYER_W_FPDATA_WL_5   SMALL_LAYER_W_FPDATA_WL_5
#define LAYER_FPDATA_IL_5     SMALL_LAYER_FPDATA_IL_5
#define LAYER_W_FPDATA_IL_5   SMALL_LAYER_W_FPDATA_IL_5
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_5     MEDIUM_LAYER_FPDATA_WL_5
#define LAYER_W_FPDATA_WL_5   MEDIUM_LAYER_W_FPDATA_WL_5
#define LAYER_FPDATA_IL_5     MEDIUM_LAYER_FPDATA_IL_5
#define LAYER_W_FPDATA_IL_5   MEDIUM_LAYER_W_FPDATA_IL_5
#else
#define LAYER_FPDATA_WL_5     FAST_LAYER_FPDATA_WL_5
#define LAYER_W_FPDATA_WL_5   FAST_LAYER_W_FPDATA_WL_5
#define LAYER_FPDATA_IL_5     FAST_LAYER_FPDATA_IL_5
#define LAYER_W_FPDATA_IL_5   FAST_LAYER_W_FPDATA_IL_5
#endif
#endif // TARGET_LAYER_5

//
// LAYER 6
//

// LAYER6-SMALL-Team:      6x
// LAYER6-SMALL-uArch:     FAST
// LAYER6-SMALL-Inst:      1
// LAYER6-SMALL-Area:      0.5
// LAYER6-SMALL-EffLat:    58.619
// LAYER6-SMALL-GitRev:    fd69a351a5aa21fdaceb6e7eb0013156854d3e93

// LAYER6-MEDIUM-Team:     6x
// LAYER6-MEDIUM-uArch:    FAST
// LAYER6-MEDIUM-Inst:     1
// LAYER6-MEDIUM-Area:     0.5
// LAYER6-MEDIUM-EffLat:   58.619
// LAYER6-MEDIUM-GitRev:   fd69a351a5aa21fdaceb6e7eb0013156854d3e93

// LAYER6-FAST-Team:       6x
// LAYER6-FAST-uArch:      FAST
// LAYER6-FAST-Inst:       1
// LAYER6-FAST-Area:       0.5
// LAYER6-FAST-EffLat:     58.619
// LAYER6-FAST-GitRev:     fd69a351a5aa21fdaceb6e7eb0013156854d3e93

//
// Layer 6
//

#define SMALL_LAYER_FPDATA_WL_6     32
#define SMALL_LAYER_W_FPDATA_WL_6   32
#define SMALL_LAYER_FPDATA_IL_6     17
#define SMALL_LAYER_W_FPDATA_IL_6   16

#define MEDIUM_LAYER_FPDATA_WL_6    32
#define MEDIUM_LAYER_W_FPDATA_WL_6  32
#define MEDIUM_LAYER_FPDATA_IL_6    17
#define MEDIUM_LAYER_W_FPDATA_IL_6  16

#define FAST_LAYER_FPDATA_WL_6      32
#define FAST_LAYER_W_FPDATA_WL_6    32
#define FAST_LAYER_FPDATA_IL_6      17
#define FAST_LAYER_W_FPDATA_IL_6    16

#ifdef TARGET_LAYER_6
// This is the target layer
#define LAYER_FPDATA_WL_6     FPDATA_WL
#define LAYER_W_FPDATA_WL_6   W_FPDATA_WL
#define LAYER_FPDATA_IL_6     FPDATA_IL
#define LAYER_W_FPDATA_IL_6   W_FPDATA_IL
#else
#if defined(SMALL)
#define LAYER_FPDATA_WL_6     SMALL_LAYER_FPDATA_WL_6
#define LAYER_W_FPDATA_WL_6   SMALL_LAYER_W_FPDATA_WL_6
#define LAYER_FPDATA_IL_6     SMALL_LAYER_FPDATA_IL_6
#define LAYER_W_FPDATA_IL_6   SMALL_LAYER_W_FPDATA_IL_6
#elif defined(MEDIUM)
#define LAYER_FPDATA_WL_6     MEDIUM_LAYER_FPDATA_WL_6
#define LAYER_W_FPDATA_WL_6   MEDIUM_LAYER_W_FPDATA_WL_6
#define LAYER_FPDATA_IL_6     MEDIUM_LAYER_FPDATA_IL_6
#define LAYER_W_FPDATA_IL_6   MEDIUM_LAYER_W_FPDATA_IL_6
#else
#define LAYER_FPDATA_WL_6     FAST_LAYER_FPDATA_WL_6
#define LAYER_W_FPDATA_WL_6   FAST_LAYER_W_FPDATA_WL_6
#define LAYER_FPDATA_IL_6     FAST_LAYER_FPDATA_IL_6
#define LAYER_W_FPDATA_IL_6   FAST_LAYER_W_FPDATA_IL_6
#endif
#endif // TARGET_LAYER_6

#endif // _PRECISION_TEST_FPDATA_H_
