------------------------------------------------------------------------------
--  Copyright (C) 2015-2017, System Level Design (SLD) @ Columbia University
-----------------------------------------------------------------------------
-- Entities:    <accelerator>_rtl
-- File:        accelerators.vhd
-- Authors:     Paolo Mantovani
--              Christian Pilato
-- Description: SLD accelerators instance based on HLS configuration
------------------------------------------------------------------------------

-- <<accelerators-entities>>
