# Copyright (c) 2011-2021 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
EXTRA_CFLAGS ?= -I$(ESP_ROOT)/accelerators/stratus_hls/gemm_stratus/sw/linux/include \
	-I$(ESP_ROOT)/accelerators/stratus_hls/conv2d_stratus/sw/linux/include
APPNAME := dwarf_nn
include $(DRIVERS)/common.mk
