# Copyright (c) 2011-2023 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
EXTRA_CFLAGS ?= -I$(ESP_ROOT)/accelerators/stratus_hls/fft_stratus/sw/linux/include
APPNAME := multifft_mon
include $(DRIVERS)/common.mk
