# Copyright (c) 2011-2023 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
# FPGA and Dev Board used in Design
PART=xcvu37p
PACKAGE=fsvh2892
PROTOBOARD=xilinx.com:vcu128:part0:1.0
SPEED=2L-e
