# Copyright (c) 2011-2023 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
# FPGA and Dev Board used in Design
PART=xcvu9p
PACKAGE=flga2104
PROTOBOARD=xilinx.com:vcu118:part0:2.3
SPEED=2L-e
