#!/bin/sh
# Copyright (c) 2011-2023 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0

# below comments pertain to content in S64esp
# start (per DDR node): contig_alloc starting address
# size (per DDR node): contig_alloc region size
# chunk_log: default accelerator page

# Default values:
#
#               #DDR0#
# 0x40000000 -> \----\
#               |    |
#               |    |
#               |    | -> reserved (software only)
#               |    |
#               |    |
# 0x5bffffff -> \    | <- 0x5bfffff0 -> Leon3 stack pointer
#               |    |
#               |    | -> shared (software and accellerators)
#               |    |
# 0x5fffffff -> \----\

#               #DDR1#
# 0x60000000 -> \----\
#               |    |
#               |    |
#               |    |
#               |    |
#               |    | -> shared (software and accellerators)
#               |    |
#               |    |
#               |    |
#               |    |
# 0x7fffffff -> \----\
#
# accelerator page: 2^20B -> 1MB

# Adjust these settings in the system if necessary

cd /opt/drivers
for K in `ls *.ko`; do
   insmod $K;
done

lsmod
