# Copyright (c) 2011-2023 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
# FPGA and Dev Board used in Design
PART=xczu9eg
PACKAGE=ffvb1156
PROTOBOARD=xilinx.com:zcu102:part0:3.3
SPEED=2-e
