FX_WIDTH ?= 64
#FX32_IL   = 14
FX32_IL   = 14
FX64_IL   = 42

CXXFLAGS += -std=c++11
CXXFLAGS += -DFX_WIDTH=$(FX_WIDTH)
CXXFLAGS += -DFX32_IL=$(FX32_IL)
CXXFLAGS += -DFX64_IL=$(FX64_IL)

include ../../../common/systemc.mk
