// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2025.1/1166825 Production Release
//       HLS date: Sun Feb 16 14:04:49 PST 2025
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: gtombesi@corsica
// Generated date: Thu May 08 18:59:15 EDT 2025
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model LeakyreluConfig
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Constructor: sysc_sim_wrapper

CCS_RTL::sysc_sim_wrapper::sysc_sim_wrapper(
   const sc_module_name& nm
)
   : ccs_rtl(
      "ccs_rtl",
      "ccs_wrapper"
   )
   , clk("clk")
   , rst("rst")
   , conf_info("conf_info")
   , conf_info_ctrl_dma2acc("conf_info_ctrl_dma2acc")
   , conf_info_ctrl_plm2vec("conf_info_ctrl_plm2vec")
   , conf_info_ctrl_acc2dma("conf_info_ctrl_acc2dma")
   , ccs_rtl_SIG_clk("ccs_rtl_SIG_clk")
   , ccs_rtl_SIG_rst("ccs_rtl_SIG_rst")
   , ccs_rtl_SIG_conf_info_val("ccs_rtl_SIG_conf_info_val")
   , ccs_rtl_SIG_conf_info_rdy("ccs_rtl_SIG_conf_info_rdy")
   , ccs_rtl_SIG_conf_info_msg("ccs_rtl_SIG_conf_info_msg")
   , ccs_rtl_SIG_conf_info_ctrl_dma2acc_val("ccs_rtl_SIG_conf_info_ctrl_dma2acc_val")
   , ccs_rtl_SIG_conf_info_ctrl_dma2acc_rdy("ccs_rtl_SIG_conf_info_ctrl_dma2acc_rdy")
   , ccs_rtl_SIG_conf_info_ctrl_dma2acc_msg("ccs_rtl_SIG_conf_info_ctrl_dma2acc_msg")
   , ccs_rtl_SIG_conf_info_ctrl_plm2vec_val("ccs_rtl_SIG_conf_info_ctrl_plm2vec_val")
   , ccs_rtl_SIG_conf_info_ctrl_plm2vec_rdy("ccs_rtl_SIG_conf_info_ctrl_plm2vec_rdy")
   , ccs_rtl_SIG_conf_info_ctrl_plm2vec_msg("ccs_rtl_SIG_conf_info_ctrl_plm2vec_msg")
   , ccs_rtl_SIG_conf_info_ctrl_acc2dma_val("ccs_rtl_SIG_conf_info_ctrl_acc2dma_val")
   , ccs_rtl_SIG_conf_info_ctrl_acc2dma_rdy("ccs_rtl_SIG_conf_info_ctrl_acc2dma_rdy")
   , ccs_rtl_SIG_conf_info_ctrl_acc2dma_msg("ccs_rtl_SIG_conf_info_ctrl_acc2dma_msg")
   , SIG_SC_LOGIC_0("SIG_SC_LOGIC_0")
   , SIG_SC_LOGIC_1("SIG_SC_LOGIC_1")
{
   // Instantiate other modules
   ccs_rtl.clk(ccs_rtl_SIG_clk);
   ccs_rtl.rst(ccs_rtl_SIG_rst);
   ccs_rtl.conf_info_val(ccs_rtl_SIG_conf_info_val);
   ccs_rtl.conf_info_rdy(ccs_rtl_SIG_conf_info_rdy);
   ccs_rtl.conf_info_msg(ccs_rtl_SIG_conf_info_msg);
   ccs_rtl.conf_info_ctrl_dma2acc_val(ccs_rtl_SIG_conf_info_ctrl_dma2acc_val);
   ccs_rtl.conf_info_ctrl_dma2acc_rdy(ccs_rtl_SIG_conf_info_ctrl_dma2acc_rdy);
   ccs_rtl.conf_info_ctrl_dma2acc_msg(ccs_rtl_SIG_conf_info_ctrl_dma2acc_msg);
   ccs_rtl.conf_info_ctrl_plm2vec_val(ccs_rtl_SIG_conf_info_ctrl_plm2vec_val);
   ccs_rtl.conf_info_ctrl_plm2vec_rdy(ccs_rtl_SIG_conf_info_ctrl_plm2vec_rdy);
   ccs_rtl.conf_info_ctrl_plm2vec_msg(ccs_rtl_SIG_conf_info_ctrl_plm2vec_msg);
   ccs_rtl.conf_info_ctrl_acc2dma_val(ccs_rtl_SIG_conf_info_ctrl_acc2dma_val);
   ccs_rtl.conf_info_ctrl_acc2dma_rdy(ccs_rtl_SIG_conf_info_ctrl_acc2dma_rdy);
   ccs_rtl.conf_info_ctrl_acc2dma_msg(ccs_rtl_SIG_conf_info_ctrl_acc2dma_msg);
   
   // Register processes
   SC_METHOD(update_proc);
   sensitive  << clk << rst << conf_info.Connections::InBlocking_Ports_abs<conf_info_t >::val << ccs_rtl_SIG_conf_info_rdy << conf_info.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg << ccs_rtl_SIG_conf_info_ctrl_dma2acc_val << conf_info_ctrl_dma2acc.Connections::OutBlocking_Ports_abs<conf_info_t >::rdy << ccs_rtl_SIG_conf_info_ctrl_dma2acc_msg << ccs_rtl_SIG_conf_info_ctrl_plm2vec_val << conf_info_ctrl_plm2vec.Connections::OutBlocking_Ports_abs<conf_info_t >::rdy << ccs_rtl_SIG_conf_info_ctrl_plm2vec_msg << ccs_rtl_SIG_conf_info_ctrl_acc2dma_val << conf_info_ctrl_acc2dma.Connections::OutBlocking_Ports_abs<conf_info_t >::rdy << ccs_rtl_SIG_conf_info_ctrl_acc2dma_msg;
   // Other constructor statements
   SIG_SC_LOGIC_0.write(SC_LOGIC_0);
   SIG_SC_LOGIC_1.write(SC_LOGIC_1);
}

// ---------------------------------------------------------------
// Process: SC_METHOD update_proc

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   
   // none.sc_in field_key=clk:cdd28f78-e43e-4559-98cc-917b784fdd77-1315:clk:cdd28f78-e43e-4559-98cc-917b784fdd77-1315
   sc_logic t_cdd28f78_e43e_4559_98cc_917b784fdd77_1315; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:cdd28f78-e43e-4559-98cc-917b784fdd77-1316:rst:cdd28f78-e43e-4559-98cc-917b784fdd77-1316
   sc_logic t_cdd28f78_e43e_4559_98cc_917b784fdd77_1316; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_cdd28f78_e43e_4559_98cc_917b784fdd77_1316); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1316); // then write to RTL port
   
   // none.sc_in field_key=conf_info:cdd28f78-e43e-4559-98cc-917b784fdd77-1317:val:cdd28f78-e43e-4559-98cc-917b784fdd77-1328
   sc_logic t_cdd28f78_e43e_4559_98cc_917b784fdd77_1328; // NPS - LV to hold field
   type_to_vector(conf_info.Connections::InBlocking_Ports_abs<conf_info_t >::val.read(),1,t_cdd28f78_e43e_4559_98cc_917b784fdd77_1328); // read orig port and type convert
   ccs_rtl_SIG_conf_info_val.write(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1328); // then write to RTL port
   
   // none.sc_out field_key=conf_info:cdd28f78-e43e-4559-98cc-917b784fdd77-1317:rdy:cdd28f78-e43e-4559-98cc-917b784fdd77-1329
   sc_logic t_cdd28f78_e43e_4559_98cc_917b784fdd77_1329;
   bool d_cdd28f78_e43e_4559_98cc_917b784fdd77_1329;
   t_cdd28f78_e43e_4559_98cc_917b784fdd77_1329 = ccs_rtl_SIG_conf_info_rdy.read();
   vector_to_type(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1329, 1, &d_cdd28f78_e43e_4559_98cc_917b784fdd77_1329);
   conf_info.Connections::InBlocking_Ports_abs<conf_info_t >::rdy.write(d_cdd28f78_e43e_4559_98cc_917b784fdd77_1329);
   
   // none.sc_in field_key=conf_info:cdd28f78-e43e-4559-98cc-917b784fdd77-1317:msg:cdd28f78-e43e-4559-98cc-917b784fdd77-1330
   sc_lv< 160 > t_cdd28f78_e43e_4559_98cc_917b784fdd77_1330; // NPS - LV to hold field
   type_to_vector(conf_info.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg.read(),160,t_cdd28f78_e43e_4559_98cc_917b784fdd77_1330); // read orig port and type convert
   ccs_rtl_SIG_conf_info_msg.write(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1330); // then write to RTL port
   
   // none.sc_out field_key=conf_info_ctrl_dma2acc:cdd28f78-e43e-4559-98cc-917b784fdd77-1331:val:cdd28f78-e43e-4559-98cc-917b784fdd77-1340
   sc_logic t_cdd28f78_e43e_4559_98cc_917b784fdd77_1340;
   bool d_cdd28f78_e43e_4559_98cc_917b784fdd77_1340;
   t_cdd28f78_e43e_4559_98cc_917b784fdd77_1340 = ccs_rtl_SIG_conf_info_ctrl_dma2acc_val.read();
   vector_to_type(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1340, 1, &d_cdd28f78_e43e_4559_98cc_917b784fdd77_1340);
   conf_info_ctrl_dma2acc.Connections::OutBlocking_Ports_abs<conf_info_t >::val.write(d_cdd28f78_e43e_4559_98cc_917b784fdd77_1340);
   
   // none.sc_in field_key=conf_info_ctrl_dma2acc:cdd28f78-e43e-4559-98cc-917b784fdd77-1331:rdy:cdd28f78-e43e-4559-98cc-917b784fdd77-1341
   sc_logic t_cdd28f78_e43e_4559_98cc_917b784fdd77_1341; // NPS - LV to hold field
   type_to_vector(conf_info_ctrl_dma2acc.Connections::OutBlocking_Ports_abs<conf_info_t >::rdy.read(),1,t_cdd28f78_e43e_4559_98cc_917b784fdd77_1341); // read orig port and type convert
   ccs_rtl_SIG_conf_info_ctrl_dma2acc_rdy.write(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1341); // then write to RTL port
   
   // none.sc_out field_key=conf_info_ctrl_dma2acc:cdd28f78-e43e-4559-98cc-917b784fdd77-1331:msg:cdd28f78-e43e-4559-98cc-917b784fdd77-1342
   sc_lv< 160 > t_cdd28f78_e43e_4559_98cc_917b784fdd77_1342;
   sc_dt::sc_lv<160 > d_cdd28f78_e43e_4559_98cc_917b784fdd77_1342;
   if ( ccs_rtl_SIG_conf_info_ctrl_dma2acc_val.read() == SC_LOGIC_1 ) {
      t_cdd28f78_e43e_4559_98cc_917b784fdd77_1342 = ccs_rtl_SIG_conf_info_ctrl_dma2acc_msg.read();
      vector_to_type(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1342, 160, &d_cdd28f78_e43e_4559_98cc_917b784fdd77_1342);
      conf_info_ctrl_dma2acc.Connections::OutBlocking<conf_info_t, Connections::SYN_PORT >::msg.write(d_cdd28f78_e43e_4559_98cc_917b784fdd77_1342);
   }
   
   // none.sc_out field_key=conf_info_ctrl_plm2vec:cdd28f78-e43e-4559-98cc-917b784fdd77-1343:val:cdd28f78-e43e-4559-98cc-917b784fdd77-1348
   sc_logic t_cdd28f78_e43e_4559_98cc_917b784fdd77_1348;
   bool d_cdd28f78_e43e_4559_98cc_917b784fdd77_1348;
   t_cdd28f78_e43e_4559_98cc_917b784fdd77_1348 = ccs_rtl_SIG_conf_info_ctrl_plm2vec_val.read();
   vector_to_type(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1348, 1, &d_cdd28f78_e43e_4559_98cc_917b784fdd77_1348);
   conf_info_ctrl_plm2vec.Connections::OutBlocking_Ports_abs<conf_info_t >::val.write(d_cdd28f78_e43e_4559_98cc_917b784fdd77_1348);
   
   // none.sc_in field_key=conf_info_ctrl_plm2vec:cdd28f78-e43e-4559-98cc-917b784fdd77-1343:rdy:cdd28f78-e43e-4559-98cc-917b784fdd77-1349
   sc_logic t_cdd28f78_e43e_4559_98cc_917b784fdd77_1349; // NPS - LV to hold field
   type_to_vector(conf_info_ctrl_plm2vec.Connections::OutBlocking_Ports_abs<conf_info_t >::rdy.read(),1,t_cdd28f78_e43e_4559_98cc_917b784fdd77_1349); // read orig port and type convert
   ccs_rtl_SIG_conf_info_ctrl_plm2vec_rdy.write(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1349); // then write to RTL port
   
   // none.sc_out field_key=conf_info_ctrl_plm2vec:cdd28f78-e43e-4559-98cc-917b784fdd77-1343:msg:cdd28f78-e43e-4559-98cc-917b784fdd77-1350
   sc_lv< 160 > t_cdd28f78_e43e_4559_98cc_917b784fdd77_1350;
   sc_dt::sc_lv<160 > d_cdd28f78_e43e_4559_98cc_917b784fdd77_1350;
   if ( ccs_rtl_SIG_conf_info_ctrl_plm2vec_val.read() == SC_LOGIC_1 ) {
      t_cdd28f78_e43e_4559_98cc_917b784fdd77_1350 = ccs_rtl_SIG_conf_info_ctrl_plm2vec_msg.read();
      vector_to_type(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1350, 160, &d_cdd28f78_e43e_4559_98cc_917b784fdd77_1350);
      conf_info_ctrl_plm2vec.Connections::OutBlocking<conf_info_t, Connections::SYN_PORT >::msg.write(d_cdd28f78_e43e_4559_98cc_917b784fdd77_1350);
   }
   
   // none.sc_out field_key=conf_info_ctrl_acc2dma:cdd28f78-e43e-4559-98cc-917b784fdd77-1351:val:cdd28f78-e43e-4559-98cc-917b784fdd77-1356
   sc_logic t_cdd28f78_e43e_4559_98cc_917b784fdd77_1356;
   bool d_cdd28f78_e43e_4559_98cc_917b784fdd77_1356;
   t_cdd28f78_e43e_4559_98cc_917b784fdd77_1356 = ccs_rtl_SIG_conf_info_ctrl_acc2dma_val.read();
   vector_to_type(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1356, 1, &d_cdd28f78_e43e_4559_98cc_917b784fdd77_1356);
   conf_info_ctrl_acc2dma.Connections::OutBlocking_Ports_abs<conf_info_t >::val.write(d_cdd28f78_e43e_4559_98cc_917b784fdd77_1356);
   
   // none.sc_in field_key=conf_info_ctrl_acc2dma:cdd28f78-e43e-4559-98cc-917b784fdd77-1351:rdy:cdd28f78-e43e-4559-98cc-917b784fdd77-1357
   sc_logic t_cdd28f78_e43e_4559_98cc_917b784fdd77_1357; // NPS - LV to hold field
   type_to_vector(conf_info_ctrl_acc2dma.Connections::OutBlocking_Ports_abs<conf_info_t >::rdy.read(),1,t_cdd28f78_e43e_4559_98cc_917b784fdd77_1357); // read orig port and type convert
   ccs_rtl_SIG_conf_info_ctrl_acc2dma_rdy.write(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1357); // then write to RTL port
   
   // none.sc_out field_key=conf_info_ctrl_acc2dma:cdd28f78-e43e-4559-98cc-917b784fdd77-1351:msg:cdd28f78-e43e-4559-98cc-917b784fdd77-1358
   sc_lv< 160 > t_cdd28f78_e43e_4559_98cc_917b784fdd77_1358;
   sc_dt::sc_lv<160 > d_cdd28f78_e43e_4559_98cc_917b784fdd77_1358;
   if ( ccs_rtl_SIG_conf_info_ctrl_acc2dma_val.read() == SC_LOGIC_1 ) {
      t_cdd28f78_e43e_4559_98cc_917b784fdd77_1358 = ccs_rtl_SIG_conf_info_ctrl_acc2dma_msg.read();
      vector_to_type(t_cdd28f78_e43e_4559_98cc_917b784fdd77_1358, 160, &d_cdd28f78_e43e_4559_98cc_917b784fdd77_1358);
      conf_info_ctrl_acc2dma.Connections::OutBlocking<conf_info_t, Connections::SYN_PORT >::msg.write(d_cdd28f78_e43e_4559_98cc_917b784fdd77_1358);
   }
}
