# ----------------------------------------------------------------------------
# LeakyreluConfig Verilog
#
#    HLS version: 2025.1/1166825 Production Release
#       HLS date: Sun Feb 16 14:04:49 PST 2025
#  Flow Packages: HDL_Tcl 8.0a, SCVerify scver
#
#   Generated by: gtombesi@corsica
# Generated date: Thu May 08 18:59:15 EDT 2025
#
# ----------------------------------------------------------------------------
# ===================================================
# DEFAULT GOAL is the help target
.PHONY: all
all: help

# ===================================================
# Directories (at the time this makefile was created)
#   MGC_HOME      /opt/Catapult_2025/Mgc_home
#   PROJECT_HOME  /home/gtombesi/catapult_update_april24/esp/accelerators/catapult_hls/leakyrelu_sysc_catapult/hw/hls/leakyrelu_cfg
#   SOLUTION_DIR  /home/gtombesi/catapult_update_april24/esp/accelerators/catapult_hls/leakyrelu_sysc_catapult/hw/hls/leakyrelu_cfg/Catapult/leakyrelu_cfg.v1
#   WORKING_DIR   /home/gtombesi/catapult_update_april24/esp/accelerators/catapult_hls/leakyrelu_sysc_catapult/hw/hls/leakyrelu_cfg/Catapult/leakyrelu_cfg.v1/.

# ===================================================
# VARIABLES
# 
MGC_HOME          = /opt/Catapult_2025/Mgc_home
export MGC_HOME

WORK_DIR  = $(CURDIR)
WORK2PROJ = ../..
WORK2SOLN = .
PROJ2WORK = ./Catapult/leakyrelu_cfg.v1
PROJ2SOLN = ./Catapult/leakyrelu_cfg.v1
export WORK_DIR
export WORK2PROJ
export WORK2SOLN
export PROJ2WORK
export PROJ2SOLN

# Variables that can be overridden from the make command line
ifeq "$(INCL_DIRS)" ""
INCL_DIRS              = . ../../../../../../common/matchlib_toolkit/include ../../../../../../common/matchlib_toolkit/examples/boost_home ../../../../../../common/matchlib_toolkit/examples/matchlib/cmod/include ../../../../inc ../../../../tb ../../../../../../common/inc ../../../../../../common/inc/core/systems ../../../../inc/mem_bank ./scverify . ../.. $(MGC_HOME)/shared/include
endif
export INCL_DIRS
ifeq "$(STAGE)" ""
STAGE                  = rtl
endif
export STAGE
ifeq "$(NETLIST_LEAF)" ""
NETLIST_LEAF           = LeakyreluConfig
endif
export NETLIST_LEAF
ifeq "$(SIMTOOL)" ""
SIMTOOL                = msim
endif
export SIMTOOL
ifeq "$(NETLIST)" ""
NETLIST                = v
endif
export NETLIST
ifeq "$(INVOKE_ARGS)" ""
INVOKE_ARGS            = 
endif
export INVOKE_ARGS
export SCVLIBS
export MODELSIM
TOP_HDL_ENTITY           := LeakyreluConfig
TOP_DU                   := sc_main
TARGET                   := scverify/$(NETLIST_LEAF)_$(NETLIST)_$(SIMTOOL)
export TOP_HDL_ENTITY
export TARGET

ifeq ($(RECUR),)
ifeq ($(STAGE),mapped)
ifeq ($(RTLTOOL),)
   $(error This makefile requires specifying the RTLTOOL variable on the make command line)
endif
endif
endif
# ===================================================
# Include environment variables set by flow options
include ./ccs_env.mk

# ===================================================
# Include makefile for default commands and variables
include $(MGC_HOME)/shared/include/mkfiles/ccs_default_cmds.mk

SYNTHESIS_FLOWPKG := Vivado
SYN_FLOW          := Vivado
# ===================================================
# SOURCES
# 
# Specify list of Questa SIM libraries to create
HDL_LIB_NAMES = work
# ===================================================
# Simulation libraries required by loaded Catapult libraries or gate simulation
SIMLIBS_V   += 
SIMLIBS_VHD += 
# 
# 
# Specify list of source files - MUST be ordered properly
ifeq ($(STAGE),gate)
ifeq ($(RTLTOOL),)
# Unless overridden on make command line, GATE_*_DEP is the last item in the netlist dependency list
ifeq ($(GATE_VHDL_DEP),)
GATE_VHDL_DEP = 
endif
ifeq ($(GATE_VLOG_DEP),)
GATE_VLOG_DEP = ./LeakyreluConfig.v/LeakyreluConfig.v.vts
endif
endif
VHDL_SRC +=  $(GATE_VHDL_DEP) 
VLOG_SRC += ./LeakyreluConfig_ccs_ctrl_in_buf_wait_v4.v/LeakyreluConfig_ccs_ctrl_in_buf_wait_v4.v.vts ./LeakyreluConfig_ccs_out_buf_wait_v5.v/LeakyreluConfig_ccs_out_buf_wait_v5.v.vts $(GATE_VLOG_DEP) ./scverify/ccs_wrapper_LeakyreluConfig.v/ccs_wrapper_LeakyreluConfig.v.vts
else
VHDL_SRC += 
VLOG_SRC += ./LeakyreluConfig_ccs_ctrl_in_buf_wait_v4.v/LeakyreluConfig_ccs_ctrl_in_buf_wait_v4.v.vts ./LeakyreluConfig_ccs_out_buf_wait_v5.v/LeakyreluConfig_ccs_out_buf_wait_v5.v.vts ./LeakyreluConfig.v/LeakyreluConfig.v.vts ./scverify/ccs_wrapper_LeakyreluConfig.v/ccs_wrapper_LeakyreluConfig.v.vts
endif
CXX_SRC  = ../../../../tb/testbench.cpp/testbench.cpp.cxxts ../../../../tb/sc_main.cpp/sc_main.cpp.cxxts ./scverify/sysc_sim.cpp/sysc_sim.cpp.cxxts
# Specify RTL synthesis scripts (if any)
RTL_SCRIPT = 

# Specify hold time file name (for verifying synthesized netlists)
HLD_CONSTRAINT_FNAME = top_gate_constraints.cpp

# ===================================================
# GLOBAL OPTIONS
# 
# CXXFLAGS - global C++ options (apply to all C++ compilations) except for include file search paths
CXXFLAGS += $(COMPILERFLAGS) -DSC_INCLUDE_DYNAMIC_PROCESSES -DCCS_SYSC -DSC_USE_STD_STRING -DTOP_HDL_ENTITY=$(TOP_HDL_ENTITY) -DDMA_WIDTH=64
# 
# If the make command line includes a definition of the special variable MC_DEFAULT_TRANSACTOR_LOG
# then define that value for all compilations as well
ifneq "$(MC_DEFAULT_TRANSACTOR_LOG)" ""
CXXFLAGS += -DMC_DEFAULT_TRANSACTOR_LOG=$(MC_DEFAULT_TRANSACTOR_LOG)
endif
# 
# CXX_INCLUDES - include file search paths
CXX_INCLUDES = . ../../../../../../common/matchlib_toolkit/include ../../../../../../common/matchlib_toolkit/examples/boost_home ../../../../../../common/matchlib_toolkit/examples/matchlib/cmod/include ../../../../inc ../../../../tb ../../../../../../common/inc ../../../../../../common/inc/core/systems ../../../../inc/mem_bank ./scverify . ../.. $(MGC_HOME)/shared/include
# 
# TCL shell
TCLSH_CMD = /opt/Catapult_2025/Mgc_home/bin/tclsh8.5

# Pass along SCVerify_DEADLOCK_DETECTION option
ifneq "$(SCVerify_DEADLOCK_DETECTION)" "false"
CXXFLAGS += -DDEADLOCK_DETECTION
endif
# ===================================================
# PER SOURCE FILE SPECIALIZATIONS
# 
# Specify source file paths
ifeq ($(STAGE),gate)
ifneq ($(GATE_VHDL_DEP),)
$(TARGET)/$(notdir $(GATE_VHDL_DEP)): $(dir $(GATE_VHDL_DEP))
endif
ifneq ($(GATE_VLOG_DEP),)
$(TARGET)/$(notdir $(GATE_VLOG_DEP)): $(dir $(GATE_VLOG_DEP))
endif
endif
$(TARGET)/LeakyreluConfig_ccs_ctrl_in_buf_wait_v4.v.vts: ./LeakyreluConfig_ccs_ctrl_in_buf_wait_v4.v
$(TARGET)/LeakyreluConfig_ccs_out_buf_wait_v5.v.vts: ./LeakyreluConfig_ccs_out_buf_wait_v5.v
$(TARGET)/LeakyreluConfig.v.vts: ./LeakyreluConfig.v
$(TARGET)/ccs_wrapper_LeakyreluConfig.v.vts: ./scverify/ccs_wrapper_LeakyreluConfig.v
$(TARGET)/testbench.cpp.cxxts: ../../../../tb/testbench.cpp
$(TARGET)/sc_main.cpp.cxxts: ../../../../tb/sc_main.cpp
$(TARGET)/sysc_sim.cpp.cxxts: ./scverify/sysc_sim.cpp
# 
# Specify additional C++ options per C++ source by setting CXX_OPTS
$(TARGET)/sysc_sim.cpp.cxxts: CXX_OPTS=
$(TARGET)/sc_main.cpp.cxxts: CXX_OPTS=
$(TARGET)/testbench.cpp.cxxts: CXX_OPTS=
# 
# Specify dependencies
$(TARGET)/testbench.cpp.cxxts: .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts
$(TARGET)/sc_main.cpp.cxxts: .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts
$(TARGET)/sysc_sim.cpp.cxxts: .ccs_env_opts/SCVerify_USE_CCS_BLOCK.ts
# 
# Specify compilation library for HDL source
$(TARGET)/ccs_wrapper_LeakyreluConfig.v.vts: HDL_LIB=work
$(TARGET)/LeakyreluConfig_ccs_out_buf_wait_v5.v.vts: HDL_LIB=work
$(TARGET)/LeakyreluConfig_ccs_ctrl_in_buf_wait_v4.v.vts: HDL_LIB=work
$(TARGET)/LeakyreluConfig.v.vts: HDL_LIB=work
ifeq ($(STAGE),gate)
ifneq ($(GATE_VHDL_DEP),)
$(TARGET)/$(notdir $(GATE_VHDL_DEP)): HDL_LIB=work
$(TARGET)/$(notdir $(GATE_VHDL_DEP)): DUT_E=ccs_ctrl_in_buf_wait_v4
endif
ifneq ($(GATE_VLOG_DEP),)
$(TARGET)/$(notdir $(GATE_VLOG_DEP)): HDL_LIB=work
$(TARGET)/$(notdir $(GATE_VLOG_DEP)): DUT_E=ccs_ctrl_in_buf_wait_v4
endif
endif
# 
# Specify additional HDL source compilation options if any
$(TARGET)/ccs_wrapper_LeakyreluConfig.v.vts: VLOG_F_OPTS=
$(TARGET)/LeakyreluConfig_ccs_out_buf_wait_v5.v.vts: VLOG_F_OPTS=
$(TARGET)/LeakyreluConfig_ccs_ctrl_in_buf_wait_v4.v.vts: VLOG_F_OPTS=
$(TARGET)/LeakyreluConfig.v.vts: VLOG_F_OPTS=
$(TARGET)/ccs_wrapper_LeakyreluConfig.v.vts: NCVLOG_F_OPTS=
$(TARGET)/LeakyreluConfig_ccs_out_buf_wait_v5.v.vts: NCVLOG_F_OPTS=
$(TARGET)/LeakyreluConfig_ccs_ctrl_in_buf_wait_v4.v.vts: NCVLOG_F_OPTS=
$(TARGET)/LeakyreluConfig.v.vts: NCVLOG_F_OPTS=
$(TARGET)/ccs_wrapper_LeakyreluConfig.v.vts: VCS_F_OPTS=
$(TARGET)/LeakyreluConfig_ccs_out_buf_wait_v5.v.vts: VCS_F_OPTS=
$(TARGET)/LeakyreluConfig_ccs_ctrl_in_buf_wait_v4.v.vts: VCS_F_OPTS=
$(TARGET)/LeakyreluConfig.v.vts: VCS_F_OPTS=
# 
# Specify top design unit for HDL source
$(TARGET)/ccs_wrapper_LeakyreluConfig.v.vts: DUT_E=ccs_wrapper
$(TARGET)/LeakyreluConfig_ccs_out_buf_wait_v5.v.vts: DUT_E=ccs_out_buf_wait_v5
$(TARGET)/LeakyreluConfig_ccs_ctrl_in_buf_wait_v4.v.vts: DUT_E=ccs_ctrl_in_buf_wait_v4
$(TARGET)/LeakyreluConfig.v.vts: DUT_E=LeakyreluConfig

# Specify top design unit
$(TARGET)/ccs_wrapper_LeakyreluConfig.v.vts: VLOG_TOP=1

ifneq "$(RTLTOOL)" ""
# ===================================================
# Include makefile for RTL synthesis
include $(MGC_HOME)/shared/include/mkfiles/ccs_$(RTLTOOL).mk
else
# ===================================================
# Include makefile for simulator
include $(MGC_HOME)/shared/include/mkfiles/ccs_questasim.mk
endif

