#!/bin/ash

# System Shutdown Script
# Based on Cross-Compiled Linux From Scratch bootscripts

PATH=/bin:/sbin:/usr/bin:/usr/sbin

echo
echo "System is going down for reboot or halt now."
echo


echo "Starting stop scripts."

for i in /etc/rc.d/stop/*
do
	if [ -x $i ]; then
		$i stop
	fi
done

if [ -x /sbin/hwclock ] && [ -e /dev/rtc ]; then
	echo "Syncing hardware clock to system clock ... "
	hwclock --systohc --utc
fi

if [ -x /sbin/swapoff ]; then
	echo "Disabling swap space ... "
	swapoff -a
fi

echo "Syncing all filesystems ... "
sync

echo "Unmounting all filesystems ... "
umount -a -r

