#!/bin/sh
#
# ifdown hook script for resolvconf
#
# This file is part of the resolvconf package.
#

[ -x /sbin/resolvconf ] || exit 0

case "$ADDRFAM" in
  inet|inet6) :      ;;
  *)          exit 0 ;;
esac

case "$METHOD" in
  dhcp)
	# Delete record left behind by TERMinated udhcpc
	# This works around bug #605215
	/sbin/resolvconf -d "${IFACE}.udhcpc"
	;;
esac

/sbin/resolvconf -d "${IFACE}.${ADDRFAM}"

