# Copyright (c) 2011-2023 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
# FPGA and Dev Board used in Design
PART=xczu7ev
PACKAGE=ffvc1156
PROTOBOARD=xilinx.com:zcu106:part0:2.5
SPEED=2-e
