// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.cpp
//
//    HLS version: 2024.2/1130128 Production Release
//       HLS date: Mon Aug 26 21:59:12 PDT 2024
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: gtombesi@corsica
// Generated date: Wed Apr 30 13:21:58 EDT 2025
//
// ----------------------------------------------------------------------------
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model Ctrl
// -------------------------------------
// 
#include "sysc_sim.h"

double __scv_hold_time = 0.0; // default for non-gate simulation is zero


// ---------------------------------------------------------------
// Constructor: sysc_sim_wrapper

CCS_RTL::sysc_sim_wrapper::sysc_sim_wrapper(
   const sc_module_name& nm
)
   : ccs_rtl(
      "ccs_rtl",
      "ccs_wrapper"
   )
   , clk("clk")
   , rst("rst")
   , acc_done("acc_done")
   , conf_info("conf_info")
   , dma_read_chnl("dma_read_chnl")
   , dma_write_chnl("dma_write_chnl")
   , dma_read_ctrl("dma_read_ctrl")
   , dma_write_ctrl("dma_write_ctrl")
   , conf_info_out("conf_info_out")
   , sync00("sync00")
   , in_wr_req("in_wr_req")
   , in_rd_rsp("in_rd_rsp")
   , ccs_rtl_SIG_clk("ccs_rtl_SIG_clk")
   , ccs_rtl_SIG_rst("ccs_rtl_SIG_rst")
   , ccs_rtl_SIG_acc_done("ccs_rtl_SIG_acc_done")
   , ccs_rtl_SIG_conf_info_val("ccs_rtl_SIG_conf_info_val")
   , ccs_rtl_SIG_conf_info_rdy("ccs_rtl_SIG_conf_info_rdy")
   , ccs_rtl_SIG_conf_info_msg("ccs_rtl_SIG_conf_info_msg")
   , ccs_rtl_SIG_dma_read_chnl_val("ccs_rtl_SIG_dma_read_chnl_val")
   , ccs_rtl_SIG_dma_read_chnl_rdy("ccs_rtl_SIG_dma_read_chnl_rdy")
   , ccs_rtl_SIG_dma_read_chnl_msg("ccs_rtl_SIG_dma_read_chnl_msg")
   , ccs_rtl_SIG_dma_write_chnl_val("ccs_rtl_SIG_dma_write_chnl_val")
   , ccs_rtl_SIG_dma_write_chnl_rdy("ccs_rtl_SIG_dma_write_chnl_rdy")
   , ccs_rtl_SIG_dma_write_chnl_msg("ccs_rtl_SIG_dma_write_chnl_msg")
   , ccs_rtl_SIG_dma_read_ctrl_val("ccs_rtl_SIG_dma_read_ctrl_val")
   , ccs_rtl_SIG_dma_read_ctrl_rdy("ccs_rtl_SIG_dma_read_ctrl_rdy")
   , ccs_rtl_SIG_dma_read_ctrl_msg("ccs_rtl_SIG_dma_read_ctrl_msg")
   , ccs_rtl_SIG_dma_write_ctrl_val("ccs_rtl_SIG_dma_write_ctrl_val")
   , ccs_rtl_SIG_dma_write_ctrl_rdy("ccs_rtl_SIG_dma_write_ctrl_rdy")
   , ccs_rtl_SIG_dma_write_ctrl_msg("ccs_rtl_SIG_dma_write_ctrl_msg")
   , ccs_rtl_SIG_conf_info_out_val("ccs_rtl_SIG_conf_info_out_val")
   , ccs_rtl_SIG_conf_info_out_rdy("ccs_rtl_SIG_conf_info_out_rdy")
   , ccs_rtl_SIG_conf_info_out_msg("ccs_rtl_SIG_conf_info_out_msg")
   , ccs_rtl_SIG_sync00_val("ccs_rtl_SIG_sync00_val")
   , ccs_rtl_SIG_sync00_rdy("ccs_rtl_SIG_sync00_rdy")
   , ccs_rtl_SIG_sync00_msg("ccs_rtl_SIG_sync00_msg")
   , ccs_rtl_SIG_in_wr_req_val("ccs_rtl_SIG_in_wr_req_val")
   , ccs_rtl_SIG_in_wr_req_rdy("ccs_rtl_SIG_in_wr_req_rdy")
   , ccs_rtl_SIG_in_wr_req_msg("ccs_rtl_SIG_in_wr_req_msg")
   , ccs_rtl_SIG_in_rd_rsp_val("ccs_rtl_SIG_in_rd_rsp_val")
   , ccs_rtl_SIG_in_rd_rsp_rdy("ccs_rtl_SIG_in_rd_rsp_rdy")
   , ccs_rtl_SIG_in_rd_rsp_msg("ccs_rtl_SIG_in_rd_rsp_msg")
{
   // Instantiate other modules
   ccs_rtl.clk(ccs_rtl_SIG_clk);
   ccs_rtl.rst(ccs_rtl_SIG_rst);
   ccs_rtl.acc_done(ccs_rtl_SIG_acc_done);
   ccs_rtl.conf_info_val(ccs_rtl_SIG_conf_info_val);
   ccs_rtl.conf_info_rdy(ccs_rtl_SIG_conf_info_rdy);
   ccs_rtl.conf_info_msg(ccs_rtl_SIG_conf_info_msg);
   ccs_rtl.dma_read_chnl_val(ccs_rtl_SIG_dma_read_chnl_val);
   ccs_rtl.dma_read_chnl_rdy(ccs_rtl_SIG_dma_read_chnl_rdy);
   ccs_rtl.dma_read_chnl_msg(ccs_rtl_SIG_dma_read_chnl_msg);
   ccs_rtl.dma_write_chnl_val(ccs_rtl_SIG_dma_write_chnl_val);
   ccs_rtl.dma_write_chnl_rdy(ccs_rtl_SIG_dma_write_chnl_rdy);
   ccs_rtl.dma_write_chnl_msg(ccs_rtl_SIG_dma_write_chnl_msg);
   ccs_rtl.dma_read_ctrl_val(ccs_rtl_SIG_dma_read_ctrl_val);
   ccs_rtl.dma_read_ctrl_rdy(ccs_rtl_SIG_dma_read_ctrl_rdy);
   ccs_rtl.dma_read_ctrl_msg(ccs_rtl_SIG_dma_read_ctrl_msg);
   ccs_rtl.dma_write_ctrl_val(ccs_rtl_SIG_dma_write_ctrl_val);
   ccs_rtl.dma_write_ctrl_rdy(ccs_rtl_SIG_dma_write_ctrl_rdy);
   ccs_rtl.dma_write_ctrl_msg(ccs_rtl_SIG_dma_write_ctrl_msg);
   ccs_rtl.conf_info_out_val(ccs_rtl_SIG_conf_info_out_val);
   ccs_rtl.conf_info_out_rdy(ccs_rtl_SIG_conf_info_out_rdy);
   ccs_rtl.conf_info_out_msg(ccs_rtl_SIG_conf_info_out_msg);
   ccs_rtl.sync00_val(ccs_rtl_SIG_sync00_val);
   ccs_rtl.sync00_rdy(ccs_rtl_SIG_sync00_rdy);
   ccs_rtl.sync00_msg(ccs_rtl_SIG_sync00_msg);
   ccs_rtl.in_wr_req_val(ccs_rtl_SIG_in_wr_req_val);
   ccs_rtl.in_wr_req_rdy(ccs_rtl_SIG_in_wr_req_rdy);
   ccs_rtl.in_wr_req_msg(ccs_rtl_SIG_in_wr_req_msg);
   ccs_rtl.in_rd_rsp_val(ccs_rtl_SIG_in_rd_rsp_val);
   ccs_rtl.in_rd_rsp_rdy(ccs_rtl_SIG_in_rd_rsp_rdy);
   ccs_rtl.in_rd_rsp_msg(ccs_rtl_SIG_in_rd_rsp_msg);
   
   // Register processes
   SC_METHOD(update_proc);
   sensitive  << clk << rst << ccs_rtl_SIG_acc_done << conf_info.Connections::InBlocking_Ports_abs<conf_info_t >::val << ccs_rtl_SIG_conf_info_rdy << conf_info.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg << dma_read_chnl.Connections::InBlocking_Ports_abs<ac_int<64, true > >::val << ccs_rtl_SIG_dma_read_chnl_rdy << dma_read_chnl.Connections::InBlocking<ac_int<64, true >, Connections::SYN_PORT >::msg << ccs_rtl_SIG_dma_write_chnl_val << dma_write_chnl.Connections::OutBlocking_Ports_abs<ac_int<64, true > >::rdy << ccs_rtl_SIG_dma_write_chnl_msg << ccs_rtl_SIG_dma_read_ctrl_val << dma_read_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::rdy << ccs_rtl_SIG_dma_read_ctrl_msg << ccs_rtl_SIG_dma_write_ctrl_val << dma_write_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::rdy << ccs_rtl_SIG_dma_write_ctrl_msg << ccs_rtl_SIG_conf_info_out_val << conf_info_out.Connections::OutBlocking_Ports_abs<conf_info_t >::rdy << ccs_rtl_SIG_conf_info_out_msg << ccs_rtl_SIG_sync00_val << sync00.Connections::OutBlocking_Ports_abs<bool >::rdy << ccs_rtl_SIG_sync00_msg << in_wr_req.Connections::InBlocking_Ports_abs<ac_int<32, true > >::val << ccs_rtl_SIG_in_wr_req_rdy << in_wr_req.Connections::InBlocking<ac_int<32, true >, Connections::SYN_PORT >::msg << ccs_rtl_SIG_in_rd_rsp_val << in_rd_rsp.Connections::OutBlocking_Ports_abs<read_data >::rdy << ccs_rtl_SIG_in_rd_rsp_msg;
   // Other constructor statements
}

// ---------------------------------------------------------------
// Process: SC_METHOD update_proc

void CCS_RTL::sysc_sim_wrapper::update_proc() {
   
   // none.sc_in field_key=clk:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1432:clk:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1432
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1432; // NPS - LV to hold field
   ccs_rtl_SIG_clk.write(clk.read());
   
   // none.sc_in field_key=rst:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1433:rst:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1433
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1433; // NPS - LV to hold field
   type_to_vector(rst.read(),1,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1433); // read orig port and type convert
   ccs_rtl_SIG_rst.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1433); // then write to RTL port
   
   // none.sc_out field_key=acc_done:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1434:acc_done:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1434
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1434;
   bool d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1434;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1434 = ccs_rtl_SIG_acc_done.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1434, 1, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1434);
   acc_done.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1434);
   
   // none.sc_in field_key=conf_info:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1435:val:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1446
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1446; // NPS - LV to hold field
   type_to_vector(conf_info.Connections::InBlocking_Ports_abs<conf_info_t >::val.read(),1,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1446); // read orig port and type convert
   ccs_rtl_SIG_conf_info_val.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1446); // then write to RTL port
   
   // none.sc_out field_key=conf_info:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1435:rdy:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1447
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1447;
   bool d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1447;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1447 = ccs_rtl_SIG_conf_info_rdy.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1447, 1, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1447);
   conf_info.Connections::InBlocking_Ports_abs<conf_info_t >::rdy.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1447);
   
   // none.sc_in field_key=conf_info:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1435:msg:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1448
   sc_lv< 96 > t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1448; // NPS - LV to hold field
   type_to_vector(conf_info.Connections::InBlocking<conf_info_t, Connections::SYN_PORT >::msg.read(),96,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1448); // read orig port and type convert
   ccs_rtl_SIG_conf_info_msg.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1448); // then write to RTL port
   
   // none.sc_in field_key=dma_read_chnl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1449:val:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1458
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1458; // NPS - LV to hold field
   type_to_vector(dma_read_chnl.Connections::InBlocking_Ports_abs<ac_int<64, true > >::val.read(),1,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1458); // read orig port and type convert
   ccs_rtl_SIG_dma_read_chnl_val.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1458); // then write to RTL port
   
   // none.sc_out field_key=dma_read_chnl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1449:rdy:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1459
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1459;
   bool d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1459;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1459 = ccs_rtl_SIG_dma_read_chnl_rdy.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1459, 1, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1459);
   dma_read_chnl.Connections::InBlocking_Ports_abs<ac_int<64, true > >::rdy.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1459);
   
   // none.sc_in field_key=dma_read_chnl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1449:msg:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1460
   sc_lv< 64 > t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1460; // NPS - LV to hold field
   type_to_vector(dma_read_chnl.Connections::InBlocking<ac_int<64, true >, Connections::SYN_PORT >::msg.read(),64,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1460); // read orig port and type convert
   ccs_rtl_SIG_dma_read_chnl_msg.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1460); // then write to RTL port
   
   // none.sc_out field_key=dma_write_chnl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1461:val:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1470
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1470;
   bool d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1470;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1470 = ccs_rtl_SIG_dma_write_chnl_val.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1470, 1, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1470);
   dma_write_chnl.Connections::OutBlocking_Ports_abs<ac_int<64, true > >::val.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1470);
   
   // none.sc_in field_key=dma_write_chnl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1461:rdy:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1471
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1471; // NPS - LV to hold field
   type_to_vector(dma_write_chnl.Connections::OutBlocking_Ports_abs<ac_int<64, true > >::rdy.read(),1,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1471); // read orig port and type convert
   ccs_rtl_SIG_dma_write_chnl_rdy.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1471); // then write to RTL port
   
   // none.sc_out field_key=dma_write_chnl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1461:msg:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1472
   sc_lv< 64 > t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1472;
   sc_dt::sc_lv<64 > d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1472;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1472 = ccs_rtl_SIG_dma_write_chnl_msg.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1472, 64, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1472);
   dma_write_chnl.Connections::OutBlocking<ac_int<64, true >, Connections::SYN_PORT >::msg.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1472);
   
   // none.sc_out field_key=dma_read_ctrl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1473:val:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1482
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1482;
   bool d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1482;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1482 = ccs_rtl_SIG_dma_read_ctrl_val.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1482, 1, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1482);
   dma_read_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::val.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1482);
   
   // none.sc_in field_key=dma_read_ctrl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1473:rdy:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1483
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1483; // NPS - LV to hold field
   type_to_vector(dma_read_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::rdy.read(),1,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1483); // read orig port and type convert
   ccs_rtl_SIG_dma_read_ctrl_rdy.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1483); // then write to RTL port
   
   // none.sc_out field_key=dma_read_ctrl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1473:msg:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1484
   sc_lv< 73 > t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1484;
   sc_dt::sc_lv<73 > d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1484;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1484 = ccs_rtl_SIG_dma_read_ctrl_msg.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1484, 73, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1484);
   dma_read_ctrl.Connections::OutBlocking<dma_info_t, Connections::SYN_PORT >::msg.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1484);
   
   // none.sc_out field_key=dma_write_ctrl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1485:val:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1490
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1490;
   bool d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1490;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1490 = ccs_rtl_SIG_dma_write_ctrl_val.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1490, 1, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1490);
   dma_write_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::val.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1490);
   
   // none.sc_in field_key=dma_write_ctrl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1485:rdy:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1491
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1491; // NPS - LV to hold field
   type_to_vector(dma_write_ctrl.Connections::OutBlocking_Ports_abs<dma_info_t >::rdy.read(),1,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1491); // read orig port and type convert
   ccs_rtl_SIG_dma_write_ctrl_rdy.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1491); // then write to RTL port
   
   // none.sc_out field_key=dma_write_ctrl:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1485:msg:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1492
   sc_lv< 73 > t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1492;
   sc_dt::sc_lv<73 > d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1492;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1492 = ccs_rtl_SIG_dma_write_ctrl_msg.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1492, 73, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1492);
   dma_write_ctrl.Connections::OutBlocking<dma_info_t, Connections::SYN_PORT >::msg.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1492);
   
   // none.sc_out field_key=conf_info_out:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1493:val:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1502
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1502;
   bool d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1502;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1502 = ccs_rtl_SIG_conf_info_out_val.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1502, 1, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1502);
   conf_info_out.Connections::OutBlocking_Ports_abs<conf_info_t >::val.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1502);
   
   // none.sc_in field_key=conf_info_out:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1493:rdy:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1503
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1503; // NPS - LV to hold field
   type_to_vector(conf_info_out.Connections::OutBlocking_Ports_abs<conf_info_t >::rdy.read(),1,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1503); // read orig port and type convert
   ccs_rtl_SIG_conf_info_out_rdy.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1503); // then write to RTL port
   
   // none.sc_out field_key=conf_info_out:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1493:msg:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1504
   sc_lv< 96 > t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1504;
   sc_dt::sc_lv<96 > d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1504;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1504 = ccs_rtl_SIG_conf_info_out_msg.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1504, 96, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1504);
   conf_info_out.Connections::OutBlocking<conf_info_t, Connections::SYN_PORT >::msg.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1504);
   
   // none.sc_out field_key=sync00:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1505:val:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1514
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1514;
   bool d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1514;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1514 = ccs_rtl_SIG_sync00_val.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1514, 1, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1514);
   sync00.Connections::OutBlocking_Ports_abs<bool >::val.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1514);
   
   // none.sc_in field_key=sync00:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1505:rdy:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1515
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1515; // NPS - LV to hold field
   type_to_vector(sync00.Connections::OutBlocking_Ports_abs<bool >::rdy.read(),1,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1515); // read orig port and type convert
   ccs_rtl_SIG_sync00_rdy.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1515); // then write to RTL port
   
   // none.sc_out field_key=sync00:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1505:msg:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1516
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1516;
   sc_dt::sc_lv<1 > d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1516;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1516 = ccs_rtl_SIG_sync00_msg.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1516, 1, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1516);
   sync00.Connections::OutBlocking<bool, Connections::SYN_PORT >::msg.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1516);
   
   // none.sc_in field_key=in_wr_req:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1517:val:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1526
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1526; // NPS - LV to hold field
   type_to_vector(in_wr_req.Connections::InBlocking_Ports_abs<ac_int<32, true > >::val.read(),1,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1526); // read orig port and type convert
   ccs_rtl_SIG_in_wr_req_val.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1526); // then write to RTL port
   
   // none.sc_out field_key=in_wr_req:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1517:rdy:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1527
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1527;
   bool d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1527;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1527 = ccs_rtl_SIG_in_wr_req_rdy.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1527, 1, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1527);
   in_wr_req.Connections::InBlocking_Ports_abs<ac_int<32, true > >::rdy.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1527);
   
   // none.sc_in field_key=in_wr_req:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1517:msg:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1528
   sc_lv< 32 > t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1528; // NPS - LV to hold field
   type_to_vector(in_wr_req.Connections::InBlocking<ac_int<32, true >, Connections::SYN_PORT >::msg.read(),32,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1528); // read orig port and type convert
   ccs_rtl_SIG_in_wr_req_msg.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1528); // then write to RTL port
   
   // none.sc_out field_key=in_rd_rsp:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1529:val:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1538
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1538;
   bool d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1538;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1538 = ccs_rtl_SIG_in_rd_rsp_val.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1538, 1, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1538);
   in_rd_rsp.Connections::OutBlocking_Ports_abs<read_data >::val.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1538);
   
   // none.sc_in field_key=in_rd_rsp:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1529:rdy:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1539
   sc_logic t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1539; // NPS - LV to hold field
   type_to_vector(in_rd_rsp.Connections::OutBlocking_Ports_abs<read_data >::rdy.read(),1,t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1539); // read orig port and type convert
   ccs_rtl_SIG_in_rd_rsp_rdy.write(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1539); // then write to RTL port
   
   // none.sc_out field_key=in_rd_rsp:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1529:msg:9d01e564-b420-4dbb-bbec-bb9cd4b67904-1540
   sc_lv< 64 > t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1540;
   sc_dt::sc_lv<64 > d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1540;
   t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1540 = ccs_rtl_SIG_in_rd_rsp_msg.read();
   vector_to_type(t_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1540, 64, &d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1540);
   in_rd_rsp.Connections::OutBlocking<read_data, Connections::SYN_PORT >::msg.write(d_9d01e564_b420_4dbb_bbec_bb9cd4b67904_1540);
}
