// ----------------------------------------------------------------------------
// SystemC SCVerify Flow -- sysc_sim.h
//
//    HLS version: 2024.2/1130128 Production Release
//       HLS date: Mon Aug 26 21:59:12 PDT 2024
//  Flow Packages: HDL_Tcl 8.0a, SCVerify 10.4
//
//   Generated by: gtombesi@corsica
// Generated date: Wed Apr 30 13:21:58 EDT 2025
//
// ----------------------------------------------------------------------------
#ifndef INCLUDED_SYSC_SIM_WRAPPER_H
#define INCLUDED_SYSC_SIM_WRAPPER_H
// 
// -------------------------------------
// sysc_sim_wrapper
// Represents a new SC_MODULE having the same interface as the original model Ctrl
// -------------------------------------
// 

#ifndef TO_QUOTED_STRING
#define TO_QUOTED_STRING(x) TO_QUOTED_STRING1(x)
#define TO_QUOTED_STRING1(x) #x
#endif
extern double __scv_hold_time;


#ifndef SC_USE_STD_STRING
#define SC_USE_STD_STRING
#endif

#include "../../../../inc/Ctrl.h"
#include <systemc.h>
#include <mc_stall_ctrl.h>
#include <mc_scv_trans.h>
#include "mc_dut_wrapper.h"


namespace CCS_RTL {
   class sysc_sim_wrapper : public sc_module
   {
   public:
      // Module instance pointers
      HDL::ccs_DUT_wrapper ccs_rtl;
      
      // Interface Ports
      sc_core::sc_in<bool > clk;
      sc_core::sc_in<bool > rst;
      sc_core::sc_out<bool > acc_done;
      Connections::In<conf_info_t, Connections::SYN_PORT > conf_info;
      Connections::In<ac_int<64, true >, Connections::SYN_PORT > dma_read_chnl;
      Connections::Out<ac_int<64, true >, Connections::SYN_PORT > dma_write_chnl;
      Connections::Out<dma_info_t, Connections::SYN_PORT > dma_read_ctrl;
      Connections::Out<dma_info_t, Connections::SYN_PORT > dma_write_ctrl;
      Connections::Out<conf_info_t, Connections::SYN_PORT > conf_info_out;
      Connections::Out<bool, Connections::SYN_PORT > sync00;
      Connections::In<ac_int<32, true >, Connections::SYN_PORT > in_wr_req;
      Connections::Out<read_data, Connections::SYN_PORT > in_rd_rsp;
      
      // Named Objects
      
      // Data objects
      sc_signal< bool >                          ccs_rtl_SIG_clk;
      sc_signal< sc_logic >                      ccs_rtl_SIG_rst;
      sc_signal< sc_logic >                      ccs_rtl_SIG_acc_done;
      sc_signal< sc_logic >                      ccs_rtl_SIG_conf_info_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_conf_info_rdy;
      sc_signal< sc_lv<96> >                     ccs_rtl_SIG_conf_info_msg;
      sc_signal< sc_logic >                      ccs_rtl_SIG_dma_read_chnl_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_dma_read_chnl_rdy;
      sc_signal< sc_lv<64> >                     ccs_rtl_SIG_dma_read_chnl_msg;
      sc_signal< sc_logic >                      ccs_rtl_SIG_dma_write_chnl_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_dma_write_chnl_rdy;
      sc_signal< sc_lv<64> >                     ccs_rtl_SIG_dma_write_chnl_msg;
      sc_signal< sc_logic >                      ccs_rtl_SIG_dma_read_ctrl_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_dma_read_ctrl_rdy;
      sc_signal< sc_lv<73> >                     ccs_rtl_SIG_dma_read_ctrl_msg;
      sc_signal< sc_logic >                      ccs_rtl_SIG_dma_write_ctrl_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_dma_write_ctrl_rdy;
      sc_signal< sc_lv<73> >                     ccs_rtl_SIG_dma_write_ctrl_msg;
      sc_signal< sc_logic >                      ccs_rtl_SIG_conf_info_out_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_conf_info_out_rdy;
      sc_signal< sc_lv<96> >                     ccs_rtl_SIG_conf_info_out_msg;
      sc_signal< sc_logic >                      ccs_rtl_SIG_sync00_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_sync00_rdy;
      sc_signal< sc_logic >                      ccs_rtl_SIG_sync00_msg;
      sc_signal< sc_logic >                      ccs_rtl_SIG_in_wr_req_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_in_wr_req_rdy;
      sc_signal< sc_lv<32> >                     ccs_rtl_SIG_in_wr_req_msg;
      sc_signal< sc_logic >                      ccs_rtl_SIG_in_rd_rsp_val;
      sc_signal< sc_logic >                      ccs_rtl_SIG_in_rd_rsp_rdy;
      sc_signal< sc_lv<64> >                     ccs_rtl_SIG_in_rd_rsp_msg;
      
      // Declare processes (SC_METHOD and SC_THREAD)
      void update_proc();
      
      // Constructor
      SC_HAS_PROCESS(sysc_sim_wrapper);
      sysc_sim_wrapper(
         const sc_module_name& nm
      );
      ~sysc_sim_wrapper()
      {
      }
      
      // C++ class functions
   };
} // end namespace CCS_RTL
#endif //INCLUDED_SYSC_SIM_WRAPPER_H
