# TODO: read HLS configuration from device registers instead
EXTRA_CFLAGS ?= -DFFT2_FX_WIDTH=32
APPNAME := fft2

#$(info $$DRIVERS  is [${DRIVERS}])
#$(info $$FFT2_FX_WIDTH  is [${FFT2_FX_WIDTH}])
include $(DRIVERS)/common.mk
