#!/usr/bin/groovy

//@Library('sld-lib-jenkins') _

pipeline {
    agent any
    // libraries {
    //     lib 'sld-lib-jenkins'
    // }

    triggers {
      githubPush()
    }
    stages {
        stage('start') {
	    steps {
		// send build started notifications
		sendNotifications buildStatus: 'STARTED', durationString: currentBuild.durationString
	    }
        }
        stage('build') {
            steps {
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
        stage('deploy') {
            steps {
                retry(3) {
                    sh 'echo "execute retrying 3 times"'
                }
                timeout(time: 3, unit: 'MINUTES') {
                    retry(2) {
                        sh 'echo "execute with timeout of 3 minutes"'
                    }
                }
	        }
        }
    }

    post {
        always {
            echo 'The run completed.'
	    sendNotifications buildStatus: currentBuild.result, durationString: currentBuild.durationString
        }
        success {
            echo 'Success: the run succeeded.'
        }
        failure {
            echo 'Failure: the run failed.'
        }
	aborted {
	    echo 'Aborted: the run was "aborted", usually due to the Pipeline being manually aborted.'
	}
        unstable {
            echo 'Unstable: run has an "unstable" status, usually caused by test failures, code violations, etc...'
        }
        changed {
	    echo 'Changed: the run has a different completion status as compared to the previous run.'
	    fixed {
		echo 'Fixed: the run is successful and the previous run failed or was unstable.'
	    }
	    regression {
		echo 'Regression: run’s status is failure, unstable, or aborted and the previous run was successful.'
	    }
        }
	cleanup {
	    echo 'Cleanup: all other Post steps have been evaluated.'
	}
    }
}
