# Copyright (c) 2011-2023 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
EXTRA_CFLAGS ?= -std=c99 -DUSE_ESP_INTERFACE -DRUN_HW
APPNAME := vitbfly2
include $(DRIVERS)/common.mk
