// Copyright (c) 2011-2019 Columbia University, System Level Design Group
// SPDX-License-Identifier: Apache-2.0

#ifndef __LAYERS_HPP__
#define __LAYERS_HPP__

#include "tb_config.hpp"
#include "sizes.h"

#if defined(CONV1_1)
#define CONV_F_HEIGHT		(CONV1_1_F_HEIGHT)
#define CONV_F_WIDTH		(CONV1_1_F_WIDTH)
#define CONV_F_CHANNELS		(CONV1_1_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV1_1_W_HEIGHT)
#define CONV_K_WIDTH		(CONV1_1_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV1_1_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV1_1_W_OUT_CHANNELS)

#elif defined(CONV1_2)
#define CONV_F_HEIGHT		(CONV1_2_F_HEIGHT)
#define CONV_F_WIDTH		(CONV1_2_F_WIDTH)
#define CONV_F_CHANNELS		(CONV1_2_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV1_2_W_HEIGHT)
#define CONV_K_WIDTH		(CONV1_2_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV1_2_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV1_2_W_OUT_CHANNELS)

#elif defined(CONV2_1)
#define CONV_F_HEIGHT		(CONV2_1_F_HEIGHT)
#define CONV_F_WIDTH		(CONV2_1_F_WIDTH)
#define CONV_F_CHANNELS		(CONV2_1_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV2_1_W_HEIGHT)
#define CONV_K_WIDTH		(CONV2_1_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV2_1_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV2_1_W_OUT_CHANNELS)

#elif defined(CONV2_2)
#define CONV_F_HEIGHT		(CONV2_2_F_HEIGHT)
#define CONV_F_WIDTH		(CONV2_2_F_WIDTH)
#define CONV_F_CHANNELS		(CONV2_2_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV2_2_W_HEIGHT)
#define CONV_K_WIDTH		(CONV2_2_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV2_2_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV2_2_W_OUT_CHANNELS)

#elif defined(CONV3_1)
#define CONV_F_HEIGHT		(CONV3_1_F_HEIGHT)
#define CONV_F_WIDTH		(CONV3_1_F_WIDTH)
#define CONV_F_CHANNELS		(CONV3_1_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV3_1_W_HEIGHT)
#define CONV_K_WIDTH		(CONV3_1_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV3_1_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV3_1_W_OUT_CHANNELS)

#elif defined(CONV3_2)
#define CONV_F_HEIGHT		(CONV3_2_F_HEIGHT)
#define CONV_F_WIDTH		(CONV3_2_F_WIDTH)
#define CONV_F_CHANNELS		(CONV3_2_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV3_2_W_HEIGHT)
#define CONV_K_WIDTH		(CONV3_2_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV3_2_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV3_2_W_OUT_CHANNELS)

#elif defined(CONV3_3)
#define CONV_F_HEIGHT		(CONV3_3_F_HEIGHT)
#define CONV_F_WIDTH		(CONV3_3_F_WIDTH)
#define CONV_F_CHANNELS		(CONV3_3_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV3_3_W_HEIGHT)
#define CONV_K_WIDTH		(CONV3_3_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV3_3_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV3_3_W_OUT_CHANNELS)

#elif defined(CONV4_1)
#define CONV_F_HEIGHT		(CONV4_1_F_HEIGHT)
#define CONV_F_WIDTH		(CONV4_1_F_WIDTH)
#define CONV_F_CHANNELS		(CONV4_1_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV4_1_W_HEIGHT)
#define CONV_K_WIDTH		(CONV4_1_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV4_1_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV4_1_W_OUT_CHANNELS)

#elif defined(CONV4_2)
#define CONV_F_HEIGHT		(CONV4_2_F_HEIGHT)
#define CONV_F_WIDTH		(CONV4_2_F_WIDTH)
#define CONV_F_CHANNELS		(CONV4_2_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV4_2_W_HEIGHT)
#define CONV_K_WIDTH		(CONV4_2_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV4_2_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV4_2_W_OUT_CHANNELS)

#elif defined(CONV4_3)
#define CONV_F_HEIGHT		(CONV4_3_F_HEIGHT)
#define CONV_F_WIDTH		(CONV4_3_F_WIDTH)
#define CONV_F_CHANNELS		(CONV4_3_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV4_3_W_HEIGHT)
#define CONV_K_WIDTH		(CONV4_3_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV4_3_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV4_3_W_OUT_CHANNELS)

#elif defined(CONV5_1)
#define CONV_F_HEIGHT		(CONV5_1_F_HEIGHT)
#define CONV_F_WIDTH		(CONV5_1_F_WIDTH)
#define CONV_F_CHANNELS		(CONV5_1_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV5_1_W_HEIGHT)
#define CONV_K_WIDTH		(CONV5_1_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV5_1_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV5_1_W_OUT_CHANNELS)

#elif defined(CONV5_2)
#define CONV_F_HEIGHT		(CONV5_2_F_HEIGHT)
#define CONV_F_WIDTH		(CONV5_2_F_WIDTH)
#define CONV_F_CHANNELS		(CONV5_2_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV5_2_W_HEIGHT)
#define CONV_K_WIDTH		(CONV5_2_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV5_2_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV5_2_W_OUT_CHANNELS)


#elif defined(CONV5_3)
#define CONV_F_HEIGHT		(CONV5_3_F_HEIGHT)
#define CONV_F_WIDTH		(CONV5_3_F_WIDTH)
#define CONV_F_CHANNELS		(CONV5_3_F_CHANNELS)
#define CONV_K_HEIGHT		(CONV5_3_W_HEIGHT)
#define CONV_K_WIDTH		(CONV5_3_W_WIDTH)
#define CONV_K_IN_CHANNELS	(CONV5_3_W_IN_CHANNELS)
#define CONV_K_OUT_CHANNELS	(CONV5_3_W_OUT_CHANNELS)


#elif defined(TINY)
#define CONV_F_HEIGHT		(6)
#define CONV_F_WIDTH		(6)
#define CONV_F_CHANNELS		(2)

#define CONV_K_HEIGHT		(3)
#define CONV_K_WIDTH		(3)
#define CONV_K_IN_CHANNELS	(2)
#define CONV_K_OUT_CHANNELS	(2)

#else
#error "Layer not defined"
#endif


const int conv_f_height = CONV_F_HEIGHT;
const int conv_f_width = CONV_F_WIDTH;
const int conv_f_channels = CONV_F_CHANNELS;

const int conv_k_height = CONV_K_HEIGHT;
const int conv_k_width = CONV_K_WIDTH;
const int conv_k_in_channels = CONV_K_IN_CHANNELS;
const int conv_k_out_channels = CONV_K_OUT_CHANNELS;

#endif // __LAYERS_HPP__
