# Copyright (c) 2011-2026 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
# FPGA device used by the Terasic DE10-Pro SX Quartus project.
QUARTUS_DEVICE=1SX280HU2F50E1VG
