# Copyright (c) 2011-2026 Columbia University, System Level Design Group
# SPDX-License-Identifier: Apache-2.0
# FPGA settings used by the generated Terasic DE10-Pro SX Quartus project.
QUARTUS_DEVICE = 1SX280HU2F50E1VG
QUARTUS_TOP = ghrd_s10_top
QUARTUS_QSYS_ACCEPT_GENERATED_TOP = 1
QUARTUS_QSYS_PROJECT_MODE = generated-files-qip
