#ifndef CONFIG_MCTRLFT
#define CONFIG_MCTRLFT 0
#endif

#ifndef CONFIG_MCTRLFT_SDRAM
#define CONFIG_MCTRLFT_SDRAM 0
#endif

#ifndef CONFIG_MCTRLFT_SDRAM_SEPBUS
#define CONFIG_MCTRLFT_SDRAM_SEPBUS 0
#endif

#ifndef CONFIG_MCTRLFT_SDRAM_INVCLK
#define CONFIG_MCTRLFT_SDRAM_INVCLK 0
#endif

#ifndef CONFIG_MCTRLFT_8BIT
#define CONFIG_MCTRLFT_8BIT 0
#endif

#ifndef CONFIG_MCTRLFT_16BIT
#define CONFIG_MCTRLFT_16BIT 0
#endif

#ifndef CONFIG_MCTRLFT_5CS
#define CONFIG_MCTRLFT_5CS 0
#endif

#ifndef CONFIG_MCTRLFT_EDAC
#define CONFIG_MCTRLFT_EDAC 0
#endif

#ifndef CONFIG_MCTRLFT_EDACPIPE
#define CONFIG_MCTRLFT_EDACPIPE 0
#endif

#ifndef CONFIG_MCTRLFT_RSEDAC
#define CONFIG_MCTRLFT_RSEDAC 0
#endif

#ifndef CONFIG_MCTRLFT_PAGE
#define CONFIG_MCTRLFT_PAGE 0
#endif

#ifndef CONFIG_MCTRLFT_PROGPAGE
#define CONFIG_MCTRLFT_PROGPAGE 0
#endif

#if defined CONFIG_MCTRLFT_ROMASEL0
#define CFG_M_CTRLFT_ROMASEL 0
#elif defined CONFIG_MCTRLFT_ROMASEL1
#define CFG_M_CTRLFT_ROMASEL 1
#elif defined CONFIG_MCTRLFT_ROMASEL2
#define CFG_M_CTRLFT_ROMASEL 2
#elif defined CONFIG_MCTRLFT_ROMASEL3
#define CFG_M_CTRLFT_ROMASEL 3
#elif defined CONFIG_MCTRLFT_ROMASEL4
#define CFG_M_CTRLFT_ROMASEL 4
#elif defined CONFIG_MCTRLFT_ROMASEL5
#define CFG_M_CTRLFT_ROMASEL 5
#elif defined CONFIG_MCTRLFT_ROMASEL6
#define CFG_M_CTRLFT_ROMASEL 6
#elif defined CONFIG_MCTRLFT_ROMASEL7
#define CFG_M_CTRLFT_ROMASEL 7
#elif defined CONFIG_MCTRLFT_ROMASEL8
#define CFG_M_CTRLFT_ROMASEL 8
#elif defined CONFIG_MCTRLFT_ROMASEL9
#define CFG_M_CTRLFT_ROMASEL 9
#elif defined CONFIG_MCTRLFT_ROMASEL10
#define CFG_M_CTRLFT_ROMASEL 10
#elif defined CONFIG_MCTRLFT_ROMASEL11
#define CFG_M_CTRLFT_ROMASEL 11
#elif defined CONFIG_MCTRLFT_ROMASEL12
#define CFG_M_CTRLFT_ROMASEL 12
#elif defined CONFIG_MCTRLFT_ROMASEL13
#define CFG_M_CTRLFT_ROMASEL 13
#elif defined CONFIG_MCTRLFT_ROMASEL14
#define CFG_M_CTRLFT_ROMASEL 14
#elif defined CONFIG_MCTRLFT_ROMASEL15
#define CFG_M_CTRLFT_ROMASEL 15
#elif defined CONFIG_MCTRLFT_ROMASEL16
#define CFG_M_CTRLFT_ROMASEL 16
#elif defined CONFIG_MCTRLFT_ROMASEL17
#define CFG_M_CTRLFT_ROMASEL 17
#elif defined CONFIG_MCTRLFT_ROMASEL18
#define CFG_M_CTRLFT_ROMASEL 18
#elif defined CONFIG_MCTRLFT_ROMASEL19
#define CFG_M_CTRLFT_ROMASEL 19
#elif defined CONFIG_MCTRLFT_ROMASEL20
#define CFG_M_CTRLFT_ROMASEL 20
#elif defined CONFIG_MCTRLFT_ROMASEL21
#define CFG_M_CTRLFT_ROMASEL 21
#elif defined CONFIG_MCTRLFT_ROMASEL22
#define CFG_M_CTRLFT_ROMASEL 22
#elif defined CONFIG_MCTRLFT_ROMASEL23
#define CFG_M_CTRLFT_ROMASEL 23
#elif defined CONFIG_MCTRLFT_ROMASEL24
#define CFG_M_CTRLFT_ROMASEL 24
#elif defined CONFIG_MCTRLFT_ROMASEL25
#define CFG_M_CTRLFT_ROMASEL 25
#elif defined CONFIG_MCTRLFT_ROMASEL26
#define CFG_M_CTRLFT_ROMASEL 26
#elif defined CONFIG_MCTRLFT_ROMASEL27
#define CFG_M_CTRLFT_ROMASEL 27
#elif defined CONFIG_MCTRLFT_ROMASEL28
#define CFG_M_CTRLFT_ROMASEL 28
#else
#define CFG_M_CTRLFT_ROMASEL 0
#endif

#ifndef CONFIG_MCTRLFT_WFB
#define CONFIG_MCTRLFT_WFB 0
#endif

#ifndef CONFIG_MCTRLFT_NETLIST
#define CONFIG_MCTRLFT_NETLIST 0
#endif

#ifndef CONFIG_MCTRLFT_SDRAM_BUS64
#define CONFIG_MCTRLFT_SDRAM_BUS64 0
#endif

