name: Regression Test Pro

on:
  push:
    branches:
      - regression-testing

jobs:
  regression-pro:
    name: Regression Test Pro Test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: regression-testing
      
      - name: Test workflow with hello
        run: echo "hello"

      - name: Submodule installation
        run: ./submodule_init.sh
        working-directory: ./utils/scripts
      
      - name: Grant permissions to actions-pipeline
        run: chmod 700 *.sh
        working-directory: ./utils/scripts/actions-pipeline
      
      - name: Grant permissions to helper
        run: chmod 700 *.sh
        working-directory: ./utils/scripts/actions-pipeline/helper
      
      - name: Run SoC flow script
        run: ./run_esp-soft.sh
        working-directory: ./utils/scripts/actions-pipeline