name: Regression Test Pro

on:
  push:
    branches:
      - regression-testing

jobs:
  regression-pro:
    name: Regression Test Pro Test
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: regression-testing
      
      - name: Set sysroot
        run: |
          cp /opt/sysroot.tgz ./sysroot.tgz
          tar -xzf ./sysroot.tgz -C ./ariane
          rm -f ./sysroot.tgz
        working-directory: ./soft

      - name: Install submodule
        run: ./utils/scripts/submodule_init.sh
      
      - name: Grant permissions to actions-pipeline
        run: chmod +x *.sh
        working-directory: ./utils/scripts/actions-pipeline
      
      - name: Grant permissions to helper
        run: chmod +x *.sh
        working-directory: ./utils/scripts/actions-pipeline/helper
      
      - name: Run full workflow script
        run: |
          ./run_workflow.sh
        working-directory: ./utils/scripts/actions-pipeline